export type StatisticsSchoolItem = {
  rank: number;
  schoolName: string;
  districtName: string;
  casePolicyLabel: string;
  caseStatusLabel: string;
  potentialDemand2029: number;
  potentialDemand2031: number;
  nearestParkDistanceM: number;
  greenRatio: number;
  playgroundCount: number;
  currentStudentCount: number;
};

export type DistrictStatistics = {
  districtName: string;
  schoolCount: number;
  case1Count: number;
  case2Count: number;
  case3Count: number;
  case4Count: number;
  specialPolicyCount: number;
  priorityReviewCount: number;
  totalPotentialDemand2029: number;
  totalPotentialDemand2031: number;
  avgNearestParkDistanceM: number;
  avgGreenRatio: number;
  avgPlaygroundCount: number;
  topPrioritySchools: StatisticsSchoolItem[];
  topPrioritySchoolsPlaygroundFocused: StatisticsSchoolItem[];
  topPrioritySchoolsStudentFocused: StatisticsSchoolItem[];
  bestSchool: StatisticsSchoolItem;
};

export type CityStatisticsData = {
  cityName: string;
  summary: {
    schoolCount: number;
    districtCount: number;
    case1Count: number;
    case2Count: number;
    case3Count: number;
    case4Count: number;
    separateBundleCount: number;
    urgentSupportCount: number;
    priorityReviewCount: number;
    apartmentPermeabilitySchoolCount: number;
    apartmentAdjustmentCandidateCount: number;
    totalPotentialDemand2029: number;
    totalPotentialDemand2031: number;
  };
  districts: DistrictStatistics[];
  cityTopPrioritySchools: StatisticsSchoolItem[];
  cityTopPrioritySchoolsPlaygroundFocused: StatisticsSchoolItem[];
  cityTopPrioritySchoolsStudentFocused: StatisticsSchoolItem[];
  cityBestSchool: StatisticsSchoolItem;
};

export const cityStatisticsPreviewDataSafe: CityStatisticsData = {
  "cityName": "인천광역시",
  "summary": {
    "schoolCount": 272,
    "districtCount": 10,
    "case1Count": 17,
    "case2Count": 68,
    "case3Count": 77,
    "case4Count": 80,
    "separateBundleCount": 30,
    "urgentSupportCount": 17,
    "priorityReviewCount": 68,
    "apartmentPermeabilitySchoolCount": 206,
    "apartmentAdjustmentCandidateCount": 194,
    "totalPotentialDemand2029": 120035,
    "totalPotentialDemand2031": 108184
  },
  "districts": [
    {
      "districtName": "중구",
      "schoolCount": 16,
      "case1Count": 6,
      "case2Count": 0,
      "case3Count": 1,
      "case4Count": 9,
      "specialPolicyCount": 0,
      "priorityReviewCount": 0,
      "totalPotentialDemand2029": 9632,
      "totalPotentialDemand2031": 9629,
      "avgNearestParkDistanceM": 1259.4,
      "avgGreenRatio": 7.2,
      "avgPlaygroundCount": 1.81,
      "topPrioritySchools": [
        {
          "rank": 1,
          "schoolName": "인천용유초등학교",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 26,
          "potentialDemand2031": 25,
          "nearestParkDistanceM": 13471.8,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 33
        },
        {
          "rank": 2,
          "schoolName": "인천영종초등학교금산분교장",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 43,
          "potentialDemand2031": 37,
          "nearestParkDistanceM": 1587.3,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 47
        },
        {
          "rank": 3,
          "schoolName": "인천신선초등학교",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 202,
          "potentialDemand2031": 159,
          "nearestParkDistanceM": 796.8,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 286
        },
        {
          "rank": 4,
          "schoolName": "인천연안초등학교",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 42,
          "potentialDemand2031": 18,
          "nearestParkDistanceM": 620.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 104
        },
        {
          "rank": 5,
          "schoolName": "인천신흥초등학교",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 263,
          "potentialDemand2031": 230,
          "nearestParkDistanceM": 722.2,
          "greenRatio": 0.0,
          "playgroundCount": 1,
          "currentStudentCount": 312
        }
      ],
      "topPrioritySchoolsPlaygroundFocused": [
        {
          "rank": 1,
          "schoolName": "인천신선초등학교",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 202,
          "potentialDemand2031": 159,
          "nearestParkDistanceM": 796.8,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 286
        },
        {
          "rank": 2,
          "schoolName": "인천연안초등학교",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 42,
          "potentialDemand2031": 18,
          "nearestParkDistanceM": 620.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 104
        },
        {
          "rank": 3,
          "schoolName": "인천영종초등학교금산분교장",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 43,
          "potentialDemand2031": 37,
          "nearestParkDistanceM": 1587.3,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 47
        },
        {
          "rank": 4,
          "schoolName": "인천용유초등학교",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 26,
          "potentialDemand2031": 25,
          "nearestParkDistanceM": 13471.8,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 33
        },
        {
          "rank": 5,
          "schoolName": "인천신광초등학교",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 673,
          "potentialDemand2031": 663,
          "nearestParkDistanceM": 533.7,
          "greenRatio": 0.0,
          "playgroundCount": 1,
          "currentStudentCount": 699
        }
      ],
      "topPrioritySchoolsStudentFocused": [
        {
          "rank": 1,
          "schoolName": "인천신광초등학교",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 673,
          "potentialDemand2031": 663,
          "nearestParkDistanceM": 533.7,
          "greenRatio": 0.0,
          "playgroundCount": 1,
          "currentStudentCount": 699
        },
        {
          "rank": 2,
          "schoolName": "인천신흥초등학교",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 263,
          "potentialDemand2031": 230,
          "nearestParkDistanceM": 722.2,
          "greenRatio": 0.0,
          "playgroundCount": 1,
          "currentStudentCount": 312
        },
        {
          "rank": 3,
          "schoolName": "인천신선초등학교",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 202,
          "potentialDemand2031": 159,
          "nearestParkDistanceM": 796.8,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 286
        },
        {
          "rank": 4,
          "schoolName": "인천연안초등학교",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 42,
          "potentialDemand2031": 18,
          "nearestParkDistanceM": 620.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 104
        },
        {
          "rank": 5,
          "schoolName": "인천영종초등학교금산분교장",
          "districtName": "중구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 43,
          "potentialDemand2031": 37,
          "nearestParkDistanceM": 1587.3,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 47
        }
      ],
      "bestSchool": {
        "rank": 1,
        "schoolName": "인천하늘초등학교",
        "districtName": "중구",
        "casePolicyLabel": "유지·관리 대상",
        "caseStatusLabel": "접근 양호",
        "potentialDemand2029": 1430,
        "potentialDemand2031": 1567,
        "nearestParkDistanceM": 124.0,
        "greenRatio": 34.3,
        "playgroundCount": 4,
        "currentStudentCount": 1305
      }
    },
    {
      "districtName": "동구",
      "schoolCount": 8,
      "case1Count": 1,
      "case2Count": 4,
      "case3Count": 2,
      "case4Count": 1,
      "specialPolicyCount": 0,
      "priorityReviewCount": 4,
      "totalPotentialDemand2029": 2200,
      "totalPotentialDemand2031": 1903,
      "avgNearestParkDistanceM": 286.3,
      "avgGreenRatio": 1.4,
      "avgPlaygroundCount": 0.25,
      "topPrioritySchools": [
        {
          "rank": 1,
          "schoolName": "인천서림초등학교",
          "districtName": "동구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 303,
          "potentialDemand2031": 229,
          "nearestParkDistanceM": 728.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 488
        },
        {
          "rank": 2,
          "schoolName": "인천동명초등학교",
          "districtName": "동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 408,
          "potentialDemand2031": 403,
          "nearestParkDistanceM": 432.0,
          "greenRatio": 1.7,
          "playgroundCount": 0,
          "currentStudentCount": 438
        },
        {
          "rank": 3,
          "schoolName": "인천송현초등학교",
          "districtName": "동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 151,
          "potentialDemand2031": 75,
          "nearestParkDistanceM": 182.0,
          "greenRatio": 0.2,
          "playgroundCount": 0,
          "currentStudentCount": 347
        },
        {
          "rank": 4,
          "schoolName": "영화초등학교",
          "districtName": "동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 376,
          "potentialDemand2031": 412,
          "nearestParkDistanceM": 305.1,
          "greenRatio": 0.3,
          "playgroundCount": 0,
          "currentStudentCount": 373
        },
        {
          "rank": 5,
          "schoolName": "인천창영초등학교",
          "districtName": "동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 243,
          "potentialDemand2031": 236,
          "nearestParkDistanceM": 43.4,
          "greenRatio": 0.3,
          "playgroundCount": 0,
          "currentStudentCount": 244
        }
      ],
      "topPrioritySchoolsPlaygroundFocused": [
        {
          "rank": 1,
          "schoolName": "인천서림초등학교",
          "districtName": "동구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 303,
          "potentialDemand2031": 229,
          "nearestParkDistanceM": 728.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 488
        },
        {
          "rank": 2,
          "schoolName": "인천창영초등학교",
          "districtName": "동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 243,
          "potentialDemand2031": 236,
          "nearestParkDistanceM": 43.4,
          "greenRatio": 0.3,
          "playgroundCount": 0,
          "currentStudentCount": 244
        },
        {
          "rank": 3,
          "schoolName": "영화초등학교",
          "districtName": "동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 376,
          "potentialDemand2031": 412,
          "nearestParkDistanceM": 305.1,
          "greenRatio": 0.3,
          "playgroundCount": 0,
          "currentStudentCount": 373
        },
        {
          "rank": 4,
          "schoolName": "인천동명초등학교",
          "districtName": "동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 408,
          "potentialDemand2031": 403,
          "nearestParkDistanceM": 432.0,
          "greenRatio": 1.7,
          "playgroundCount": 0,
          "currentStudentCount": 438
        },
        {
          "rank": 5,
          "schoolName": "인천송현초등학교",
          "districtName": "동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 151,
          "potentialDemand2031": 75,
          "nearestParkDistanceM": 182.0,
          "greenRatio": 0.2,
          "playgroundCount": 0,
          "currentStudentCount": 347
        }
      ],
      "topPrioritySchoolsStudentFocused": [
        {
          "rank": 1,
          "schoolName": "인천서림초등학교",
          "districtName": "동구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 303,
          "potentialDemand2031": 229,
          "nearestParkDistanceM": 728.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 488
        },
        {
          "rank": 2,
          "schoolName": "인천동명초등학교",
          "districtName": "동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 408,
          "potentialDemand2031": 403,
          "nearestParkDistanceM": 432.0,
          "greenRatio": 1.7,
          "playgroundCount": 0,
          "currentStudentCount": 438
        },
        {
          "rank": 3,
          "schoolName": "영화초등학교",
          "districtName": "동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 376,
          "potentialDemand2031": 412,
          "nearestParkDistanceM": 305.1,
          "greenRatio": 0.3,
          "playgroundCount": 0,
          "currentStudentCount": 373
        },
        {
          "rank": 4,
          "schoolName": "인천송현초등학교",
          "districtName": "동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 151,
          "potentialDemand2031": 75,
          "nearestParkDistanceM": 182.0,
          "greenRatio": 0.2,
          "playgroundCount": 0,
          "currentStudentCount": 347
        },
        {
          "rank": 5,
          "schoolName": "인천창영초등학교",
          "districtName": "동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 243,
          "potentialDemand2031": 236,
          "nearestParkDistanceM": 43.4,
          "greenRatio": 0.3,
          "playgroundCount": 0,
          "currentStudentCount": 244
        }
      ],
      "bestSchool": {
        "rank": 1,
        "schoolName": "인천만석초등학교",
        "districtName": "동구",
        "casePolicyLabel": "모니터링 대상",
        "caseStatusLabel": "접근 가능, 중간 수준",
        "potentialDemand2029": 103,
        "potentialDemand2031": 43,
        "nearestParkDistanceM": 110.6,
        "greenRatio": 4.4,
        "playgroundCount": 0,
        "currentStudentCount": 263
      }
    },
    {
      "districtName": "미추홀구",
      "schoolCount": 23,
      "case1Count": 1,
      "case2Count": 10,
      "case3Count": 7,
      "case4Count": 5,
      "specialPolicyCount": 0,
      "priorityReviewCount": 10,
      "totalPotentialDemand2029": 13649,
      "totalPotentialDemand2031": 12861,
      "avgNearestParkDistanceM": 234.1,
      "avgGreenRatio": 3.5,
      "avgPlaygroundCount": 0.17,
      "topPrioritySchools": [
        {
          "rank": 1,
          "schoolName": "인천석암초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 940,
          "potentialDemand2031": 938,
          "nearestParkDistanceM": 947.1,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 902
        },
        {
          "rank": 2,
          "schoolName": "인천주안북초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 309,
          "potentialDemand2031": 287,
          "nearestParkDistanceM": 279.4,
          "greenRatio": 0.4,
          "playgroundCount": 0,
          "currentStudentCount": 362
        },
        {
          "rank": 3,
          "schoolName": "인천숭의초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1039,
          "potentialDemand2031": 968,
          "nearestParkDistanceM": 54.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 1154
        },
        {
          "rank": 4,
          "schoolName": "인천용학초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1119,
          "potentialDemand2031": 1100,
          "nearestParkDistanceM": 0.0,
          "greenRatio": 5.7,
          "playgroundCount": 0,
          "currentStudentCount": 1192
        },
        {
          "rank": 5,
          "schoolName": "인천용현남초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1020,
          "potentialDemand2031": 998,
          "nearestParkDistanceM": 497.0,
          "greenRatio": 0.0,
          "playgroundCount": 1,
          "currentStudentCount": 1149
        }
      ],
      "topPrioritySchoolsPlaygroundFocused": [
        {
          "rank": 1,
          "schoolName": "인천석암초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 940,
          "potentialDemand2031": 938,
          "nearestParkDistanceM": 947.1,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 902
        },
        {
          "rank": 2,
          "schoolName": "인천숭의초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1039,
          "potentialDemand2031": 968,
          "nearestParkDistanceM": 54.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 1154
        },
        {
          "rank": 3,
          "schoolName": "인천용현남초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1020,
          "potentialDemand2031": 998,
          "nearestParkDistanceM": 497.0,
          "greenRatio": 0.0,
          "playgroundCount": 1,
          "currentStudentCount": 1149
        },
        {
          "rank": 4,
          "schoolName": "인천주안북초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 309,
          "potentialDemand2031": 287,
          "nearestParkDistanceM": 279.4,
          "greenRatio": 0.4,
          "playgroundCount": 0,
          "currentStudentCount": 362
        },
        {
          "rank": 5,
          "schoolName": "인천용학초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1119,
          "potentialDemand2031": 1100,
          "nearestParkDistanceM": 0.0,
          "greenRatio": 5.7,
          "playgroundCount": 0,
          "currentStudentCount": 1192
        }
      ],
      "topPrioritySchoolsStudentFocused": [
        {
          "rank": 1,
          "schoolName": "인천용학초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1119,
          "potentialDemand2031": 1100,
          "nearestParkDistanceM": 0.0,
          "greenRatio": 5.7,
          "playgroundCount": 0,
          "currentStudentCount": 1192
        },
        {
          "rank": 2,
          "schoolName": "인천숭의초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1039,
          "potentialDemand2031": 968,
          "nearestParkDistanceM": 54.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 1154
        },
        {
          "rank": 3,
          "schoolName": "인천용현남초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1020,
          "potentialDemand2031": 998,
          "nearestParkDistanceM": 497.0,
          "greenRatio": 0.0,
          "playgroundCount": 1,
          "currentStudentCount": 1149
        },
        {
          "rank": 4,
          "schoolName": "인천경원초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 645,
          "potentialDemand2031": 504,
          "nearestParkDistanceM": 73.2,
          "greenRatio": 0.7,
          "playgroundCount": 0,
          "currentStudentCount": 941
        },
        {
          "rank": 5,
          "schoolName": "인천석암초등학교",
          "districtName": "미추홀구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 940,
          "potentialDemand2031": 938,
          "nearestParkDistanceM": 947.1,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 902
        }
      ],
      "bestSchool": {
        "rank": 1,
        "schoolName": "인천연학초등학교",
        "districtName": "미추홀구",
        "casePolicyLabel": "유지·관리 대상",
        "caseStatusLabel": "접근 양호",
        "potentialDemand2029": 438,
        "potentialDemand2031": 442,
        "nearestParkDistanceM": 121.4,
        "greenRatio": 12.8,
        "playgroundCount": 0,
        "currentStudentCount": 371
      }
    },
    {
      "districtName": "옹진군",
      "schoolCount": 10,
      "case1Count": 0,
      "case2Count": 0,
      "case3Count": 0,
      "case4Count": 0,
      "specialPolicyCount": 10,
      "priorityReviewCount": 0,
      "totalPotentialDemand2029": 101,
      "totalPotentialDemand2031": 43,
      "avgNearestParkDistanceM": 16553.3,
      "avgGreenRatio": 0.0,
      "avgPlaygroundCount": 0.0,
      "topPrioritySchools": [],
      "topPrioritySchoolsPlaygroundFocused": [],
      "topPrioritySchoolsStudentFocused": [],
      "bestSchool": {
        "rank": 1,
        "schoolName": "기준 충족 학교 없음",
        "districtName": "옹진군",
        "casePolicyLabel": "기준 미충족",
        "caseStatusLabel": "200m 이내 후보 없음",
        "potentialDemand2029": 0,
        "potentialDemand2031": 0,
        "nearestParkDistanceM": 0,
        "greenRatio": 0,
        "playgroundCount": 0,
        "currentStudentCount": 0
      }
    },
    {
      "districtName": "부평구",
      "schoolCount": 42,
      "case1Count": 4,
      "case2Count": 13,
      "case3Count": 14,
      "case4Count": 11,
      "specialPolicyCount": 0,
      "priorityReviewCount": 13,
      "totalPotentialDemand2029": 17097,
      "totalPotentialDemand2031": 15607,
      "avgNearestParkDistanceM": 313.4,
      "avgGreenRatio": 3.8,
      "avgPlaygroundCount": 0.64,
      "topPrioritySchools": [
        {
          "rank": 1,
          "schoolName": "인천마장초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 393,
          "potentialDemand2031": 335,
          "nearestParkDistanceM": 839.7,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 543
        },
        {
          "rank": 2,
          "schoolName": "인천부원초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 447,
          "potentialDemand2031": 368,
          "nearestParkDistanceM": 752.2,
          "greenRatio": 0.0,
          "playgroundCount": 7,
          "currentStudentCount": 602
        },
        {
          "rank": 3,
          "schoolName": "인천미산초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 142,
          "potentialDemand2031": 102,
          "nearestParkDistanceM": 1143.0,
          "greenRatio": 0.0,
          "playgroundCount": 9,
          "currentStudentCount": 219
        },
        {
          "rank": 4,
          "schoolName": "인천부마초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 520,
          "potentialDemand2031": 461,
          "nearestParkDistanceM": 801.4,
          "greenRatio": 0.0,
          "playgroundCount": 11,
          "currentStudentCount": 654
        },
        {
          "rank": 5,
          "schoolName": "인천금마초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 173,
          "potentialDemand2031": 129,
          "nearestParkDistanceM": 477.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 273
        }
      ],
      "topPrioritySchoolsPlaygroundFocused": [
        {
          "rank": 1,
          "schoolName": "인천마장초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 393,
          "potentialDemand2031": 335,
          "nearestParkDistanceM": 839.7,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 543
        },
        {
          "rank": 2,
          "schoolName": "인천대정초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 228,
          "potentialDemand2031": 119,
          "nearestParkDistanceM": 317.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 471
        },
        {
          "rank": 3,
          "schoolName": "인천산곡초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 504,
          "potentialDemand2031": 504,
          "nearestParkDistanceM": 200.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 427
        },
        {
          "rank": 4,
          "schoolName": "인천산곡남초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 270,
          "potentialDemand2031": 213,
          "nearestParkDistanceM": 343.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 417
        },
        {
          "rank": 5,
          "schoolName": "인천금마초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 173,
          "potentialDemand2031": 129,
          "nearestParkDistanceM": 477.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 273
        }
      ],
      "topPrioritySchoolsStudentFocused": [
        {
          "rank": 1,
          "schoolName": "인천부개서초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1173,
          "potentialDemand2031": 1174,
          "nearestParkDistanceM": 232.0,
          "greenRatio": 2.3,
          "playgroundCount": 0,
          "currentStudentCount": 1054
        },
        {
          "rank": 2,
          "schoolName": "인천부흥초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1003,
          "potentialDemand2031": 992,
          "nearestParkDistanceM": 162.1,
          "greenRatio": 0.6,
          "playgroundCount": 0,
          "currentStudentCount": 1016
        },
        {
          "rank": 3,
          "schoolName": "인천부곡초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 598,
          "potentialDemand2031": 454,
          "nearestParkDistanceM": 420.0,
          "greenRatio": 0.5,
          "playgroundCount": 0,
          "currentStudentCount": 912
        },
        {
          "rank": 4,
          "schoolName": "인천부평동초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 741,
          "potentialDemand2031": 675,
          "nearestParkDistanceM": 409.0,
          "greenRatio": 0.4,
          "playgroundCount": 0,
          "currentStudentCount": 831
        },
        {
          "rank": 5,
          "schoolName": "인천부평남초등학교",
          "districtName": "부평구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 591,
          "potentialDemand2031": 524,
          "nearestParkDistanceM": 399.0,
          "greenRatio": 5.3,
          "playgroundCount": 0,
          "currentStudentCount": 768
        }
      ],
      "bestSchool": {
        "rank": 1,
        "schoolName": "인천후정초등학교",
        "districtName": "부평구",
        "casePolicyLabel": "모니터링 대상",
        "caseStatusLabel": "접근 가능, 중간 수준",
        "potentialDemand2029": 154,
        "potentialDemand2031": 87,
        "nearestParkDistanceM": 65.9,
        "greenRatio": 10.0,
        "playgroundCount": 0,
        "currentStudentCount": 297
      }
    },
    {
      "districtName": "연수구",
      "schoolCount": 34,
      "case1Count": 2,
      "case2Count": 8,
      "case3Count": 6,
      "case4Count": 18,
      "specialPolicyCount": 0,
      "priorityReviewCount": 8,
      "totalPotentialDemand2029": 22651,
      "totalPotentialDemand2031": 21173,
      "avgNearestParkDistanceM": 232.1,
      "avgGreenRatio": 8.6,
      "avgPlaygroundCount": 1.06,
      "topPrioritySchools": [
        {
          "rank": 1,
          "schoolName": "인천은송초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 1606,
          "potentialDemand2031": 1652,
          "nearestParkDistanceM": 1575.0,
          "greenRatio": 0.0,
          "playgroundCount": 6,
          "currentStudentCount": 1502
        },
        {
          "rank": 2,
          "schoolName": "인천송빛초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 654,
          "potentialDemand2031": 584,
          "nearestParkDistanceM": 716.0,
          "greenRatio": 0.0,
          "playgroundCount": 6,
          "currentStudentCount": 762
        },
        {
          "rank": 3,
          "schoolName": "인천연수초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 183,
          "potentialDemand2031": 137,
          "nearestParkDistanceM": 373.0,
          "greenRatio": 0.2,
          "playgroundCount": 0,
          "currentStudentCount": 271
        },
        {
          "rank": 4,
          "schoolName": "인천현송초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1050,
          "potentialDemand2031": 1113,
          "nearestParkDistanceM": 122.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 801
        },
        {
          "rank": 5,
          "schoolName": "인천송도초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 192,
          "potentialDemand2031": 136,
          "nearestParkDistanceM": 224.0,
          "greenRatio": 0.5,
          "playgroundCount": 0,
          "currentStudentCount": 285
        }
      ],
      "topPrioritySchoolsPlaygroundFocused": [
        {
          "rank": 1,
          "schoolName": "인천현송초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1050,
          "potentialDemand2031": 1113,
          "nearestParkDistanceM": 122.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 801
        },
        {
          "rank": 2,
          "schoolName": "인천은송초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 1606,
          "potentialDemand2031": 1652,
          "nearestParkDistanceM": 1575.0,
          "greenRatio": 0.0,
          "playgroundCount": 6,
          "currentStudentCount": 1502
        },
        {
          "rank": 3,
          "schoolName": "인천송빛초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 654,
          "potentialDemand2031": 584,
          "nearestParkDistanceM": 716.0,
          "greenRatio": 0.0,
          "playgroundCount": 6,
          "currentStudentCount": 762
        },
        {
          "rank": 4,
          "schoolName": "인천연수초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 183,
          "potentialDemand2031": 137,
          "nearestParkDistanceM": 373.0,
          "greenRatio": 0.2,
          "playgroundCount": 0,
          "currentStudentCount": 271
        },
        {
          "rank": 5,
          "schoolName": "인천송도초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 192,
          "potentialDemand2031": 136,
          "nearestParkDistanceM": 224.0,
          "greenRatio": 0.5,
          "playgroundCount": 0,
          "currentStudentCount": 285
        }
      ],
      "topPrioritySchoolsStudentFocused": [
        {
          "rank": 1,
          "schoolName": "인천신정초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1480,
          "potentialDemand2031": 1458,
          "nearestParkDistanceM": 270.5,
          "greenRatio": 0.7,
          "playgroundCount": 0,
          "currentStudentCount": 1519
        },
        {
          "rank": 2,
          "schoolName": "인천은송초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 1606,
          "potentialDemand2031": 1652,
          "nearestParkDistanceM": 1575.0,
          "greenRatio": 0.0,
          "playgroundCount": 6,
          "currentStudentCount": 1502
        },
        {
          "rank": 3,
          "schoolName": "인천예송초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1351,
          "potentialDemand2031": 1364,
          "nearestParkDistanceM": 0.0,
          "greenRatio": 1.6,
          "playgroundCount": 0,
          "currentStudentCount": 1185
        },
        {
          "rank": 4,
          "schoolName": "인천연송초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1119,
          "potentialDemand2031": 1223,
          "nearestParkDistanceM": 219.8,
          "greenRatio": 1.0,
          "playgroundCount": 0,
          "currentStudentCount": 1116
        },
        {
          "rank": 5,
          "schoolName": "인천현송초등학교",
          "districtName": "연수구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1050,
          "potentialDemand2031": 1113,
          "nearestParkDistanceM": 122.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 801
        }
      ],
      "bestSchool": {
        "rank": 1,
        "schoolName": "인천신송초등학교",
        "districtName": "연수구",
        "casePolicyLabel": "유지·관리 대상",
        "caseStatusLabel": "접근 양호",
        "potentialDemand2029": 299,
        "potentialDemand2031": 216,
        "nearestParkDistanceM": 0.0,
        "greenRatio": 54.3,
        "playgroundCount": 0,
        "currentStudentCount": 472
      }
    },
    {
      "districtName": "남동구",
      "schoolCount": 39,
      "case1Count": 0,
      "case2Count": 9,
      "case3Count": 16,
      "case4Count": 14,
      "specialPolicyCount": 0,
      "priorityReviewCount": 9,
      "totalPotentialDemand2029": 14134,
      "totalPotentialDemand2031": 10535,
      "avgNearestParkDistanceM": 219.9,
      "avgGreenRatio": 4.4,
      "avgPlaygroundCount": 0.64,
      "topPrioritySchools": [
        {
          "rank": 1,
          "schoolName": "인천상아초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 371,
          "potentialDemand2031": 240,
          "nearestParkDistanceM": 434.0,
          "greenRatio": 0.6,
          "playgroundCount": 0,
          "currentStudentCount": 630
        },
        {
          "rank": 2,
          "schoolName": "인천만수북초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 296,
          "potentialDemand2031": 161,
          "nearestParkDistanceM": 384.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 607
        },
        {
          "rank": 3,
          "schoolName": "인천석천초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 768,
          "potentialDemand2031": 639,
          "nearestParkDistanceM": 180.0,
          "greenRatio": 0.4,
          "playgroundCount": 0,
          "currentStudentCount": 982
        },
        {
          "rank": 4,
          "schoolName": "인천주원초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 170,
          "potentialDemand2031": 133,
          "nearestParkDistanceM": 249.0,
          "greenRatio": 3.3,
          "playgroundCount": 1,
          "currentStudentCount": 242
        },
        {
          "rank": 5,
          "schoolName": "인천정각초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 546,
          "potentialDemand2031": 321,
          "nearestParkDistanceM": 335.8,
          "greenRatio": 0.2,
          "playgroundCount": 0,
          "currentStudentCount": 950
        }
      ],
      "topPrioritySchoolsPlaygroundFocused": [
        {
          "rank": 1,
          "schoolName": "인천만수북초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 296,
          "potentialDemand2031": 161,
          "nearestParkDistanceM": 384.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 607
        },
        {
          "rank": 2,
          "schoolName": "인천석천초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 768,
          "potentialDemand2031": 639,
          "nearestParkDistanceM": 180.0,
          "greenRatio": 0.4,
          "playgroundCount": 0,
          "currentStudentCount": 982
        },
        {
          "rank": 3,
          "schoolName": "인천상아초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 371,
          "potentialDemand2031": 240,
          "nearestParkDistanceM": 434.0,
          "greenRatio": 0.6,
          "playgroundCount": 0,
          "currentStudentCount": 630
        },
        {
          "rank": 4,
          "schoolName": "인천주원초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 170,
          "potentialDemand2031": 133,
          "nearestParkDistanceM": 249.0,
          "greenRatio": 3.3,
          "playgroundCount": 1,
          "currentStudentCount": 242
        },
        {
          "rank": 5,
          "schoolName": "인천정각초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 546,
          "potentialDemand2031": 321,
          "nearestParkDistanceM": 335.8,
          "greenRatio": 0.2,
          "playgroundCount": 0,
          "currentStudentCount": 950
        }
      ],
      "topPrioritySchoolsStudentFocused": [
        {
          "rank": 1,
          "schoolName": "인천석천초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 768,
          "potentialDemand2031": 639,
          "nearestParkDistanceM": 180.0,
          "greenRatio": 0.4,
          "playgroundCount": 0,
          "currentStudentCount": 982
        },
        {
          "rank": 2,
          "schoolName": "인천정각초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 546,
          "potentialDemand2031": 321,
          "nearestParkDistanceM": 335.8,
          "greenRatio": 0.2,
          "playgroundCount": 0,
          "currentStudentCount": 950
        },
        {
          "rank": 3,
          "schoolName": "인천인동초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 448,
          "potentialDemand2031": 303,
          "nearestParkDistanceM": 215.9,
          "greenRatio": 1.0,
          "playgroundCount": 0,
          "currentStudentCount": 771
        },
        {
          "rank": 4,
          "schoolName": "인천상아초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 371,
          "potentialDemand2031": 240,
          "nearestParkDistanceM": 434.0,
          "greenRatio": 0.6,
          "playgroundCount": 0,
          "currentStudentCount": 630
        },
        {
          "rank": 5,
          "schoolName": "인천만수북초등학교",
          "districtName": "남동구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 296,
          "potentialDemand2031": 161,
          "nearestParkDistanceM": 384.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 607
        }
      ],
      "bestSchool": {
        "rank": 1,
        "schoolName": "인천장아초등학교",
        "districtName": "남동구",
        "casePolicyLabel": "유지·관리 대상",
        "caseStatusLabel": "접근 양호",
        "potentialDemand2029": 748,
        "potentialDemand2031": 643,
        "nearestParkDistanceM": 0.0,
        "greenRatio": 17.2,
        "playgroundCount": 0,
        "currentStudentCount": 896
      }
    },
    {
      "districtName": "계양구",
      "schoolCount": 27,
      "case1Count": 0,
      "case2Count": 8,
      "case3Count": 14,
      "case4Count": 5,
      "specialPolicyCount": 0,
      "priorityReviewCount": 8,
      "totalPotentialDemand2029": 6315,
      "totalPotentialDemand2031": 4958,
      "avgNearestParkDistanceM": 266.6,
      "avgGreenRatio": 2.3,
      "avgPlaygroundCount": 0.0,
      "topPrioritySchools": [
        {
          "rank": 1,
          "schoolName": "인천안산초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 161,
          "potentialDemand2031": 149,
          "nearestParkDistanceM": 300.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 265
        },
        {
          "rank": 2,
          "schoolName": "인천효성동초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 420,
          "potentialDemand2031": 469,
          "nearestParkDistanceM": 280.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 454
        },
        {
          "rank": 3,
          "schoolName": "인천화전초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 441,
          "potentialDemand2031": 325,
          "nearestParkDistanceM": 400.0,
          "greenRatio": 0.1,
          "playgroundCount": 0,
          "currentStudentCount": 688
        },
        {
          "rank": 4,
          "schoolName": "인천안남초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 169,
          "potentialDemand2031": 132,
          "nearestParkDistanceM": 496.0,
          "greenRatio": 0.5,
          "playgroundCount": 0,
          "currentStudentCount": 288
        },
        {
          "rank": 5,
          "schoolName": "인천해서초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 31,
          "potentialDemand2031": 15,
          "nearestParkDistanceM": 268.2,
          "greenRatio": 0.5,
          "playgroundCount": 0,
          "currentStudentCount": 141
        }
      ],
      "topPrioritySchoolsPlaygroundFocused": [
        {
          "rank": 1,
          "schoolName": "인천효성동초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 420,
          "potentialDemand2031": 469,
          "nearestParkDistanceM": 280.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 454
        },
        {
          "rank": 2,
          "schoolName": "인천안산초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 161,
          "potentialDemand2031": 149,
          "nearestParkDistanceM": 300.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 265
        },
        {
          "rank": 3,
          "schoolName": "인천화전초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 441,
          "potentialDemand2031": 325,
          "nearestParkDistanceM": 400.0,
          "greenRatio": 0.1,
          "playgroundCount": 0,
          "currentStudentCount": 688
        },
        {
          "rank": 4,
          "schoolName": "인천해서초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 31,
          "potentialDemand2031": 15,
          "nearestParkDistanceM": 268.2,
          "greenRatio": 0.5,
          "playgroundCount": 0,
          "currentStudentCount": 141
        },
        {
          "rank": 5,
          "schoolName": "인천부현초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 206,
          "potentialDemand2031": 159,
          "nearestParkDistanceM": 327.0,
          "greenRatio": 0.6,
          "playgroundCount": 0,
          "currentStudentCount": 342
        }
      ],
      "topPrioritySchoolsStudentFocused": [
        {
          "rank": 1,
          "schoolName": "인천화전초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 441,
          "potentialDemand2031": 325,
          "nearestParkDistanceM": 400.0,
          "greenRatio": 0.1,
          "playgroundCount": 0,
          "currentStudentCount": 688
        },
        {
          "rank": 2,
          "schoolName": "인천효성동초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 420,
          "potentialDemand2031": 469,
          "nearestParkDistanceM": 280.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 454
        },
        {
          "rank": 3,
          "schoolName": "인천부현초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 206,
          "potentialDemand2031": 159,
          "nearestParkDistanceM": 327.0,
          "greenRatio": 0.6,
          "playgroundCount": 0,
          "currentStudentCount": 342
        },
        {
          "rank": 4,
          "schoolName": "인천병방초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 179,
          "potentialDemand2031": 165,
          "nearestParkDistanceM": 291.1,
          "greenRatio": 0.7,
          "playgroundCount": 0,
          "currentStudentCount": 290
        },
        {
          "rank": 5,
          "schoolName": "인천안남초등학교",
          "districtName": "계양구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 169,
          "potentialDemand2031": 132,
          "nearestParkDistanceM": 496.0,
          "greenRatio": 0.5,
          "playgroundCount": 0,
          "currentStudentCount": 288
        }
      ],
      "bestSchool": {
        "rank": 1,
        "schoolName": "인천서운초등학교",
        "districtName": "계양구",
        "casePolicyLabel": "유지·관리 대상",
        "caseStatusLabel": "접근 양호",
        "potentialDemand2029": 513,
        "potentialDemand2031": 507,
        "nearestParkDistanceM": 60.0,
        "greenRatio": 7.2,
        "playgroundCount": 0,
        "currentStudentCount": 510
      }
    },
    {
      "districtName": "서구",
      "schoolCount": 53,
      "case1Count": 3,
      "case2Count": 16,
      "case3Count": 17,
      "case4Count": 17,
      "specialPolicyCount": 0,
      "priorityReviewCount": 16,
      "totalPotentialDemand2029": 33021,
      "totalPotentialDemand2031": 30490,
      "avgNearestParkDistanceM": 235.0,
      "avgGreenRatio": 4.1,
      "avgPlaygroundCount": 0.08,
      "topPrioritySchools": [
        {
          "rank": 1,
          "schoolName": "인천가석초등학교",
          "districtName": "서구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 94,
          "potentialDemand2031": 43,
          "nearestParkDistanceM": 1323.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 209
        },
        {
          "rank": 2,
          "schoolName": "인천가정초등학교",
          "districtName": "서구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 548,
          "potentialDemand2031": 491,
          "nearestParkDistanceM": 663.1,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 664
        },
        {
          "rank": 3,
          "schoolName": "인천봉화초등학교",
          "districtName": "서구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 222,
          "potentialDemand2031": 183,
          "nearestParkDistanceM": 608.2,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 298
        },
        {
          "rank": 4,
          "schoolName": "인천석남서초등학교",
          "districtName": "서구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 193,
          "potentialDemand2031": 148,
          "nearestParkDistanceM": 270.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 321
        },
        {
          "rank": 5,
          "schoolName": "인천목향초등학교",
          "districtName": "서구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 323,
          "potentialDemand2031": 253,
          "nearestParkDistanceM": 235.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 484
        }
      ],
      "topPrioritySchoolsPlaygroundFocused": [
        {
          "rank": 1,
          "schoolName": "인천가정초등학교",
          "districtName": "서구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 548,
          "potentialDemand2031": 491,
          "nearestParkDistanceM": 663.1,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 664
        },
        {
          "rank": 2,
          "schoolName": "인천봉화초등학교",
          "districtName": "서구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 222,
          "potentialDemand2031": 183,
          "nearestParkDistanceM": 608.2,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 298
        },
        {
          "rank": 3,
          "schoolName": "인천가석초등학교",
          "districtName": "서구",
          "casePolicyLabel": "즉시 개선 대상",
          "caseStatusLabel": "공원 접근 결핍",
          "potentialDemand2029": 94,
          "potentialDemand2031": 43,
          "nearestParkDistanceM": 1323.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 209
        },
        {
          "rank": 4,
          "schoolName": "인천가원초등학교",
          "districtName": "서구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1564,
          "potentialDemand2031": 1541,
          "nearestParkDistanceM": 98.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 1558
        },
        {
          "rank": 5,
          "schoolName": "인천경명초등학교",
          "districtName": "서구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 551,
          "potentialDemand2031": 365,
          "nearestParkDistanceM": 96.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 891
        }
      ],
      "topPrioritySchoolsStudentFocused": [
        {
          "rank": 1,
          "schoolName": "인천가현초등학교",
          "districtName": "서구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 2154,
          "potentialDemand2031": 2183,
          "nearestParkDistanceM": 240.0,
          "greenRatio": 0.1,
          "playgroundCount": 1,
          "currentStudentCount": 2044
        },
        {
          "rank": 2,
          "schoolName": "인천이음초등학교",
          "districtName": "서구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1772,
          "potentialDemand2031": 1672,
          "nearestParkDistanceM": 190.0,
          "greenRatio": 0.7,
          "playgroundCount": 0,
          "currentStudentCount": 1934
        },
        {
          "rank": 3,
          "schoolName": "인천가원초등학교",
          "districtName": "서구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1564,
          "potentialDemand2031": 1541,
          "nearestParkDistanceM": 98.0,
          "greenRatio": 0.0,
          "playgroundCount": 0,
          "currentStudentCount": 1558
        },
        {
          "rank": 4,
          "schoolName": "인천봉수초등학교",
          "districtName": "서구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1714,
          "potentialDemand2031": 1797,
          "nearestParkDistanceM": 65.0,
          "greenRatio": 0.0,
          "playgroundCount": 1,
          "currentStudentCount": 1216
        },
        {
          "rank": 5,
          "schoolName": "인천아람초등학교",
          "districtName": "서구",
          "casePolicyLabel": "우선 검토 대상",
          "caseStatusLabel": "접근 가능하나 녹지 부족",
          "potentialDemand2029": 1409,
          "potentialDemand2031": 1403,
          "nearestParkDistanceM": 78.9,
          "greenRatio": 1.9,
          "playgroundCount": 0,
          "currentStudentCount": 907
        }
      ],
      "bestSchool": {
        "rank": 1,
        "schoolName": "인천청라초등학교",
        "districtName": "서구",
        "casePolicyLabel": "유지·관리 대상",
        "caseStatusLabel": "접근 양호",
        "potentialDemand2029": 1105,
        "potentialDemand2031": 1025,
        "nearestParkDistanceM": 146.0,
        "greenRatio": 11.5,
        "playgroundCount": 0,
        "currentStudentCount": 1281
      }
    },
    {
      "districtName": "강화군",
      "schoolCount": 20,
      "case1Count": 0,
      "case2Count": 0,
      "case3Count": 0,
      "case4Count": 0,
      "specialPolicyCount": 20,
      "priorityReviewCount": 0,
      "totalPotentialDemand2029": 1235,
      "totalPotentialDemand2031": 985,
      "avgNearestParkDistanceM": 3705.3,
      "avgGreenRatio": 0.4,
      "avgPlaygroundCount": 0.0,
      "topPrioritySchools": [],
      "topPrioritySchoolsPlaygroundFocused": [],
      "topPrioritySchoolsStudentFocused": [],
      "bestSchool": {
        "rank": 1,
        "schoolName": "합일초등학교",
        "districtName": "강화군",
        "casePolicyLabel": "별도 정책 적용",
        "caseStatusLabel": "별도 묶음",
        "potentialDemand2029": 106,
        "potentialDemand2031": 95,
        "nearestParkDistanceM": 0.0,
        "greenRatio": 3.8,
        "playgroundCount": 0,
        "currentStudentCount": 131
      }
    }
  ],
  "cityTopPrioritySchools": [
    {
      "rank": 1,
      "schoolName": "인천용유초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 26,
      "potentialDemand2031": 25,
      "nearestParkDistanceM": 13471.8,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 33
    },
    {
      "rank": 2,
      "schoolName": "인천영종초등학교금산분교장",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 43,
      "potentialDemand2031": 37,
      "nearestParkDistanceM": 1587.3,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 47
    },
    {
      "rank": 3,
      "schoolName": "인천가석초등학교",
      "districtName": "서구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 94,
      "potentialDemand2031": 43,
      "nearestParkDistanceM": 1323.0,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 209
    },
    {
      "rank": 4,
      "schoolName": "인천석암초등학교",
      "districtName": "미추홀구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 940,
      "potentialDemand2031": 938,
      "nearestParkDistanceM": 947.1,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 902
    },
    {
      "rank": 5,
      "schoolName": "인천마장초등학교",
      "districtName": "부평구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 393,
      "potentialDemand2031": 335,
      "nearestParkDistanceM": 839.7,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 543
    },
    {
      "rank": 6,
      "schoolName": "인천신선초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 202,
      "potentialDemand2031": 159,
      "nearestParkDistanceM": 796.8,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 286
    },
    {
      "rank": 7,
      "schoolName": "인천서림초등학교",
      "districtName": "동구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 303,
      "potentialDemand2031": 229,
      "nearestParkDistanceM": 728.0,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 488
    },
    {
      "rank": 8,
      "schoolName": "인천가정초등학교",
      "districtName": "서구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 548,
      "potentialDemand2031": 491,
      "nearestParkDistanceM": 663.1,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 664
    },
    {
      "rank": 9,
      "schoolName": "인천연안초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 42,
      "potentialDemand2031": 18,
      "nearestParkDistanceM": 620.0,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 104
    },
    {
      "rank": 10,
      "schoolName": "인천봉화초등학교",
      "districtName": "서구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 222,
      "potentialDemand2031": 183,
      "nearestParkDistanceM": 608.2,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 298
    },
    {
      "rank": 11,
      "schoolName": "인천신흥초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 263,
      "potentialDemand2031": 230,
      "nearestParkDistanceM": 722.2,
      "greenRatio": 0.0,
      "playgroundCount": 1,
      "currentStudentCount": 312
    },
    {
      "rank": 12,
      "schoolName": "인천신광초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 673,
      "potentialDemand2031": 663,
      "nearestParkDistanceM": 533.7,
      "greenRatio": 0.0,
      "playgroundCount": 1,
      "currentStudentCount": 699
    },
    {
      "rank": 13,
      "schoolName": "인천은송초등학교",
      "districtName": "연수구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 1606,
      "potentialDemand2031": 1652,
      "nearestParkDistanceM": 1575.0,
      "greenRatio": 0.0,
      "playgroundCount": 6,
      "currentStudentCount": 1502
    },
    {
      "rank": 14,
      "schoolName": "인천송빛초등학교",
      "districtName": "연수구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 654,
      "potentialDemand2031": 584,
      "nearestParkDistanceM": 716.0,
      "greenRatio": 0.0,
      "playgroundCount": 6,
      "currentStudentCount": 762
    },
    {
      "rank": 15,
      "schoolName": "인천부원초등학교",
      "districtName": "부평구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 447,
      "potentialDemand2031": 368,
      "nearestParkDistanceM": 752.2,
      "greenRatio": 0.0,
      "playgroundCount": 7,
      "currentStudentCount": 602
    },
    {
      "rank": 16,
      "schoolName": "인천미산초등학교",
      "districtName": "부평구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 142,
      "potentialDemand2031": 102,
      "nearestParkDistanceM": 1143.0,
      "greenRatio": 0.0,
      "playgroundCount": 9,
      "currentStudentCount": 219
    },
    {
      "rank": 17,
      "schoolName": "인천부마초등학교",
      "districtName": "부평구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 520,
      "potentialDemand2031": 461,
      "nearestParkDistanceM": 801.4,
      "greenRatio": 0.0,
      "playgroundCount": 11,
      "currentStudentCount": 654
    }
  ],
  "cityTopPrioritySchoolsPlaygroundFocused": [
    {
      "rank": 1,
      "schoolName": "인천석암초등학교",
      "districtName": "미추홀구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 940,
      "potentialDemand2031": 938,
      "nearestParkDistanceM": 947.1,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 902
    },
    {
      "rank": 2,
      "schoolName": "인천가정초등학교",
      "districtName": "서구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 548,
      "potentialDemand2031": 491,
      "nearestParkDistanceM": 663.1,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 664
    },
    {
      "rank": 3,
      "schoolName": "인천마장초등학교",
      "districtName": "부평구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 393,
      "potentialDemand2031": 335,
      "nearestParkDistanceM": 839.7,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 543
    },
    {
      "rank": 4,
      "schoolName": "인천서림초등학교",
      "districtName": "동구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 303,
      "potentialDemand2031": 229,
      "nearestParkDistanceM": 728.0,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 488
    },
    {
      "rank": 5,
      "schoolName": "인천봉화초등학교",
      "districtName": "서구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 222,
      "potentialDemand2031": 183,
      "nearestParkDistanceM": 608.2,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 298
    },
    {
      "rank": 6,
      "schoolName": "인천신선초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 202,
      "potentialDemand2031": 159,
      "nearestParkDistanceM": 796.8,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 286
    },
    {
      "rank": 7,
      "schoolName": "인천가석초등학교",
      "districtName": "서구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 94,
      "potentialDemand2031": 43,
      "nearestParkDistanceM": 1323.0,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 209
    },
    {
      "rank": 8,
      "schoolName": "인천연안초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 42,
      "potentialDemand2031": 18,
      "nearestParkDistanceM": 620.0,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 104
    },
    {
      "rank": 9,
      "schoolName": "인천영종초등학교금산분교장",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 43,
      "potentialDemand2031": 37,
      "nearestParkDistanceM": 1587.3,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 47
    },
    {
      "rank": 10,
      "schoolName": "인천용유초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 26,
      "potentialDemand2031": 25,
      "nearestParkDistanceM": 13471.8,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 33
    },
    {
      "rank": 11,
      "schoolName": "인천신광초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 673,
      "potentialDemand2031": 663,
      "nearestParkDistanceM": 533.7,
      "greenRatio": 0.0,
      "playgroundCount": 1,
      "currentStudentCount": 699
    },
    {
      "rank": 12,
      "schoolName": "인천신흥초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 263,
      "potentialDemand2031": 230,
      "nearestParkDistanceM": 722.2,
      "greenRatio": 0.0,
      "playgroundCount": 1,
      "currentStudentCount": 312
    },
    {
      "rank": 13,
      "schoolName": "인천은송초등학교",
      "districtName": "연수구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 1606,
      "potentialDemand2031": 1652,
      "nearestParkDistanceM": 1575.0,
      "greenRatio": 0.0,
      "playgroundCount": 6,
      "currentStudentCount": 1502
    },
    {
      "rank": 14,
      "schoolName": "인천송빛초등학교",
      "districtName": "연수구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 654,
      "potentialDemand2031": 584,
      "nearestParkDistanceM": 716.0,
      "greenRatio": 0.0,
      "playgroundCount": 6,
      "currentStudentCount": 762
    },
    {
      "rank": 15,
      "schoolName": "인천부원초등학교",
      "districtName": "부평구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 447,
      "potentialDemand2031": 368,
      "nearestParkDistanceM": 752.2,
      "greenRatio": 0.0,
      "playgroundCount": 7,
      "currentStudentCount": 602
    },
    {
      "rank": 16,
      "schoolName": "인천미산초등학교",
      "districtName": "부평구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 142,
      "potentialDemand2031": 102,
      "nearestParkDistanceM": 1143.0,
      "greenRatio": 0.0,
      "playgroundCount": 9,
      "currentStudentCount": 219
    },
    {
      "rank": 17,
      "schoolName": "인천부마초등학교",
      "districtName": "부평구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 520,
      "potentialDemand2031": 461,
      "nearestParkDistanceM": 801.4,
      "greenRatio": 0.0,
      "playgroundCount": 11,
      "currentStudentCount": 654
    }
  ],
  "cityTopPrioritySchoolsStudentFocused": [
    {
      "rank": 1,
      "schoolName": "인천은송초등학교",
      "districtName": "연수구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 1606,
      "potentialDemand2031": 1652,
      "nearestParkDistanceM": 1575.0,
      "greenRatio": 0.0,
      "playgroundCount": 6,
      "currentStudentCount": 1502
    },
    {
      "rank": 2,
      "schoolName": "인천석암초등학교",
      "districtName": "미추홀구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 940,
      "potentialDemand2031": 938,
      "nearestParkDistanceM": 947.1,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 902
    },
    {
      "rank": 3,
      "schoolName": "인천송빛초등학교",
      "districtName": "연수구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 654,
      "potentialDemand2031": 584,
      "nearestParkDistanceM": 716.0,
      "greenRatio": 0.0,
      "playgroundCount": 6,
      "currentStudentCount": 762
    },
    {
      "rank": 4,
      "schoolName": "인천신광초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 673,
      "potentialDemand2031": 663,
      "nearestParkDistanceM": 533.7,
      "greenRatio": 0.0,
      "playgroundCount": 1,
      "currentStudentCount": 699
    },
    {
      "rank": 5,
      "schoolName": "인천가정초등학교",
      "districtName": "서구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 548,
      "potentialDemand2031": 491,
      "nearestParkDistanceM": 663.1,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 664
    },
    {
      "rank": 6,
      "schoolName": "인천부마초등학교",
      "districtName": "부평구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 520,
      "potentialDemand2031": 461,
      "nearestParkDistanceM": 801.4,
      "greenRatio": 0.0,
      "playgroundCount": 11,
      "currentStudentCount": 654
    },
    {
      "rank": 7,
      "schoolName": "인천부원초등학교",
      "districtName": "부평구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 447,
      "potentialDemand2031": 368,
      "nearestParkDistanceM": 752.2,
      "greenRatio": 0.0,
      "playgroundCount": 7,
      "currentStudentCount": 602
    },
    {
      "rank": 8,
      "schoolName": "인천마장초등학교",
      "districtName": "부평구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 393,
      "potentialDemand2031": 335,
      "nearestParkDistanceM": 839.7,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 543
    },
    {
      "rank": 9,
      "schoolName": "인천서림초등학교",
      "districtName": "동구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 303,
      "potentialDemand2031": 229,
      "nearestParkDistanceM": 728.0,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 488
    },
    {
      "rank": 10,
      "schoolName": "인천신흥초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 263,
      "potentialDemand2031": 230,
      "nearestParkDistanceM": 722.2,
      "greenRatio": 0.0,
      "playgroundCount": 1,
      "currentStudentCount": 312
    },
    {
      "rank": 11,
      "schoolName": "인천봉화초등학교",
      "districtName": "서구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 222,
      "potentialDemand2031": 183,
      "nearestParkDistanceM": 608.2,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 298
    },
    {
      "rank": 12,
      "schoolName": "인천신선초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 202,
      "potentialDemand2031": 159,
      "nearestParkDistanceM": 796.8,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 286
    },
    {
      "rank": 13,
      "schoolName": "인천미산초등학교",
      "districtName": "부평구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 142,
      "potentialDemand2031": 102,
      "nearestParkDistanceM": 1143.0,
      "greenRatio": 0.0,
      "playgroundCount": 9,
      "currentStudentCount": 219
    },
    {
      "rank": 14,
      "schoolName": "인천가석초등학교",
      "districtName": "서구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 94,
      "potentialDemand2031": 43,
      "nearestParkDistanceM": 1323.0,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 209
    },
    {
      "rank": 15,
      "schoolName": "인천연안초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 42,
      "potentialDemand2031": 18,
      "nearestParkDistanceM": 620.0,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 104
    },
    {
      "rank": 16,
      "schoolName": "인천영종초등학교금산분교장",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 43,
      "potentialDemand2031": 37,
      "nearestParkDistanceM": 1587.3,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 47
    },
    {
      "rank": 17,
      "schoolName": "인천용유초등학교",
      "districtName": "중구",
      "casePolicyLabel": "즉시 개선 대상",
      "caseStatusLabel": "공원 접근 결핍",
      "potentialDemand2029": 26,
      "potentialDemand2031": 25,
      "nearestParkDistanceM": 13471.8,
      "greenRatio": 0.0,
      "playgroundCount": 0,
      "currentStudentCount": 33
    }
  ],
  "cityBestSchool": {
    "rank": 1,
    "schoolName": "인천신송초등학교",
    "districtName": "연수구",
    "casePolicyLabel": "유지·관리 대상",
    "caseStatusLabel": "접근 양호",
    "potentialDemand2029": 299,
    "potentialDemand2031": 216,
    "nearestParkDistanceM": 0.0,
    "greenRatio": 54.3,
    "playgroundCount": 0,
    "currentStudentCount": 472
  }
};
