const assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require('jsdom');
const dom=new JSDOM('<section id="host"></section>',{runScripts:'outside-only',url:'http://localhost'}),w=dom.window;
w.eval(fs.readFileSync('assets/school-photos.js','utf8'));
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
const school={name:'검증학교',gu:'중구',lat:37.5,lng:126.7},host=w.document.getElementById('host');
assert.deepEqual(Array.from(w.SchoolPhotos.nearby({lat:null,lng:null},[{lat:37,lng:126}])),[]);
assert.equal(w.SchoolPhotos.nearby(school,[{name:'근처',lat:37.5001,lng:126.7},{name:'멀리',lat:38,lng:127},{lat:null,lng:null}]).length,1);
let configCalls=0,enabled=false;
w.google={maps:{importLibrary:()=>Promise.resolve()}};
w.fetch=async url=>url.includes('google-places')?(configCalls++,{ok:true,json:async()=>({enabled})}):{ok:true,json:async()=>url.includes('parks')?[{name:'주변공원',lat:37.5001,lng:126.7}]:[]};
function loaded(widget,places){widget.places=places;widget.dispatchEvent(new w.Event('gmp-load'));}
(async()=>{
 w.SchoolPhotos.mount(host,school);assert.equal(configCalls,1,'selected school starts loading without a click');
 assert(host.querySelector('button').disabled);await tick();await tick();
 assert.match(host.textContent,/아직 연결되지/);assert.equal(host.querySelector('button').disabled,false);
 assert.equal(host.querySelector('.photo-results').children.length,0);
 enabled=true;w.SchoolPhotos.mount(host,school);await tick();await tick();
 let widget=host.querySelector('gmp-place-search');assert(widget,'school candidates mount automatically');
 assert.match(widget.querySelector('gmp-place-text-search-request').textQuery,/검증학교/);
 loaded(widget,[{id:'a'},{id:'b'}]);assert.match(host.querySelector('.photo-status').textContent,/여러 장소 후보/);
 assert.equal(host.querySelector('.photo-detail'),null,'ambiguous candidates never auto-selected');assert.equal(host.querySelectorAll('.photo-preview').length,2,'each candidate has an explicitly labeled automatic preview');
 assert.equal(host.querySelector('button').disabled,false);
 const firstPreview=host.querySelector('.photo-preview');loaded(widget,[{id:'a'},{id:'b'}]);assert.equal(host.querySelector('.photo-preview'),firstPreview,'repeated load reuses previews');
 const select=host.querySelector('select');assert.equal(select.options.length,2);
 select.value='1';select.dispatchEvent(new w.Event('change'));await tick();
 assert.equal(host.querySelector('gmp-place-search'),null,'facility selection alone makes no photo search');
 const facility=host.querySelector('button').onclick();await facility;
 let parkWidget=host.querySelector('gmp-place-search');assert.match(parkWidget.querySelector('gmp-place-text-search-request').textQuery,/주변공원/);
 loaded(parkWidget,[]);assert.match(host.querySelector('.photo-status').textContent,/미확보는 시설 부족/);
 select.value='0';select.dispatchEvent(new w.Event('change'));await tick();
 widget=host.querySelector('gmp-place-search');assert(widget,'returning to school loads automatically');
 loaded(widget,[{id:'school'}]);
 const event=new w.Event('gmp-select');event.place={id:'school'};widget.dispatchEvent(event);
 assert(host.querySelector('gmp-place-details'),'explicit candidate selection opens detail');
 // Reusing the same connected host must isolate older async responses and widget events.
 w.SchoolPhotos.mount(host,{...school,name:'새학교'});await tick();
 const newWidget=host.querySelector('gmp-place-search');assert.match(newWidget.querySelector('gmp-place-text-search-request').textQuery,/새학교/);
 loaded(widget,[]);widget.dispatchEvent(event);assert.equal(host.querySelector('.photo-detail'),null);
 assert.match(host.querySelector('.photo-status').textContent,/새학교/,'stale events do not change current status');
 loaded(newWidget,[{id:'new'}]);
 w.SchoolPhotos.mount(host,{name:'<img src=x onerror=alert(1)>'});await tick();
 assert.equal(host.querySelector('img'),null);assert.match(host.textContent,/좌표가 없어/);
 loaded(host.querySelector('gmp-place-search'),[]);
 // Delayed facility data for the old mount cannot populate a newer school's choices.
 const oldResolvers=[];w.fetch=async()=>new Promise(r=>{oldResolvers.push(r);});
 w.SchoolPhotos.mount(host,school);await tick();const stale=host.querySelector('gmp-place-search');
 w.SchoolPhotos.mount(host,{name:'좌표없는학교'});await tick();
 assert.equal(oldResolvers.length,2);oldResolvers.forEach(resolve=>resolve({ok:true,json:async()=>[{name:'이전학교시설',lat:37.5001,lng:126.7}]}));await tick();await tick();assert.equal(host.querySelectorAll('option').length,1);
 loaded(stale,[]);loaded(host.querySelector('gmp-place-search'),[]);
 assert.equal(configCalls,2,'successful SDK initialization is reused');
 console.log('PASS school photos: automatic school, manual facilities, ambiguous candidates, explicit details, stale events, SDK reuse, missing config and escaping');
 w.close();
})().catch(e=>{w.close();console.error(e);process.exitCode=1;});
