import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'refresh-pipeline-'));
process.env.UPDATE_CENTER_APPLY_ROOT=root;process.env.UPDATE_CENTER_HOME=path.join(root,'runtime');
process.env.UPDATE_CENTER_STORE_PATH=path.join(root,'store.json');delete process.env.DATABASE_URL;
const {createStore}=await import('../scripts/update_center/store.mjs');
const {checkPipeline,validatePipelineFile}=await import('../scripts/update_center/pipeline.mjs');
const {restoreActiveVersions}=await import('../scripts/update_center/restore.mjs');
const {rollbackVersionDir}=await import('../scripts/update_center/apply.mjs');
const store=await createStore();const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const target='data_processed/education/analysis_dataset.json';
const original={years:[2026],schools:[{id:'s1',environment:{library:0},observations:{2026:{students:12}}}]};
const updated=structuredClone(original);updated.schools[0].environment.library=2;
function write(base,name,value){const file=path.join(base,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(value));}
write(root,target,original);write(path.join(root,'vercel_public'),target,original);
const entry={dataset:'libraries',auto_apply:true,local_file:'data_processed/libraries.csv',check:{type:'refresh_pipeline',pipeline:'libraries'}};
const collect=async(_,input)=>{
  write(input.work,target,updated);const bytes=fs.readFileSync(path.join(input.work,target));
  return {files:[{target,sha256:hash(bytes)}],input_hashes:{[target]:hash(fs.readFileSync(path.join(root,target)))},result:{changed:true}};
};
const state={};let result=await checkPipeline(entry,state,store,{collect});
assert.equal(result.event.status,'applied');assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,target))),updated);
assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,'vercel_public',target))),updated);
const versions=await store.listVersions();assert.equal(versions.length,1);
const db=JSON.parse(fs.readFileSync(path.join(root,'store.json')));
assert.ok(db.version_files[versions[0].id].every(f=>f.blob_sha256&&!f.content),'compressed deduplicated blobs');
write(root,target,original);await restoreActiveVersions({store});assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,target))),updated);
await rollbackVersionDir({versionName:versions[0].version_dir,entry,store,versionId:versions[0].id,actor:'test'});
assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,target))),original);
const failedStore={...store,putVersionFiles:async()=>{throw Error('injected disk failure');}};
result=await checkPipeline(entry,state,failedStore,{collect});assert.equal(result.outcome,'error');
assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,target))),original,'persistence failure cannot publish');
result=await checkPipeline(entry,state,store,{collect:async()=>{throw Error('upstream unavailable');}});
assert.equal(result.outcome,'error');assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,target))),original);
result=await checkPipeline(entry,state,store,{collect:async(...args)=>{const r=await collect(...args);r.input_hashes[target]='0'.repeat(64);return r;}});
assert.equal(result.outcome,'error');assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,target))),original,'stale build rejected');
assert.throws(()=>validatePipelineFile(Buffer.from('{}'),'../outside.json',path.join(root,target)),/Unregistered/);
assert.throws(()=>validatePipelineFile(Buffer.from('{"schools":[]}'),target,path.join(root,target)),/keys missing|identity/);
console.log('refresh pipeline: publish, analysis/static consistency, compressed persistence, restart restore, rollback, failed persistence, network failure, stale input and path guards PASS');
