const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');
const dom=new JSDOM('<section id="networks"></section>',{runScripts:'outside-only'}),w=dom.window;
w.fetch=async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(root,url.replace('./','')),'utf8'))});
w.eval(fs.readFileSync(path.join(root,'assets/education-networks.js'),'utf8'));
(async()=>{
 const container=w.document.getElementById('networks');
 await w.EducationNetworks.mount(container,'유치원','전체');
 const el=k=>container.querySelector(`[data-network="${k}"]`);
 assert.equal(el('level').value,'유치원');
 assert.equal(el('parks-result').querySelectorAll('tbody tr').length,369);
 assert.match(el('diffusion-result').textContent,/375\.3/);
 el('radius').value='1000';el('radius').dispatchEvent(new w.Event('change'));
 assert.match(el('diffusion-result').textContent,/96\.5/);
 el('level').value='중학교';el('gu').value='강화군';el('gu').dispatchEvent(new w.Event('change'));
 const data=JSON.parse(fs.readFileSync(path.join(root,'data_processed/education/shared_parks.json'),'utf8'));
 assert.equal(el('parks-result').querySelectorAll('tbody tr').length,data.schools.filter(s=>s.level==='중학교'&&s.gu==='강화군').length);
 assert(!/NaN|undefined/.test(container.textContent));
 assert.match(container.textContent,/실제 전망이 아닙니다/);
 const curriculum=container.querySelector('#educationCurriculumNetwork');
 const probability=curriculum.querySelector('[data-curriculum="probability"]');
 assert.match(curriculum.textContent,/77\.83곳/);
 probability.value='0.05';probability.dispatchEvent(new w.Event('change'));
 assert(!curriculum.querySelector('[data-curriculum="comparison"]').textContent.includes('77.83곳'));
 const school=curriculum.querySelector('[data-curriculum="school"]');
 school.value='B000012240';school.dispatchEvent(new w.Event('change'));
 assert.match(curriculum.querySelector('[data-curriculum="school-result"]').textContent,/인하대학교사범대학부속고등학교/);
 assert.match(curriculum.querySelector('[data-curriculum="school-result"]').textContent,/학익고등학교/);
 const field=container.querySelector('#educationFieldVerification');
 assert.match(field.textContent,/함봉공원/);
 assert.equal(field.querySelector('[data-field="result"]').querySelectorAll('tbody tr').length,4);
 const park=field.querySelector('select');park.selectedIndex=1;park.dispatchEvent(new w.Event('change'));
 assert.equal(field.querySelector('[data-field="result"]').querySelectorAll('tbody tr').length,6);
 const road=container.querySelector('#educationRoadResilience');
 const roadLevel=road.querySelector('select');roadLevel.value='고등학교';roadLevel.dispatchEvent(new w.Event('change'));
 assert.match(road.textContent,/대상 129곳/);
 assert(!/NaN|undefined/.test(container.textContent));
 const insights=w.document.createElement('section');w.document.body.appendChild(insights);
 await w.EducationNetworks.mountInsights(insights,'중학교','강화군');
 assert.equal(insights.querySelectorAll('.edu-insight-card').length,5);
 assert.match(insights.querySelector('.edu-insight-grid').textContent,/498곳 중 247곳/);
 assert.match(insights.querySelector('.edu-insight-grid').textContent,/240곳/);
 assert.match(insights.querySelector('.edu-insight-grid').textContent,/43개 중 21개/);
 assert.match(insights.querySelector('.edu-insight-grid').textContent,/0.257/);
 for(const link of insights.querySelectorAll('.edu-insight-card a[href^="#"]')) assert(insights.querySelector(link.getAttribute('href')));
 assert.equal(insights.querySelector('[data-network="level"]').value,'중학교');
 assert.equal(insights.querySelector('[data-network="gu"]').value,'강화군');
 assert(!/NaN|undefined/.test(insights.textContent));
 console.log('Education network controls, real data, missing-value display passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
