const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {JSDOM} = require('jsdom');
const root = path.resolve(__dirname,'..');
const read = name => JSON.parse(fs.readFileSync(path.join(root,'data_processed/education',name),'utf8'));
const dom = new JSDOM('<select id="schoolLevelFilter" disabled><option value="초등학교">초등학교</option><option value="중학교">중학교</option><option value="all">전체</option></select><button id="educationReportButton"></button>',{runScripts:'outside-only',url:'http://localhost/'});
const w=dom.window;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;};
const baselines=fs.readFileSync(path.join(root,'data_processed/schools.csv'),'utf8').trim().split(/\r?\n/).slice(1).map(line=>{const c=line.split(',');return {학교ID:c[0],학교명:c[1]};});
w.state={datasets:{schools:baselines,isochrone:{features:[]}},overlays:{},selectedSchoolId:null};
w.state.map={panTo(point){this.point=point;},setLevel(level){this.level=level;}};
w.kakao={maps:{LatLng:class {constructor(lat,lng){this.lat=lat;this.lng=lng;}},Polygon:class {constructor(options){this.options=options;}setMap(map){this.map=map;}}}};
w.ui={schoolSearchInput:{value:''}};
w.getSchoolId=r=>r.학교ID;
for(const name of ['clearDetailPanelSelection','populateSchoolSearchOptions','rerenderAll','renderGuSummary','appendStatus']) w[name]=()=>{};
w.findSchoolBySearch=()=>null;
w.isLayerOnById=()=>false;
const fetched=[];
w.fetch=async url=>{fetched.push(url);const name=decodeURIComponent(url.replace('./data_processed/education/',''));return {ok:true,json:async()=>read(name)};};
w.eval(fs.readFileSync(path.join(root,'assets/education-layers.js'),'utf8'));
(async()=>{
  await w.EducationLayers.init();
  const selector=w.document.getElementById('schoolLevelFilter');
  assert.equal(selector.disabled,false);
  assert.equal(w.state.datasets.schools.length,272);
  selector.value='중학교';selector.dispatchEvent(new w.Event('change'));
  assert.equal(w.state.datasets.schools.length,146);
  const row=w.state.datasets.schools.find(r=>r.case_type===1 && r.similar_schools.length);
  await w.EducationLayers.openReport(row);
  const body=w.document.querySelector('.edu-body');
  assert.match(body.textContent,/유사학교 비교/);
  assert.match(body.textContent,/학교 내부 독서 공급/);
  assert.match(body.textContent,/학교별 공개 공시/);
  assert.match(body.textContent,/학교 주변 해당 연령 거주인구/);
  const schoolAge=read('school_age_demand.json').schools[row.학교ID].straight_500m.levels[row.학교급구분];
  assert(schoolAge.estimated_residents!==null);
  assert(body.textContent.includes(schoolAge.estimated_residents.toLocaleString('ko-KR',{maximumFractionDigits:1})+'명'));
  assert.match(body.textContent,/학교별 공개 활동·지원·체력 지표/);
  assert.match(body.textContent,/4·5등급 비율/);
  const indicator=read('school_public_indicators.json').schools[row.학교ID].find(g=>g.item==='90').observations.at(-1).metrics.at(-1);
  assert(body.textContent.includes(indicator.value.toLocaleString('ko-KR',{maximumFractionDigits:1})+'%'));
  assert.match(body.textContent,/무이동 코호트 시나리오/);
  assert.match(body.textContent,/후보지 내부 추정 인구/);
  assert.match(body.textContent,/파레토/);
  assert.match(body.querySelector('#edu-candidates').textContent,/66조합 상위5/);
  assert.equal(body.querySelector('#edu-candidates tbody').children.length,row.candidates.length);
  const distanceWeight=body.querySelector('#edu-distance-weight');
  distanceWeight.value='90';distanceWeight.dispatchEvent(new w.Event('input'));
  assert.equal(body.querySelector('#edu-age-weight').value,'10');
  assert.match(body.querySelector('#edu-gap-weight').textContent,/공원 부족 가중치 0%/);
  const candidateDemand=read('candidate_age_demand.json');
  const candidate=row.candidates.find(c=>candidateDemand.candidates[c.grid_id]?.straight_500m.levels['중학교'].estimated_residents!=null);
  assert(candidate);
  const count=candidateDemand.candidates[candidate.grid_id].straight_500m.levels['중학교'].estimated_residents;
  assert(body.querySelector('#edu-candidates').textContent.includes(count.toLocaleString('ko-KR',{maximumFractionDigits:1})+'명'));
  assert.match(body.textContent,/지역 미래 수요 지원 예측/);
  const demandYear=w.document.getElementById('edu-demand-year');
  demandYear.value='2029';demandYear.dispatchEvent(new w.Event('change'));
  assert.match(body.querySelector('#edu-candidates').textContent,/2029년 지역비례 시나리오/);
  const futureContext=read('regional_age_forecasts.json')[`${row.gu}|중학교`];
  const actualContext=read('regional_demography.json')[`${row.gu}|중학교`];
  const expected=count*futureContext.forecast.find(r=>r.year===2029).residents/actualContext.history.find(r=>r.year===2024).residents;
  assert(body.querySelector('#edu-candidates').textContent.includes(expected.toLocaleString('ko-KR',{maximumFractionDigits:1})+'명'));
  const selectedGrid=body.querySelector('#edu-map-candidate').value;
  await body.querySelector('#edu-show-candidate').onclick();
  const overlay=w.state.overlays.educationCandidate[0];
  assert.equal(overlay.map,w.state.map);
  assert.equal(overlay.options.path.length,5);
  assert.equal(w.state.map.level,4);
  assert.equal(w.state.map.point.lat,row.candidates.find(c=>c.grid_id===selectedGrid).lat);
  assert.equal(w.document.querySelector('dialog').open,false);
  const policy=w.document.getElementById('edu-policy-action');
  assert.match(policy.textContent,/신규 공급/);
  const site=w.document.getElementById('edu-site');site.value='unavailable';site.dispatchEvent(new w.Event('change'));
  assert.match(policy.textContent,/공동활용/);
  assert(fetched.some(u=>u.includes(`disclosures/${row.학교ID}.json`)));
  assert(!fetched.some(u=>u.endsWith('school_disclosures.json')));
  await w.EducationLayers.openReport({...row,학교명:'<img src=x onerror=alert(1)>'});
  assert.equal(body.querySelector('img'),null);
  assert.match(body.textContent,/<img src=x/);
  selector.value='all';selector.dispatchEvent(new w.Event('change'));
  assert.equal(overlay.map,null);
  assert.equal(w.state.datasets.schools.length,916);
  const awards=read('science_awards.json');
  const awarded=w.state.datasets.schools.find(r=>awards.schools[r.학교ID]?.length);
  assert(awarded);
  await w.EducationLayers.openReport(awarded);
  assert(body.textContent.includes(awards.schools[awarded.학교ID][0].work_title));
  const invention=read('invention_awards.json');
  const inventor=w.state.datasets.schools.find(r=>invention.schools[r.학교ID]?.length);
  assert(inventor);
  await w.EducationLayers.openReport(inventor);
  assert(body.textContent.includes(invention.schools[inventor.학교ID][0].work_title));
  assert.match(body.textContent,/전국학생과학발명품경진대회/);
  await w.EducationLayers.openReport(awarded);
  let aiSelection,aiQuestion;
  w.setSchoolPanelSelection=r=>{aiSelection=r;};
  w.askAiExplainer=q=>{aiQuestion=q;};
  w.document.getElementById('edu-ai-explain').click();
  assert.equal(aiSelection.학교ID,awarded.학교ID);
  assert.match(aiQuestion,/현재 공원 환경/);
  assert.equal(w.document.querySelector('dialog').open,false);
  w.state.selectedGu='전체';
  w.EducationLayers.openStatistics();
  assert.match(body.textContent,/학교급별 분석 현황/);
  const coverageLink=body.querySelector('a[download]');
  assert.equal(coverageLink.getAttribute('href'),'./data_processed/education/school_data_coverage.csv');
  assert(fs.existsSync(path.join(root,coverageLink.getAttribute('href'))));
  assert.match(body.textContent,/369/);
  assert.match(body.textContent,/146/);
  console.log('Education UI integration passed: school filters, lazy disclosures, policy scenarios, escaped source text.');
})().catch(e=>{console.error(e);process.exitCode=1;});
