'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..'),dom=new JSDOM('<main id="evidence-panel"></main>',{runScripts:'outside-only'}),w=dom.window;
for(const file of ['table-comparison.js','chat-workspace.js'])w.eval(fs.readFileSync(path.join(root,'assets',file),'utf8'));
const table={headers:['학교','학생당 장서','공공도서관 거리'],rows:[['학교 A',null,1200],['학교 B',0,300]]};
const section={title:'도서관 지원 검토 관측',table,notes:['직선거리는 검증된 보행 접근성이 아닙니다.']};
w.ChatWorkspace.show({observation_version:1,visual:{sections:[section,section,{...section,title:'반복 조회'}],table}},'도서관 지원 검토');
const d=w.document;
assert.equal(d.querySelectorAll('.table-comparison').length,1,'same table from repeated calls/top-level renders once');
assert.equal(d.querySelectorAll('.tc-values').length,1);
assert([...d.querySelectorAll('.comparison-section')].every(e=>!e.open),'variable detail sections are collapsed');
assert.equal(d.querySelector('.tc-values').open,false);
assert.match(d.querySelector('.tc-table').textContent,/자료 없음/);
assert.match(d.querySelector('.tc-table').textContent,/학교 B0/);
assert.match(d.body.textContent,/직선거리는 검증된 보행 접근성/);
const legacy=w.ChatWorkspace.safeResult({weights:[{}],visual:{table}});
assert.equal(legacy.answerable,false);assert.match(legacy.summary,/이전 방식/);
console.log('PASS deduplicated evidence, collapsed details, missing vs zero, route caveat, persisted legacy gate');
dom.window.close();
