const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const stats=require('../assets/education-statistics.js');
const rows=(x,y)=>x.map((v,i)=>({values:{x:v,y:y[i]}}));
assert.equal(stats.analyze(rows([1,2,3],[2,4,6]),'x','y').pearson,1);
assert.equal(stats.analyze(rows([1,2,3],[6,4,2]),'x','y').pearson,-1);
assert.equal(stats.analyze(rows([1,1,1],[2,3,4]),'x','y').pearson,null);
assert.equal(stats.analyze(rows([1,2],[2,3]),'x','y').spearman,null);
assert.deepEqual(stats.ranks([1,2,2,4]),[1,2.5,2.5,4]);
assert(Math.abs(stats.analyze(rows([1,2,2,4],[4,1,1,3]),'x','y').spearman+1/3)<1e-12);
const missing=stats.analyze(rows([0,1,2,null,'',false,' '],[0,1,2,3,4,5,6]),'x','y');
assert.equal(missing.n,3);assert.equal(missing.excluded,4);assert.equal(missing.pearson,1);
const dom=new JSDOM('<section id="stats"></section>',{runScripts:'outside-only'}),w=dom.window;
const schools=[1,2,3,4].map(i=>({id:String(i),name:`학교 ${i}`,level:'중학교',gu:i===4?'B':'A',environment:{academy:i}}));
schools.push({id:'kg',name:'유치원',level:'유치원',gu:'A',environment:{academy:20}});
const data={years:[2025,2026],schools:Object.fromEntries(schools.map((s,i)=>[s.id,{'2026':{students:(i+1)*10,sources:[]},'2025':{students:1,sources:[]}}]))};
w.fetch=async()=>({ok:true,json:async()=>data});
w.eval(fs.readFileSync(path.resolve(__dirname,'../assets/education-statistics.js'),'utf8'));
(async()=>{
 const container=w.document.getElementById('stats');
 await w.EducationStatistics.mount(container,schools,'中学校','전체');
 const select=k=>container.querySelector(`[data-filter="${k}"]`);
 select('level').value='중학교';select('level').dispatchEvent(new w.Event('change'));
 assert(container.querySelector('.edu-stat-result').textContent.includes('4 / 4'));
 assert.equal(container.querySelectorAll('circle').length,4);
 select('gu').value='A';select('gu').dispatchEvent(new w.Event('change'));
 assert(container.querySelector('.edu-stat-result').textContent.includes('3 / 3'));
 assert.equal(container.querySelectorAll('circle').length,3);
 select('year').value='2025';select('year').dispatchEvent(new w.Event('change'));
 assert(container.querySelector('.edu-stat-result').textContent.includes('산출 불가'));
 container.querySelector('[data-x="classes"][data-y="students"]').click();
 assert.equal(select('x').value,'classes');assert.equal(select('y').value,'students');
 assert(container.querySelector('.edu-stat-result').textContent.includes('0 / 3'));
 select('level').value='유치원';select('level').dispatchEvent(new w.Event('change'));
 assert([...select('x').options].some(o=>o.value==='kg_teachers'));
 assert(![...select('x').options].some(o=>o.value==='teachers'));
 assert(container.querySelector('.edu-stat-result').textContent.includes('1 / 1'));
 console.log('Correlation math and UI: tie ranks, pairwise missingness, zero, constant/small samples, level/district/year filters and matrix selection passed.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>w.close());
