import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'zones-test-'));
process.env.UPDATE_CENTER_APPLY_ROOT=root;process.env.UPDATE_CENTER_HOME=path.join(root,'runtime');process.env.UPDATE_CENTER_STORE_PATH=path.join(root,'store.json');delete process.env.DATABASE_URL;
const {createStore}=await import('../scripts/update_center/store.mjs');
const {checkSchoolZones}=await import('../scripts/update_center/school_zones.mjs');
const {autoApplyEvents}=await import('../scripts/update_center/automatic.mjs');
const {evaluateCandidate}=await import('../scripts/update_center/candidate.mjs');
const real=JSON.parse(fs.readFileSync(new URL('../data_processed/education/school_zones.geojson',import.meta.url),'utf8'));
const entry={dataset:'school_zones',local_file:'data_processed/education/school_zones.geojson',auto_apply:true};
const dest=path.join(root,entry.local_file);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,JSON.stringify(real));
const store=await createStore(),state={};
assert.equal((await evaluateCandidate(entry,JSON.stringify(real),'school_zones.geojson')).approval_blocked,false);
assert.equal((await checkSchoolZones(entry,state,store,{collect:async()=>real})).outcome,'unchanged');
const changed=structuredClone(real);changed.features[0].properties.name+=' 검증';
const next=await checkSchoolZones(entry,state,store,{collect:async()=>changed});assert.equal(next.outcome,'green');
const applied=await autoApplyEvents([next.event],[entry],store);assert.equal(applied[0].ok,true);assert.equal(JSON.parse(fs.readFileSync(dest)).features[0].properties.name,changed.features[0].properties.name);
const failed=await checkSchoolZones(entry,state,store,{collect:async()=>{throw Error('network down');}});assert.equal(failed.outcome,'error');assert.equal(JSON.parse(fs.readFileSync(dest)).features.length,311);
const reduced=structuredClone(changed);reduced.features=reduced.features.slice(0,100);assert.equal((await checkSchoolZones(entry,state,store,{collect:async()=>reduced})).outcome,'yellow');
let calls=0;const blocked={...next.event,status:'pending',risk:'yellow'};assert.deepEqual(await autoApplyEvents([blocked],[entry],store,{apply:async()=>{calls++;}}),[]);assert.equal(calls,0);
assert.equal((await autoApplyEvents([{...next.event,status:'pending'}],[{...entry,never_auto_apply:true}],store)).length,0);
assert.equal(real.features.length,311);assert.equal(real.metadata.kindergarten.status,'not_published');
console.log('school zones: official data, unchanged, staged/auto apply, failure preservation, review gates PASS');
