'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
process.env.UPDATE_CENTER_STORE_PATH=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'policy-studio-test-')),'store.json');delete process.env.DATABASE_URL;
process.env.AI_EXPLAINER_ENABLED='false';
const p=require('../api/_policy_studio'),hitl=require('../api/_hitl_analysis');
const base={version:1,resource:'books',year:2025,level:'초등학교',track:'general',target:30000,budget:10000000,unit_cost:15000,weights:{gap:70,scale:30},preference:'선택한 학교당 장서 목표까지의 차이 70%, 같은 연도 학생 규모 30%'};
(async()=>{
 const inv=await p.inventory(base);assert(inv.schools.length>200);const s=inv.schools.find(s=>s.observed>0&&s.observed<30000&&s.track==='general');assert(s);assert(Number.isFinite(s.students));
 const empty=await p.scenario(base,[]);assert.equal(empty.scenario.allocation.rows.length,0);assert(empty.visual.table.rows.some(r=>r[0]===s.name&&r[3]===30000-s.observed));assert(!('ranking' in empty));assert(empty.scenario.schools.some(r=>r.gap===null));
 const record=school=>({schema:1,target:base.target,version_id:'review-'+school.id,school_id:school.id,resource:'books',year:2025,snapshot:inv.snapshot,valid_until:'2099-01-01',checks:Object.fromEntries(['eligibility','safety','execution','route'].map(key=>[key,{status:'verified',reason:'테스트 전용 · 실제 검증이 아님'}]))});
 const choices=inv.schools.filter(s=>s.track==='general'&&s.observed>0&&s.observed<30000&&s.students>0).slice(0,8),records=choices.map(record);
 const result=await p.scenario(base,records);assert(result.scenario.allocation.rows.length===8);assert(result.scenario.allocation.spent<=base.budget);assert(result.scenario.allocation.rows.every(r=>r.units<=r.gap&&Number.isInteger(r.units)));assert(result.scenario.allocation.rows.some(r=>r.units>0));
 const failed=structuredClone(records);failed[0].checks.safety.status='failed';const gate=await p.scenario({...base,weights:{gap:100,scale:0}},failed);assert(!gate.scenario.allocation.rows.some(r=>r.id===choices[0].id));
 const stale=structuredClone(records);stale[0].snapshot='old';assert(!p.gateState(choices[0],base,inv,stale).eligible);
 assert(!p.gateState(choices[0],{...base,target:base.target+10000},inv,records).eligible);
 const expired=structuredClone(records);expired[0].valid_until='2000-01-01';assert(!p.gateState(choices[0],base,inv,expired).eligible);
 const missing=await p.scenario({...base,year:2099},records);assert(missing.scenario.schools.every(r=>r.gap===null));assert.equal(missing.scenario.allocation.rows.length,0);
 await assert.rejects(()=>p.scenario({...base,version:0},records));await assert.rejects(()=>p.scenario({...base,weights:{gap:null,scale:30}},records));await assert.rejects(()=>p.scenario({...base,budget:null},records));await assert.rejects(()=>p.scenario({...base,track:''},records));await assert.rejects(()=>p.scenario({...base,preference:''},records));
 const legacy=await p.handle({...base,action:'studio_scenario',gates:{safety:'verified'},recommendation:'지원',records});assert.equal(legacy.scenario.allocation.rows.length,0);
 await assert.rejects(()=>p.review({...base,school_id:s.id},'wrong'));
 process.env.UPDATE_CENTER_TOKEN='isolated-test-token';
 const reviewInput={...base,school_id:s.id,reviewer:'테스트 전용 담당자',valid_until:'2099-01-01',checks:Object.fromEntries(['eligibility','safety','execution','route'].map(key=>[key,{status:'verified',source:'테스트 fixture 문서 1쪽',reason:'테스트 전용 상태 검증',document:'실제 학교의 확인 자료가 아닌 자동화 테스트 fixture입니다.'}]))};
 const saved=await p.review(reviewInput,'isolated-test-token');assert(saved.version_id);const replay=await p.handle({...base,action:'studio_scenario'});assert(replay.scenario.allocation.rows.some(r=>r.id===s.id));
 await p.review({...reviewInput,checks:{...reviewInput.checks,safety:{...reviewInput.checks.safety,status:'failed'}}},'isolated-test-token');const revoked=await p.handle({...base,action:'studio_scenario'});assert(!revoked.scenario.allocation.rows.some(r=>r.id===s.id));
 const tied=p.allocate([{id:'a',name:'A',gap:3,observed:10,students:100},{id:'b',name:'B',gap:3,observed:10,students:100}],50,10,{gap:1,scale:0});assert.deepEqual(tied.rows.map(r=>r.units),[2,2]);assert.equal(tied.remaining_budget,10);assert.equal(tied.rows[0].order,tied.rows[1].order);
 const w1=p.allocate([{id:'a',name:'A',gap:100,students:10},{id:'b',name:'B',gap:10,students:100}],100,1,{gap:1,scale:0}),w2=p.allocate([{id:'a',name:'A',gap:100,students:10},{id:'b',name:'B',gap:10,students:100}],100,1,{gap:0,scale:1});assert.equal(w1.rows[0].id,'a');assert.equal(w2.rows[0].id,'b');
 const dist=hitl.distribution([{id:'a',name:'A',v:1},{id:'b',name:'B',v:2},{id:'c',name:'C',v:null}],'v','observe');assert.equal(dist.chart.members.length,2);assert.equal(dist.chart.points.reduce((n,b)=>n+b.members.length,0),2);assert(dist.chart.points.flatMap(p=>p.members).some(m=>m.name==='A'));
 const out={actual_example:{school:s.name,observed:s.observed,selected_target:base.target,quantity_gap:base.target-s.observed,year:2025,decision:'조건 확인 전 집행 보류'},real_data:{schools:inv.schools.length,missing:empty.scenario.schools.filter(s=>s.gap===null).length,comparison_eligible:0},synthetic_verified_records:{count:8,spent:result.scenario.allocation.spent,note:'테스트 전용 근거. 실제 검증·학교 추천으로 사용 금지.'},checks:['missing coverage','safety non-compensation','explicit weights','no default ranking','legacy restore blocked','tied units','budget bound','source invalidation','weight sensitivity','drilldown membership']};
 fs.mkdirSync(path.join(__dirname,'../contest_plan'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../contest_plan/policy_studio_validation_20260912.json'),JSON.stringify(out,null,2));console.log('PASS policy studio',JSON.stringify(out.actual_example));
})().catch(e=>{console.error(e);process.exitCode=1;});
