'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
process.env.AI_AGENT_MAX_STEPS='1';
const agent=require('../api/_agent'),tools=require('../api/_agent_tools');
const originalFetch=global.fetch,ctx={level:'초등학교'};
const query={type:'function_call',call_id:'c1',name:'query_schools',arguments:JSON.stringify({sort_by:'zone_walk_mismatch_pct',limit:10})};
const reply=output=>({ok:true,text:async()=>JSON.stringify({output,usage:{input_tokens:100,output_tokens:20}})});
(async()=>{
 let calls=[];
 global.fetch=async(_,opts)=>{const b=JSON.parse(opts.body);calls.push(b);if(calls.length===1)return reply([{type:'reasoning',id:'reason1',encrypted_content:'opaque',summary:[]},query]);return reply([]);};
 let r=await agent.answer(ctx,'학구 조정 검토 학교 10곳');
 assert(r.answerable);assert(r.visual.sections[0].table.rows.length===10);assert(r.highlights.some(h=>h.includes('학교:')));assert.match(r.summary,/조회된 관측값/);
 assert(r.summary.includes(r.visual.sections[0].chart.points[0].name),'fallback must answer with a real school, not just describe settings');
 assert.equal(calls[1].tool_choice,'none','last call must produce an answer, not more tools');
 assert(calls[1].input.some(i=>i.type==='reasoning'),'reasoning state must survive function calls');
 const toolOutput=calls[1].input.find(i=>i.type==='function_call_output');assert.doesNotThrow(()=>JSON.parse(toolOutput.output));
 let n=0;global.fetch=async()=>{if(n++===0)return reply([query]);throw Error('upstream unavailable');};
 r=await agent.answer(ctx,'학구 조정 검토 학교 10곳');assert(r.answerable);assert(r.visual.sections.length);assert(r.highlights.length);
 global.fetch=async()=>reply([]);
 r=await agent.answer(ctx,'질문');assert.equal(r.answerable,false,'empty response without evidence is not success');
 r=tools.run('weighted_rank',ctx,{criteria:[{column:'parks_walk',prefer:'low',weight:90},{column:'students',prefer:'high',weight:10}],limit:10});
 assert(!JSON.stringify(r).includes('"score"'));assert.equal(r.sections.length,2);assert.match(r.llm.constraints,/상쇄하지/);
 assert.throws(()=>tools.run('weighted_rank',ctx,{criteria:[{column:'students',weight:Infinity}]}),/숫자/);
 assert.throws(()=>tools.run('query_schools',ctx,{sort_by:'paps'}),/등급 정의/);
 assert(!tools.run('school_profile',ctx,{school_id:'B000003024',columns:['paps']}).llm.indicators.some(i=>i.column==='paps'));
 const missing=tools.run('query_schools',ctx,{where:[{column:'zone_walk_mismatch_pct',op:'is_null'}],sort_by:'zone_walk_mismatch_pct'});
 assert.equal(missing.llm.rows.length,0);assert(missing.llm.excluded_missing>0);
 const dom=new JSDOM('<aside id="evidence-panel"></aside>',{runScripts:'outside-only'}),w=dom.window;
 w.eval(fs.readFileSync(path.join(__dirname,'../assets/chat-workspace.js'),'utf8'));
 const safe=w.ChatWorkspace.safeResult({summary:'A초 투자 1위',weights:[{weight:100}],visual:{sections:[{chart:{unit:'점',points:[{value:90}]}}]}});
 assert.equal(safe.answerable,false);assert(!safe.summary.includes('A초'));assert.equal(safe.visual.sections.length,0);
 const chart=w.ChatWorkspace.chart({kind:'bar',points:[{name:'누락',value:null},{name:'관측',value:3}]});assert(!chart.includes('누락'));assert(chart.includes('관측'));
 dom.window.close();console.log('PASS answer recovery, final tool budget, reasoning state, empty output, missing coverage, separate safety conditions, no scores, legacy restoration');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{global.fetch=originalFetch;});
