'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const dom=new JSDOM('<aside id="evidence-panel"></aside>',{runScripts:'outside-only'}),w=dom.window,d=w.document,maps=[];
w.ChatMap={dispose(){},mount(host,result){maps.push({host,result});}};
w.eval(fs.readFileSync(path.join(__dirname,'../assets/chat-workspace.js'),'utf8'));
const school=(id,name,students,books)=>({id,name,values:{students,books}}),point=(id,name)=>({id,name,lat:37.5,lng:126.7});
const result={observation_version:1,answerable:true,visual:{overview:{version:1,status:'focused',title:'학교 지원 검토 근거',summary:'두 학교의 수요와 장서를 함께 확인했습니다.',schools:[school('a','가초',120,null),school('b','나초',0,5)],columns:[{id:'students',label:'학생 수',unit:'명',group:'현재 수요'},{id:'books',label:'학생당 장서',unit:'권',group:'학교 내부 자원'}],notes:['직선거리는 검증된 보행 접근성이 아닙니다.'],constraints:['안전과 이용 조건 확인 전 지원 결정 보류']},map:[point('a','가초'),point('b','나초'),point('c','다초')],sections:[{title:'학생 수 전체 조회',map:[point('z','다른 학교')],chart:{kind:'bar',points:[{name:'다른 학교',value:900}],unit:'명'}}]}};
w.ChatWorkspace.show(result,'도서관 지원 학교 두 곳');
assert.equal(d.querySelector('#evidence-overview').hidden,false);
assert.equal(d.querySelector('#evidence-details').hidden,true);
assert.equal(d.querySelector('#evidence-overview-tab').getAttribute('aria-selected'),'true');
assert.equal(d.querySelectorAll('.evidence-matrix tbody tr').length,2,'all variables visible together');
assert.equal(d.querySelectorAll('.evidence-matrix td').length,4);
assert.equal(d.querySelectorAll('.evidence-missing').length,1,'missing remains distinct from observed zero');
assert.equal(d.querySelector('.evidence-matrix tbody tr td:nth-child(3) strong').textContent,'0');
assert.match(d.querySelector('#evidence-overview').textContent,/지원 결정 보류/);
assert.equal(d.querySelectorAll('#evidence-overview svg').length,0,'single variable chart absent from overview');
assert.equal(d.querySelectorAll('#evidence-details svg').length,1,'variable chart stays in detail tab');
assert.deepEqual(Array.from(maps[0].result.visual.map,p=>p.id),['a','b'],'map excludes unrelated and selected-context schools');
assert.equal(maps[0].result.visual.sections.length,0,'no section union can add unrelated school markers');
d.querySelector('#evidence-details-tab').click();
assert.equal(d.querySelector('#evidence-details').hidden,false);assert.equal(d.querySelector('#evidence-overview').hidden,true);
d.querySelector('#evidence-details-tab').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));
assert.equal(d.querySelector('#evidence-overview').hidden,false,'keyboard tabs work');
w.ChatWorkspace.show(result,'저장된 답변 다시 보기',{omitMap:true});assert.equal(maps.length,1,'omitMap respected');
const unresolved={...result,visual:{...result.visual,overview:{...result.visual.overview,status:'unresolved',schools:[]}}};
w.ChatWorkspace.show(unresolved,'학교가 특정되지 않은 답변');assert.equal(maps.length,1);assert.match(d.querySelector('#evidence-overview').textContent,/학교가 확인되지 않아/);
w.ChatWorkspace.show({observation_version:1,visual:{sections:result.visual.sections}},'이전 대화');assert.equal(maps.length,1);assert.match(d.querySelector('#evidence-overview').textContent,/이전 답변/);
const malicious=structuredClone(result);malicious.visual.overview.schools[0].name='<img src=x onerror=alert(1)>';w.ChatWorkspace.show(malicious,'escaping');assert.equal(d.querySelectorAll('img').length,0);
const extended=structuredClone(result);extended.visual.overview.schools[0].name='인천가초등학교';extended.visual.overview.additional_candidates={status:'available',title:'추가 비교 후보',schools:Array.from({length:10},(_,i)=>({...school('extra'+i,'후보'+i+'초',100+i,i===0?null:i),metric_position:i+3})),criteria:[{label:'재학생 수'}],notes:['안전과 이용 조건은 별도 확인']};
w.ChatWorkspace.show(extended,'추가 후보 비교');
const extras=d.querySelector('.evidence-additional-candidates');assert.equal(extras.open,false,'additional schools collapsed by default');
assert.equal(extras.querySelectorAll('thead th[scope=col]').length,11,'10 extra candidates with same selected variable table');
assert.equal(d.querySelector('.evidence-counts b').textContent,'2','main count never includes additional candidates');
assert.equal(maps.at(-1).result.visual.map.length,2,'extra schools never added to main map');
assert.equal(extras.querySelectorAll('tbody tr').length,2);assert.equal(extras.querySelectorAll('.evidence-missing').length,1);assert.match(extras.textContent,/지표 기준 3번째/);
const probe=d.createElement('p');probe.innerHTML=w.ChatWorkspace.schoolText('인천가초등학교입니다. 가초는 자료 확인, 가초이고 후보0초도 비교. <img src=x> 알수없는초등학교 신가초등학교',extended);
assert.deepEqual(Array.from(probe.querySelectorAll('a'),a=>a.textContent),['인천가초등학교','가초','가초','후보0초'],'canonical, short alias, Korean particles supported; unmatched schools not linked');
assert.equal(probe.querySelectorAll('img').length,0);assert(probe.textContent.includes('<img src=x>'));
assert.equal(probe.querySelector('a').getAttribute('href'),'/index.html?school=a#summary');assert.equal(probe.querySelector('a').target,'_blank');assert.equal(probe.querySelector('a').rel,'noopener');
dom.window.close();console.log('PASS overview, focused maps, detail tabs, missing values, constraints, saved responses, report links/aliases, collapsed additional candidates and escaping');
