'use strict';
process.env.AI_EXPLAINER_ENABLED='false';
const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom'),chat=require('../api/chat'),planner=require('../api/_collection_plan'),doc=require('../api/_document_evidence');
(async()=>{
 for(const [q,ids] of [['도서관 지원',['reading','execution']],['도보 통학 안전',['route']],['재건축 입주 예측',['demand']],['돌봄 대기 문제',['care']],['학원가 격차',['academy']],['폭염 때문에 활동을 못해',['environment']],['교육 지원 효과',['outcome','execution']]]){const p=planner.plan({question:q});for(const id of ids)assert(p.items.some(i=>i.id===id),q+id);assert(p.items.every(i=>i.reason&&i.fields.includes('출처')&&i.decision_effect));}
 const libraries=planner.plan({question:'도서관 지원'}).items[0];assert(libraries.sources.find(s=>s.dataset==='libraries').check.type==='refresh_pipeline');assert(!libraries.sources.find(s=>s.dataset==='school_library').auto_apply);assert(planner.plan({question:'안녕'}).unresolved);
 const gaps=planner.plan({question:'자료 확인'},{join:{total:10,excluded:2},visual:{sections:[{title:'장서',statistics:{n:0,excluded:3}}]}});assert.equal(gaps.observed_gaps.length,2);
 const direct=await chat.run({question:'전체 초등학교 학생 수 통계',scope:'all'});assert(direct.collection_plan.items.length);const plan=await chat.run({action:'hitl_plan',question:'공원 지원을 검토해줘',scope:'all'});assert(plan.collection_plan.items.some(i=>i.id==='execution'));assert(!JSON.stringify(plan.collection_plan).includes('종합점수'));
 const u={kind:'document',name:'현장 기록.txt',parts:[{location:'1줄',text:'도서관은 평일 오후 5시까지 개방한다. 출입구 경로 안전은 미확인이다.'},{location:'2줄',text:'급식 메뉴는 쌀밥이다.'}],sha256:'a'.repeat(64)};
 const answer=await chat.run({question:'도서관 개방시간을 정리해줘',upload:u,scope:'all'});assert.equal(answer.mode,'document_evidence');assert(answer.sources.every(s=>s.source_chain.status==='user_provided'));assert.equal(answer.sources.length,1);assert(answer.sources[0].source_chain.files[0].path.includes('1줄'));assert(answer.collection_plan.items.some(i=>i.id==='reading'));assert.equal(doc.select('다른말',u).length,0);assert.throws(()=>doc.select('질문',{...u,parts:[{location:'1',text:'a'.repeat(2001)}]}));assert.throws(()=>doc.select('질문',{...u,parts:[{}]}));
 const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'outside-only'}),w=dom.window;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.eval(fs.readFileSync('assets/attachment-reader.js','utf8'));w.eval(fs.readFileSync('assets/chat-upload.js','utf8'));const r=w.AttachmentReader;
 assert.equal(r.json('[{"학교명":"학교","값":0}]')[1][1],0);assert.equal(r.json('{"headers":["학교명","값"],"rows":[["학교",3]]}')[1][1],3);assert.equal(r.json('{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"학교명":"학교"},"geometry":{"type":"Point","coordinates":[126,37]}}]}')[1][1],126);assert.throws(()=>r.json('[{"a":{"b":1}}]'));assert.throws(()=>r.json('{"type":"FeatureCollection","features":[{"properties":{},"geometry":{"type":"Point","coordinates":[1000000,300000]}}]}'));
 assert.equal(r.documentPayload({name:'a.txt',parts:[{location:'1줄',text:'가'.repeat(4000)}]}).parts.length,3);
 w.ChatUpload.init();let finish;const file={name:'늦은.csv',size:20,arrayBuffer:()=>new Promise(resolve=>finish=resolve)};Object.defineProperty(w.document.getElementById('upload-file'),'files',{configurable:true,value:[file]});const reading=w.document.getElementById('upload-file').onchange();w.ChatUpload.clear();finish(Buffer.from('학교명,값\n학교,1').buffer);await reading;assert.equal(w.ChatUpload.payload(),undefined);dom.window.close();
 console.log('PASS collection requirements, automatic/manual paths, result gaps, direct/HITL/document flows, bounded document sources, JSON/GeoJSON, stale upload cancellation');
})().catch(e=>{console.error(e);process.exitCode=1;});
