'use strict';
const assert=require('node:assert/strict');
const table=require('../api/_school_table');
const tools=require('../api/_agent_tools');
const {buildOverview,buildVisual,overviewSources}=require('../api/_answer_overview');
const T=table.build();
const result=tools.run('query_schools',{level:'초등학교'},{sort_by:'nearest_public_library_m',order:'desc',limit:50,columns:['students','forecast_2029','forecast_2031','books_per_student','libraries_walk'],island:'exclude'});
const rows=result.llm.rows;
assert.equal(rows.length,50);
assert(rows.every(r=>T.byId.has(r.id)),'tool rows expose grounded school IDs');
const chosen=rows.slice(1,6),summary=chosen.map(r=>r.name.replace(/초등학교$/,'초')).join(', ')+'를 함께 검토할 수 있습니다.';
const final={summary,focus_school_ids:[...chosen.map(r=>r.id),'invented-school',rows[0].id]};
const visual=buildVisual(final,[result.visual],{school_id:rows[0].id,selected_variables:['도서관 좌석 수']});
assert.equal(visual.overview.status,'focused');
assert.deepEqual(visual.overview.school_ids,chosen.map(r=>r.id));
assert.deepEqual(visual.map.map(r=>r.id),chosen.map(r=>r.id));
assert.equal(visual.map.length,5,'50 queried schools must not leak into the five-school answer map');
const excludedMention=buildVisual({summary:summary+' '+rows[0].name+'는 이번 목록에서 제외합니다.',focus_school_ids:chosen.map(r=>r.id)},[result.visual]);
assert.deepEqual(excludedMention.overview.school_ids,chosen.map(r=>r.id),'a school mentioned only for exclusion must not expand explicit focus');
for(const school of visual.overview.schools){
 assert.equal(school.values.students,T.byId.get(school.id).students);
 assert.equal(school.values.forecast_2029,T.byId.get(school.id).forecast_2029);
 assert.equal(school.values.books_per_student,T.byId.get(school.id).books_per_student);
 assert.equal(school.values.libraries_walk,T.byId.get(school.id).libraries_walk);
 assert(school.forecast_evidence);
}
assert(!('score' in visual.overview));
assert(visual.overview.constraints.some(s=>s.includes('상쇄')));
assert(visual.overview.notes.some(s=>s.includes('0이나 부족')));
assert(!visual.sections[0].map,'detail section must not restore broad map');
const unresolved=buildVisual({summary:'자료만으로 한 학교를 특정할 수 없습니다.',focus_school_ids:rows.slice(0,5).map(r=>r.id)},[result.visual],{});
assert.equal(unresolved.overview.status,'unresolved');
assert.equal(unresolved.map.length,0,'unmentioned IDs must not create school recommendations');
const legacy=buildVisual({summary},[{...result.visual,evidence:undefined}],{});
assert.equal(legacy.map.length,0,'metadata-free legacy results must not silently adopt the first map');
const agg=buildVisual({summary:'학교급별 평균을 확인했습니다.'},[{title:'평균',table:{headers:['평균'],rows:[[5]]}}]);
assert.equal(agg.overview.status,'aggregate');
assert.equal(agg.map.length,0);
const savedRow=T.byId.get(chosen[0].id),saved=savedRow.books_per_student;
try{
 savedRow.books_per_student=null;
 const nullResult=buildOverview(final,[result.visual]);
 assert.equal(nullResult.schools.find(r=>r.id===savedRow.id).values.books_per_student,null);
}finally{savedRow.books_per_student=saved;}
const selectedColumn='library_seats';
const selected=buildOverview(final,[result.visual],{selected_variables:[table.COLUMNS[selectedColumn].label]});
assert(selected.columns.some(c=>c.id===selectedColumn),'confirmed variables are included even if omitted by model tool columns');
assert.equal(selected.schools[0].values[selectedColumn],T.byId.get(chosen[0].id)[selectedColumn]);
const sources=overviewSources([], {overview:selected});
assert(selected.columns.every(c=>sources.some(s=>s.id===c.source_id)),'every variable has a resolvable actual source');
const scenario=T.rows.find(r=>r.forecast_status==='limited_history_constant_scenario');
assert(scenario,'fixture contains limited-history scenario');
const scenarioOverview=buildOverview({summary:scenario.name+'의 학생 규모를 확인했습니다.',focus_school_ids:[scenario.id]},[{evidence:{school_ids:[scenario.id],columns:['students','forecast_2029','forecast_2031']}}]);
assert(scenarioOverview.notes.some(n=>n.includes(scenario.name)&&n.includes('시나리오')),'school-specific forecast scenario caveat stays visible');
console.log('answer overview: focused schools, all variables, missing coverage, safety gates, no scores, and legacy fallback passed');

const small=tools.run('query_schools',{level:'초등학교'},{sort_by:'students',order:'desc',limit:5,columns:['students','forecast_2029','forecast_2031'],island:'exclude',gu:'서구',where:[{column:'students',op:'>',value:100}]});
const primary=small.llm.rows;
assert.equal(primary.length,5,'extra pool must not change requested LLM answer row count');
assert.equal(small.visual.map.length,5,'extra pool must not change tool map');
assert.equal(small.visual.table.rows.length,5,'extra pool must not change table');
const smallFinal={summary:primary.map(r=>r.name).join(', ')+'를 검토합니다.',focus_school_ids:primary.map(r=>r.id)};
const smallVisual=buildVisual(smallFinal,[small.visual]);
const additional=smallVisual.overview.additional_candidates;
assert.equal(smallVisual.overview.schools.length,5);
assert.equal(smallVisual.map.length,5);
assert.equal(additional.schools.length,10,'five requested schools retain ten bounded extra candidates');
assert.equal(additional.ordering,'subsequent_metric');
assert.deepEqual(additional.schools.map(s=>s.metric_position),[6,7,8,9,10,11,12,13,14,15]);
assert(additional.schools.every(r=>!smallFinal.focus_school_ids.includes(r.id)));
assert(additional.schools.every(r=>r.level==='초등학교'&&r.gu==='서구'&&!r.island&&r.values.students>100),'all original scope and where conditions retained');
assert(additional.schools.every((r,i,rs)=>!i||rs[i-1].values.students>=r.values.students),'single metric ordering retained without composite rank');
assert(additional.notes.some(n=>n.includes('추가 지원 순위가 아닙니다')));
assert(additional.schools.every(r=>r.aliases.includes(r.name)));
const fixed=tools.run('query_schools',{level:'초등학교'},{school_ids:smallFinal.focus_school_ids,limit:5,columns:['students']});
assert.equal(buildVisual(smallFinal,[fixed.visual]).overview.additional_candidates.schools.length,0,'explicit exact-school scope must not broaden');
assert.equal(buildVisual(smallFinal,[small.visual,fixed.visual]).overview.additional_candidates.schools.length,10,'verification query does not discard original scoped continuation');
assert.equal(buildVisual({summary:'학교를 특정하지 않습니다.',focus_school_ids:[]},[small.visual]).overview.additional_candidates.schools.length,0,'no alternatives without grounded primary schools');
const narrow=tools.run('query_schools',{level:'초등학교'},{sort_by:'students',order:'desc',limit:5,gu:'서구',island:'exclude',where:[{column:'students',op:'>=',value:T.byId.get(primary[4].id).students}],columns:['students']});
const intersection=buildVisual(smallFinal,[small.visual,narrow.visual]).overview.additional_candidates;
assert(intersection.schools.every(r=>r.values.students>=T.byId.get(primary[4].id).students),'multiple query conditions intersect instead of being replaced');
const nonPrefix={summary:primary.slice(1).map(r=>r.name).join(', ')+'를 검토합니다.',focus_school_ids:primary.slice(1).map(r=>r.id)};
const nonPrefixExtra=buildVisual(nonPrefix,[small.visual]).overview.additional_candidates;
assert.equal(nonPrefixExtra.ordering,'metric');
assert(nonPrefixExtra.schools.every(s=>s.metric_position===undefined),'nonprefix selection cannot claim next metric positions');
console.log('additional candidates: bounded continuation, unchanged main count/map, exact filters, no implicit rank, and fixed-school scope passed');

const branchQuery=tools.run('query_schools',{level:'초등학교'},{sort_by:'nearest_public_library_m',order:'desc',limit:5,island:'exclude',columns:['students','libraries_walk']});
const branch=T.byId.get('B000002962'),main=T.byId.get('B000002959');
assert(branchQuery.llm.rows.some(r=>r.id===branch.id));
const branchSummary=branchQuery.llm.rows.map(r=>r.name.replace('초등학교','초')).join(', ')+'입니다.';
const branchVisual=buildVisual({summary:branchSummary,focus_school_ids:branchQuery.llm.rows.map(r=>r.id)},[branchQuery.visual]);
assert.equal(branchVisual.overview.schools.length,5,'abbreviated branch name retains all five primary schools');
assert.equal(branchVisual.map.length,5);
assert(branchVisual.overview.schools.find(r=>r.id===branch.id).aliases.includes('인천영종초금산분교장'));
assert(!branchVisual.overview.additional_candidates.schools.some(r=>r.id===branch.id),'named primary branch must never leak into extras');
const branchScope=[{evidence:{school_ids:[main.id,branch.id],columns:['students']}}];
assert.deepEqual(buildOverview({summary:'인천영종초금산분교장을 확인했습니다.'},branchScope).school_ids,[branch.id],'branch abbreviation must not also match main school');
assert.deepEqual(buildOverview({summary:'인천영종초를 확인했습니다.'},branchScope).school_ids,[main.id],'main school abbreviation must not match branch');
assert.deepEqual(buildOverview({summary:'인천영종초등학교금산분교장을 확인했습니다.'},branchScope).school_ids,[branch.id]);
console.log('branch alias regression: five primary schools retained; main and branch remain distinct');
