'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('C:/Users/Mijin/Desktop/project_city/node_modules/playwright-core');
const root=path.resolve(__dirname,'..'),live=process.argv.includes('--live'),url='https://education-living-area-preview-production.up.railway.app',work=path.resolve(root,'../outputs/collection_upload_20260912'),out=path.join(work,live?'live':'preview');fs.mkdirSync(out,{recursive:true});
const files=['index.html','assets/chat-upload.js','assets/attachment-reader.js','assets/attachment-support.css','assets/collection-assistant.js','assets/hitl-analysis.js','assets/simple-app.js','assets/chat-workspace.js'];
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],checked=[];page.setDefaultTimeout(45000);page.on('pageerror',e=>errors.push(e.message));
 if(!live){process.env.AI_EXPLAINER_ENABLED='false';await page.route(url+'/**',async route=>{const p=new URL(route.request().url()).pathname,file=p==='/'?'index.html':p.slice(1);if(['/api/chat','/api/chat-upload'].includes(p)){try{const body=route.request().postDataJSON(),d=p==='/api/chat'?await require('../api/chat').run(body):await require('../api/chat-upload').extract(body);return route.fulfill({json:d});}catch(e){return route.fulfill({status:400,json:{summary:e.message,error:e.message}});}}if(files.includes(file))return route.fulfill({path:path.join(root,file),contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html'});return route.continue();});}
 await page.goto(url,{waitUntil:'domcontentloaded'});await page.locator('[data-workspace="ask"]').first().click();await page.locator('#upload-details').evaluate(e=>e.open=true);await page.waitForFunction(()=>document.querySelector('#upload-existing').options.length>0);
 for(const ext of ['csv','tsv','xlsx','xls','json','geojson','docx','hwpx']){await page.locator('#upload-file').setInputFiles(path.join(work,'fixtures','표.'+ext));await page.locator('#upload-status').filter({hasText:'3행 ×'}).waitFor();await page.locator('#upload-key').selectOption('0');await page.locator('#upload-measure').selectOption('1');await page.locator('#upload-year').selectOption('2');const payload=await page.evaluate(()=>window.ChatUpload.payload());assert.equal(payload.rows.length,3,ext);assert.equal(Number(payload.rows[0][1]),10,ext);checked.push(ext);if(ext==='docx'){await page.locator('#upload-mode').selectOption('document');assert.equal((await page.evaluate(()=>window.ChatUpload.payload())).kind,'document');await page.locator('#upload-mode').selectOption('table');}}
 // A title above the header can be skipped without editing the original CSV.
 await page.locator('#upload-file').setInputFiles({name:'머리말.csv',mimeType:'text/csv',buffer:Buffer.from('현장 조사\n학교명,값,연도\n인천석암초등학교,0,2026')});await page.locator('#upload-header-row').fill('2');await page.locator('#upload-header-row').dispatchEvent('change');await page.locator('#upload-status').filter({hasText:'1행 × 3열'}).waitFor();assert.equal((await page.evaluate(()=>window.ChatUpload.payload())).rows[0][1],'0');
 await page.locator('#upload-file').setInputFiles(path.join(root,'data/context_sources/raw/ice_autonomous_school_2026_designation.hwp'));await page.locator('#upload-status').filter({hasText:'본문'}).waitFor();assert.equal((await page.evaluate(()=>window.ChatUpload.payload())).kind,'document');checked.push('hwp');
 for(const ext of ['txt','md','pdf']){await page.locator('#upload-file').setInputFiles(path.join(work,'fixtures','현장.'+ext));await page.locator('#upload-status').filter({hasText:'본문'}).waitFor();const payload=await page.evaluate(()=>window.ChatUpload.payload());assert.equal(payload.kind,'document');assert(payload.parts.length>0);checked.push(ext);}
 await page.locator('#question').fill('PDF 내용을 요약하고 안전 확인에 필요한 자료를 알려줘');const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/chat'&&!r.request().postDataJSON()?.action);await page.locator('#send').click();const result=await (await response).json();assert.equal(result.mode,'document_evidence');assert(result.sources.some(s=>s.title.includes('1페이지')));await page.locator('.message .source-proof').first().waitFor();assert(await page.locator('.message .collection-need').count());await page.locator('.message .collection-need').first().evaluate(e=>e.open=true);await page.locator('.message .collection-need').first().scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'document-and-collection.png')});
 await page.locator('#upload-remove').click();await page.locator('#question').fill('초등학교 도서관 지원을 검토해줘');await page.locator('#send').click();await page.locator('.hitl-plan [data-factor]').first().check();await page.locator('.hitl-results .source-evidence').waitFor();const need=page.locator('.hitl-checks .collection-need').first();await need.evaluate(e=>e.open=true);assert((await need.innerText()).includes('확보 후 달라지는 판단'));await need.locator('.collection-paths').evaluate(e=>e.open=true);assert(await need.locator('a[href*="data.go.kr"]').count());
 const download=await Promise.all([page.waitForEvent('download'),need.locator('.collection-template').click()]);const dest=path.join(out,'collection-template.csv');await download[0].saveAs(dest);assert(fs.readFileSync(dest,'utf8').includes('대기학생수_명'));await need.locator('.collection-attach').click();assert(await page.locator('#upload-details').evaluate(e=>e.open));
 await page.setViewportSize({width:390,height:844});await need.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'collection-mobile.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
 await page.reload({waitUntil:'domcontentloaded'});await page.locator('[data-workspace="ask"]').first().click();await page.waitForFunction(()=>document.querySelector('.topic-select')?.options.length>1);await page.selectOption('.topic-select',{index:1});await page.locator('.analysis-topics>details').evaluate(e=>e.open=true);await page.getByRole('button',{name:'당시 근거 다시 보기'}).last().click();assert(await page.locator('#evidence-panel .collection-need').count());assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify({passed:true,live,formats:checked,checks:['header row selection','DOCX table/document switch','HITL document dispatch','page citations','question-specific collection and official sources','downloadable collection template','mobile overflow','topic restore'],errors},null,2));console.log('PASS '+(live?'LIVE':'PREVIEW')+' 12 formats + collection + document evidence + history');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
