const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.MAP_QA_URL||'http://127.0.0.1:3100';
const output=path.resolve(__dirname,'../outputs/map-review');fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.MAP_QA_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto(base,{waitUntil:'domcontentloaded'});
  await page.locator('#map-zone-status').filter({hasText:'279개'}).waitFor({timeout:30000});
  await page.locator('.leaflet-tile-loaded').first().waitFor();
  await page.screenshot({path:path.join(output,'desktop-start.png'),fullPage:true});
  await page.locator('[data-map-level="유치원"]').check({force:true});
  assert.match(await page.locator('#map-count').textContent(),/641곳/);
  const represented=await page.locator('[data-school-count]').evaluateAll(nodes=>nodes.reduce((n,e)=>n+Number(e.dataset.schoolCount),0));assert.equal(represented,641);
  await page.locator('#search').fill('신흥');await page.locator('.leaflet-schoolPoints-pane path[aria-label*="인천신흥초등학교"]').click();
  if(await page.locator('.leaflet-popup').isVisible())await page.locator('.leaflet-popup').getByRole('button',{name:'인천신흥초등학교 · 초등학교 선택',exact:true}).click();
  await page.locator('#summary h2').filter({hasText:'인천신흥초등학교'}).waitFor();
  assert.match(await page.locator('#map-zone-status').textContent(),/공식 연결된 학구 1개/);
  assert.equal(await page.locator('.leaflet-schoolRadius-pane path').count(),1);
  assert.equal(await page.locator('.leaflet-schoolZones-pane path').count(),1);
  assert.equal(await page.locator('[data-map-level]:checked').count(),2);
  await page.locator('#map-zones').uncheck();assert.equal(await page.locator('.leaflet-schoolZones-pane path').count(),0);
  await page.locator('#map-zones').check();assert.equal(await page.locator('.leaflet-schoolZones-pane path').count(),1);
  await page.locator('#map-zone-fit').click();await page.screenshot({path:path.join(output,'desktop-school.png'),fullPage:true});
  await page.locator('#map-radius').uncheck();assert.equal(await page.locator('.leaflet-schoolRadius-pane path').count(),0);await page.locator('#map-radius').check();
  await page.locator('#search').fill('');
  const kindergarten=await page.locator('#school option').evaluateAll(options=>options.find(o=>o.textContent.includes('유치원'))?.value);assert(kindergarten);
  await page.locator('#school').selectOption(kindergarten);await page.locator('#map-zone-status').filter({hasText:'유치원 학구도는 원자료에서 제공하지 않습니다'}).waitFor();
  assert.equal(await page.locator('.leaflet-schoolZones-pane path').count(),0);
  await page.locator('#map-clear-school').click();await page.locator('#map-all-levels').click();assert.match(await page.locator('#map-count').textContent(),/917곳/);
  await page.locator('#map-fit').click();await page.screenshot({path:path.join(output,'desktop-all-islands.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.reload();
  await page.locator('#map-zone-status').filter({hasText:'279개'}).waitFor();
  assert.equal(await page.locator('#map-options').getAttribute('open'),null);
  await page.locator('[data-map-level="유치원"]').check({force:true});assert.match(await page.locator('#map-count').textContent(),/641곳/);
  await page.screenshot({path:path.join(output,'mobile-start.png'),fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile horizontal overflow');
  await page.locator('#map-options>summary').click();await page.locator('#search').fill('신흥');await page.locator('#school').selectOption('B000002949');
  await page.locator('#summary h2').filter({hasText:'인천신흥초등학교'}).waitFor();
  await page.locator('#map-options>summary').click();await page.locator('#school-map').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(output,'mobile-school.png'),fullPage:true});
  await page.locator('.workspace-nav [data-workspace="review"]').click();await page.locator('#review-purpose').fill('경계와 통학 조건 확인');await page.locator('#review-reason').fill('출입구 보행 경로 확인 후 판단');
  assert.equal(await page.locator('#save-review').isEnabled(),true);
  assert.equal(await page.locator('.workspace-page:visible').count(),1);
  await page.locator('.workspace-nav [data-workspace="explore"]').click();
  assert.equal(await page.locator('#school-map').isVisible(),true);assert.equal(errors.length,0,errors.join('\n'));
  const result={url:base,checked_at:new Date().toISOString(),school_union:641,all_schools:917,elementary_zones:279,selected_school:'B000002949',selected_zones:1,kindergarten_boundary:'not_published',mobile_width:390,horizontal_overflow:false,page_errors:errors,screenshots:fs.readdirSync(output).filter(f=>f.endsWith('.png'))};
  fs.writeFileSync(path.join(output,'validation.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
