const {chromium}=require('C:/Users/Mijin/Desktop/SAbuffet/node_modules/playwright-core'),fs=require('fs'),assert=require('node:assert/strict');
const base=process.env.QA_BASE||'http://127.0.0.1:8877',out='outputs/adaptive-dashboard-20260916';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:'C:/Users/Mijin/AppData/Local/ms-playwright/chromium-1243/chrome-win64/chrome.exe'});try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/?school=B000002951');await page.locator('[data-workspace=stats]').click();await page.locator('.ds-chart-grid').waitFor();
const grid=page.locator('.ds-chart-grid');assert(await page.locator('.ds-main-histogram').isVisible());assert(await page.locator('.ds-districts').isVisible());assert.equal(await page.locator('.ds-numeric-details').getAttribute('open'),null);
const boxes=await page.locator('.ds-chart-grid > section').evaluateAll(es=>es.map(e=>{const b=e.getBoundingClientRect();return {x:b.x,y:b.y,width:b.width}}));assert(boxes.length>=2);assert(Math.abs(boxes[0].y-boxes[1].y)<4,'charts side by side');
const response=await page.request.get(base+'/api/domain-stats?domain=park&level='+encodeURIComponent('초등학교'));const data=await response.json();const column=await page.locator('[data-indicator][aria-pressed=true]').getAttribute('data-indicator');const i=data.indicators.find(i=>i.column===column);assert.equal((await page.locator('.ds-hist-count').allTextContents()).reduce((n,s)=>n+Number(s),0),i.coverage.general.available);
await page.locator('.ds-view-tabs').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/park-desktop.png'});
const gu=await page.locator('.ds-bar-row').first().getAttribute('data-district-open');await page.locator('.ds-bar-row').first().click();assert.equal(await page.locator('#stats-district').inputValue(),gu);
await page.locator('[data-view=distribution]').click();await page.locator('[data-track=island]').click();assert((await page.locator('.ds-context').innerText()).includes('강화'));assert.equal((await page.locator('.ds-hist-count').allTextContents()).reduce((n,s)=>n+Number(s),0),i.coverage.island.available);
await page.locator('[data-track=general]').click();for(const domain of ['reading','safety','trend']){await page.locator('#stats-domain').selectOption(domain);await page.waitForFunction(domain=>document.querySelector('.ds-dashboard')?.dataset.domain===domain,domain);assert(await page.locator('.ds-main-histogram').isVisible());assert(await page.locator('.ds-districts').isVisible());await page.locator('.ds-view-tabs').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/'+domain+'.png'});}
await page.locator('#stats-domain').selectOption('reading');await page.locator('#stats-level').selectOption('유치원');await page.waitForFunction(()=>document.querySelector('.ds-overview')?.textContent.includes('관측된 값이 없습니다'));assert.equal(await page.locator('.ds-hist-count').count(),0);assert((await page.locator('#stats-body').innerText()).includes('미확보'));
await page.locator('#stats-level').selectOption('초등학교');await page.locator('#stats-domain').selectOption('park');await page.waitForFunction(()=>document.querySelector('.ds-dashboard')?.dataset.domain==='park');await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('.ds-main-histogram').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/mobile.png'});assert.deepEqual(errors,[]);fs.writeFileSync(out+'/browser-check.json',JSON.stringify({base,passed:true,at:new Date(),checks:['two charts immediately visible','correct histogram total','district drilldown','island totals','reading safety trend','missing data','mobile overflow']},null,2));console.log('PASS chart-first dashboard',base);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
