// Isolated ephemeral server: no scheduler, deployment, or shared build output.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
process.env.AI_EXPLAINER_ENABLED='false';
const chat=require('../api/chat'),model=require('../api/_school_summary'),root=path.resolve(__dirname,'..');
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/chat'){let raw='';for await(const c of req)raw+=c;req.body=JSON.parse(raw);return chat(req,res);}if(u.pathname==='/api/school-summary'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(u.searchParams.has('id')?model.summary(u.searchParams.get('id'),u.searchParams.get('kind')):{schools:model.list()}));}const file=path.resolve(root,'.'+decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.json':'application/json','.geojson':'application/json','.png':'image/png'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);}catch(e){res.statusCode=400;res.end(JSON.stringify({summary:e.message}));}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const output=path.join(root,'outputs/hitl-analysis');fs.mkdirSync(output,{recursive:true});try{
 browser=await chromium.launch({headless:true,executablePath:process.env.HITL_QA_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'domcontentloaded'});
 await page.locator('.workspace-nav [data-workspace="ask"]').click();await page.locator('#question').fill('어느 학교 도서관을 우선지원할지 정해야해');await page.locator('#send').click();await page.locator('.hitl-dataset').selectOption('books');await page.getByRole('button',{name:'장서 총수 (권) +',exact:true}).click();await page.locator('.hitl-dataset').selectOption('library_access');await page.getByRole('button',{name:'공공 어린이도서관 직선거리 m +',exact:true}).click();
 await page.locator('.hitl-selected .direction').nth(0).selectOption('lower');await page.locator('.hitl-selected .direction').nth(1).selectOption('higher');await page.locator('.hitl-run').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'desktop-selection.png')});
 await page.locator('.hitl-run').click();await page.locator('.hitl-results button').first().waitFor({timeout:65000});assert.match(await page.locator('.hitl-status').innerText(),/우선순위가 없어/);assert(await page.locator('#evidence-panel svg').count()>0);
 await page.locator('#evidence-panel').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'desktop-result.png')});
 await page.locator('.hitl-selected .weight').nth(0).selectOption('3');await page.locator('.hitl-selected .weight').nth(1).selectOption('1');await page.locator('.hitl-run').click();await page.locator('.hitl-status').filter({hasText:'합계 100%'}).waitFor();assert.match(await page.locator('#evidence-panel').innerText(),/75/);
 await page.setViewportSize({width:390,height:844});await page.locator('.hitl-selected').scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));await page.screenshot({path:path.join(output,'mobile-selection.png')});
 assert.deepEqual(errors,[]);console.log('PASS HITL browser: desktop/mobile, 2 factors, directions, unweighted/weighted rerun, charts, no horizontal overflow or JS errors');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
