const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Mijin/Desktop/project_city/node_modules/playwright-core');
const root=path.resolve(__dirname,'..'),live=process.argv.includes('--live'),url='https://education-living-area-preview-production.up.railway.app',out=path.resolve(root,'../outputs/map_layers_20260912',live?'live':'preview');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],requests=[];page.setDefaultTimeout(60000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/map_layers/'))requests.push(r.url());});
 if(!live)await page.route(url+'/**',route=>{const p=new URL(route.request().url()).pathname,file=p==='/'?'index.html':p.slice(1);if(['index.html','assets/school-map.js','assets/kakao-maps.js','assets/map-layers.js','assets/map-layers.css'].includes(file)||file.startsWith('data_processed/map_layers/'))return route.fulfill({path:path.join(root,file),contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/html'});return route.continue();});
 await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelectorAll('[data-context-layer]').length===12);assert.equal(requests.length,1,'Only manifest loads until layers selected');assert.equal(await page.locator('#map-layer-groups details[open]').count(),0);
 await page.selectOption('#school','B000002949');await page.waitForFunction(()=>document.querySelector('#school-map').dataset.walkingAreas==='1');
 for(const group of ['nature','learning','housing','safety'])await page.locator('[data-layer-group="'+group+'"]>summary').click();
 for(const id of ['parks','libraries','care','apartments','redevelopment','construction','accidents']){await page.locator('[data-context-layer="'+id+'"]').check();await page.waitForFunction(id=>!document.querySelector('#map-layer-status').textContent.includes('불러오는 중'),id);}
 assert.equal(await page.locator('.map-layer-chip').count(),7);await page.locator('#map-fit').click();await page.waitForFunction(()=>Number(document.querySelector('#school-map').dataset.contextCount)>500);await page.locator('#school-map').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'grouped-map-desktop.png')});
 await page.locator('#map-layer-list>summary').click();assert(await page.locator('#map-layer-table tr').count()>0);await page.locator('#map-layer-table button').first().click();await page.waitForTimeout(700);assert(await page.locator('.kakao-evidence-popup').isVisible(),'Popup remains after viewport update');await page.locator('.kakao-popup-close').click();
 await page.locator('#map-layers-clear').click();assert.equal(await page.locator('.map-layer-chip').count(),0);assert(await page.locator('#map-walkshed').isChecked());
 await page.locator('[data-context-layer="clusters"]').check();await page.waitForFunction(()=>!document.querySelector('#map-layer-status').textContent.includes('불러오는 중'));await page.locator('#map-fit').click();await page.waitForFunction(()=>Number(document.querySelector('#school-map').dataset.contextCount)>0);if(!await page.locator('#map-layer-list').getAttribute('open'))await page.locator('#map-layer-list').evaluate(e=>e.open=true);await page.locator('#map-layer-table button').first().click();await page.getByRole('button',{name:/이 구역의 학원/}).click();await page.locator('.map-member-list button').first().waitFor();assert(await page.locator('.map-member-list button').count()>=10);await page.screenshot({path:path.join(out,'academy-members.png')});
 await page.reload({waitUntil:'domcontentloaded'});await page.locator('[data-context-layer="clusters"]:checked').waitFor({state:'attached'});assert.equal(await page.locator('.map-layer-chip').count(),1);await page.setViewportSize({width:390,height:844});await page.locator('.map-layer-panel').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'grouped-map-mobile.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
 // Disable during a slow response: late data must never resurrect an unchecked layer.
 await page.locator('[data-layer-group="nature"]>summary').click();await page.route('**/map_layers/playgrounds.json',async route=>{await new Promise(r=>setTimeout(r,800));return live?route.continue():route.fulfill({path:path.join(root,'data_processed/map_layers/playgrounds.json'),contentType:'application/json'});});await page.locator('[data-context-layer="playgrounds"]').check();await page.locator('[data-context-layer="playgrounds"]').uncheck();await page.waitForTimeout(1200);assert.equal(await page.locator('[data-facility-layer="playgrounds"]').count(),0);
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify({passed:true,live,checked_at:new Date().toISOString(),checks:['12 layer toggles in collapsed groups','lazy data fetch','real Kakao rendering and viewport grouping','facility table and durable popup','clear preserves walking controls','academy membership drilldown','restored selections','mobile no overflow','slow response does not resurrect disabled layers'],errors},null,2));console.log('PASS grouped map layers '+(live?'LIVE':'PREVIEW'));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
