'use strict';
const {chromium}=require('C:/Users/Mijin/Desktop/project_city/node_modules/playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
process.env.UPDATE_CENTER_STORE_PATH=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'question-levers-')),'store.json');delete process.env.DATABASE_URL;
const server=require('./serve_policy_studio.cjs'),live=process.env.LEVERS_BASE_URL;
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const out=path.join(__dirname,'../outputs/question-levers',live?'live':'preview');fs.mkdirSync(out,{recursive:true});try{
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/chat')&&r.method()==='POST')requests.push(r.postDataJSON());});page.setDefaultTimeout(65000);
 await page.goto(live||'http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});await page.locator('.workspace-nav [data-workspace="ask"]').click();await page.selectOption('#chat-scope','all');
 await page.fill('#question','전체 초등학교 도서관 지원을 검토해줘');await page.locator('#send').click();const panel=page.locator('.hitl-plan').last();await panel.locator('[data-factor="books:books.total"]').check();await panel.locator('[data-factor="library_access:nearest_m.public_children"]').check();
 await panel.locator('.hitl-selected .direction').nth(0).selectOption('lower');await panel.locator('.hitl-selected .direction').nth(1).selectOption('higher');
 await panel.locator('.question-conclusion').waitFor();await page.waitForFunction(()=>document.querySelector('.hitl-status')?.textContent.includes('현재 체크'));
 assert(await panel.locator('.hitl-priority').isVisible());assert.equal(await panel.locator('input[type=range]').count(),2);assert.equal(await panel.locator('.hitl-weighted').count(),0);
 async function weights(a,b){await panel.locator('.weight').nth(0).fill(String(a));await panel.locator('.weight').nth(1).fill(String(b));await page.waitForTimeout(1100);await page.waitForFunction(()=>document.querySelector('.hitl-status')?.textContent.includes('현재 체크'));}
 const before=requests.filter(r=>r.action==='hitl_run').length;await weights(80,20);const first=await panel.locator('.conclusion-text').innerText();assert(first.includes('장서'));assert(first.includes('도서 구입'));await weights(20,80);const second=await panel.locator('.conclusion-text').innerText();assert(second.includes('도서관'));assert(second.includes('순회대출'));assert.notEqual(first,second);assert.equal(requests.filter(r=>r.action==='hitl_run').length,before,'weight-only changes must use local cached evidence');
 await panel.locator('.conclusion-dot').first().click();assert(await panel.locator('.conclusion-members tbody tr').count()>0);await panel.locator('.hitl-priority').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'weights-and-conclusion-desktop.png')});
 await page.setViewportSize({width:390,height:844});await weights(21,79);await weights(20,80);await panel.locator('.hitl-priority').scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await page.screenshot({path:path.join(out,'weights-mobile.png')});await panel.locator('.question-conclusion').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'conclusion-mobile.png')});
 await panel.locator('.weight').nth(0).fill('0');await panel.locator('.weight').nth(1).fill('0');await page.waitForTimeout(900);assert.equal(await panel.locator('.question-conclusion').count(),0);assert((await panel.locator('.hitl-status').innerText()).includes('하나 이상'));
 await weights(30,70);await panel.locator('[data-factor="library_access:nearest_m.public_children"]').uncheck();await page.waitForTimeout(1500);await page.waitForFunction(()=>document.querySelector('.hitl-status')?.textContent.includes('현재 체크'));assert.equal(await panel.locator('.weight').count(),1);
 const topic=await page.locator('.topic-select').inputValue();assert(topic);const saved=await page.evaluate(id=>new Promise((resolve,reject)=>{const r=indexedDB.open('beyond-radius-analysis-topics',1);r.onsuccess=()=>{const q=r.result.transaction('topics').objectStore('topics').get(id);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);};}),topic);assert(saved.entries.some(e=>e.request?.factors?.some(f=>f.weight===80)&&e.result?.conclusion));await page.reload({waitUntil:'domcontentloaded'});await page.locator('.workspace-nav [data-workspace="ask"]').click();await page.locator('.topic-select option[value="'+topic+'"]').waitFor({state:'attached'});await page.locator('.topic-select').selectOption(topic);await page.locator('.analysis-topics details summary').click();assert((await page.locator('.topic-history').innerText()).includes('순회대출'));assert.equal(await page.locator('.hitl-plan').count(),0);assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify({passed:true,live:!!live,checked_at:new Date().toISOString(),checks:['related checkbox candidates','visible range levers after selection','auto analysis','local weight updates without API requests','changed substantive conclusion','actual school dot drilldown','mobile no overflow','all zero clears stale result','selection removal','topic history persists without current decision restore'],errors,analysis_requests:requests.filter(r=>r.action==='hitl_run').length},null,2));console.log('PASS browser question levers '+(live?'LIVE':'PREVIEW'));
 }finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
