const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Mijin/Desktop/SAbuffet/node_modules/playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.QA_BASE||'http://127.0.0.1:8877',out='outputs/visualization-20260916';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Users/Mijin/AppData/Local/ms-playwright/chromium-1243/chrome-win64/chrome.exe'});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base);await page.locator('.workspace-nav [data-workspace=stats]').click();await page.locator('.ds-context').waitFor();
await page.locator('[data-indicator=green_ratio]').click();await page.locator('.ds-context').screenshot({path:out+'/decision-context.png'});
await page.locator('.ds-main-histogram').screenshot({path:out+'/distribution.png'});
assert.equal(await page.locator('.ds-districts .ds-spread-details').count(),1);assert.equal(await page.locator('.ds-spread-details').evaluate(e=>e.open),false);
const counts=await page.locator('.ds-hist-count').allTextContents();assert(counts.length>0);
await page.locator('[data-view=district]').click();await page.locator('.ds-districts').screenshot({path:out+'/district.png'});
const district=await page.locator('[data-district-open]').first().getAttribute('data-district-open');await page.locator('[data-district-open]').first().click();
assert.equal(await page.locator('#stats-district').inputValue(),district);assert((await page.locator('#stats-school-table tbody tr').count())>0);
assert((await page.locator('#stats-school-table tbody tr td:nth-child(2)').allTextContents()).every(x=>x===district));
await page.locator('[data-view=relationship]').click();await page.locator('.ds-pair-metrics').waitFor();await page.locator('#stats-pair').selectOption('books_per_student');await page.locator('.ds-relationship svg').waitFor();await page.locator('.ds-relationship').screenshot({path:out+'/relationship.png'});
await page.locator('[data-track=island]').click();await page.locator('.ds-pair-metrics').waitFor();assert((await page.locator('.ds-context-heading').innerText()).includes('강화·옹진'));
await page.locator('[data-view=distribution]').click();await page.locator('#stats-domain').selectOption('reading');await page.locator('#stats-level').selectOption('유치원');await page.waitForFunction(()=>document.querySelector('.ds-overview')?.textContent.includes('관측된 값이 없습니다'));
assert((await page.locator('.ds-context').innerText()).includes('판단을 보류'));assert.equal(await page.locator('.ds-hist-count').count(),0);
await page.locator('#stats-level').selectOption('초등학교');await page.locator('#stats-domain').selectOption('park');await page.locator('[data-track=general]').click();
await page.setViewportSize({width:390,height:844});await page.locator('#workspace-stats').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/mobile.png'});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile document width');
const width=await page.locator('.ds-dashboard').evaluate(e=>e.getBoundingClientRect().width);assert(width>250);
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/browser-check.json',JSON.stringify({base,at:new Date(),passed:true,checks:['decision context','histogram labels','district drilldown','cross-domain scatter','island separation','missing deferral','mobile overflow'],errors},null,2));console.log('PASS visual story browser',base);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
