'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ExcelJS=require('../assets/vendor/exceljs/exceljs.min.js');
const {chromium}=require('C:/Users/Mijin/Desktop/project_city/node_modules/playwright-core');
const base='https://education-living-area-preview-production.up.railway.app',out=path.resolve(__dirname,'../outputs/hitl-release-validation/live');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(60000);await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('.workspace-nav [data-workspace="ask"]').click();await page.locator('#chat-scope').selectOption('all');const question='학교 학생 수와 CSV TSV Excel JSON으로 제공한 현장 시험자료 네 가지를 함께 검토해줘';await page.locator('#question').fill(question);await page.locator('#send').click();await page.locator('.hitl-dataset').selectOption('schools');await page.getByRole('button',{name:'학생 수 +',exact:true}).click();await page.locator('.hitl-year').fill('2026');await page.getByText('내 자료·현장 의견 추가',{exact:true}).click();await page.locator('#upload-details > summary').click();
 const rows=[['인천석암초등학교',120,2026],['인천신흥초등학교',80,2026],['인천송림초등학교',100,2026]];
 for(const ext of ['csv','tsv','xlsx']){const headers=['학교명',ext+' 시험값','연도'];let buffer;if(ext==='xlsx'){const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('현장 시험자료');sheet.addRow(headers);rows.forEach(r=>sheet.addRow(r));buffer=Buffer.from(await book.xlsx.writeBuffer());}else buffer=Buffer.from([headers,...rows].map(r=>r.join(ext==='csv'?',':'\t')).join('\n'));
 await page.locator('#upload-file').setInputFiles({name:'검증용.'+ext,mimeType:ext==='xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'text/plain',buffer});await page.locator('#upload-status').filter({hasText:'3행 × 3열'}).waitFor();await page.locator('#upload-existing').selectOption('schools:students');await page.locator('#upload-key-type').selectOption('school_name');await page.locator('#upload-key').selectOption('0');await page.locator('#upload-measure').selectOption('1');await page.locator('#upload-year').selectOption('2');await page.locator('#upload-value-type').selectOption('numeric');await page.locator('.hitl-add-upload').click();}
 await page.locator('.hitl-paste').fill(JSON.stringify({name:'검증용 JSON',headers:['학교명','JSON 시험값','연도'],rows,mapping:{type:'school_name',key:0,measure:1,year:2,existing:'schools:students',valueType:'numeric'}}));await page.locator('.hitl-add-paste').click();assert.equal(await page.locator('.hitl-uploads p').count(),4);
 await page.locator('.hitl-selected .weight').selectOption('1');const controls=page.locator('.hitl-uploads select');for(let i=0;i<4;i++){await controls.nth(i*2).selectOption('higher');await controls.nth(i*2+1).selectOption('2');}
 const response=page.waitForResponse(r=>r.url().endsWith('/api/chat')&&r.request().postDataJSON()?.action==='hitl_run');await page.locator('.hitl-run').click();const raw=await response,result=await raw.json();assert.equal(raw.status(),200,JSON.stringify(result));assert.equal(result.review.upload_count,4);assert.equal(result.review.factors.length,5);assert(result.review.factors.every(f=>f.share_percent!==null));const sections=result.visual.sections.filter(s=>s.title.includes('사용자 자료'));assert.equal(sections.length,4);assert(sections.every(s=>s.table.rows.length===3));assert(sections.every(s=>s.table.rows.find(r=>r[1]===120)?.[4]===100));await page.locator('.hitl-results button').first().waitFor();await page.locator('.hitl-uploads').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'upload-formats.png')});fs.writeFileSync(path.join(out,'upload-formats.json'),JSON.stringify({passed:true,checked:new Date().toISOString(),question,formats:['CSV','TSV','XLSX','JSON'],uploads:4,valid_rows:12,weighted_factors:5,result},null,2));console.log('PASS live upload formats: CSV TSV XLSX JSON, 4 uploads, 12 valid rows, explicit weights and directional percentiles');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});


