'use strict';
const {chromium}=require('C:/Users/Mijin/Desktop/SAbuffet/node_modules/playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=path.join(root,'outputs/indicator-expansion-20260916');
async function serve(){const handlers={'/api/domain-stats':require('../api/domain-stats'),'/api/school-summary':require('../api/school-summary'),'/api/school-profile':require('../api/school-profile')};const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(handlers[u.pathname])return await handlers[u.pathname](req,res);const file=path.resolve(root,'.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!file.startsWith(root+path.sep)){res.statusCode=403;return res.end();}res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.png':'image/png'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).on('error',()=>{res.statusCode=404;res.end();}).pipe(res);}catch(e){res.statusCode=500;res.end(e.message);}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return server;}
(async()=>{let server,browser;fs.mkdirSync(out,{recursive:true});try{if(!process.env.QA_BASE)server=await serve();const base=process.env.QA_BASE||'http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,executablePath:'C:/Users/Mijin/AppData/Local/ms-playwright/chromium-1243/chrome-win64/chrome.exe'});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/?school=B000002951');await page.locator('.workspace-nav [data-workspace="stats"]').click();await page.locator('.ds-chart-grid').waitFor();
async function domain(domain,level){const response=page.waitForResponse(r=>r.url().includes('/api/domain-stats?')&&r.url().includes('domain='+domain)&&decodeURIComponent(r.url()).includes('level='+level));if(await page.locator('#stats-level').inputValue()!==level)await page.locator('#stats-level').selectOption(level);else if(await page.locator('#stats-domain').inputValue()===domain){await page.locator('#stats-domain').dispatchEvent('change');}if(await page.locator('#stats-domain').inputValue()!==domain)await page.locator('#stats-domain').selectOption(domain);const data=await (await response).json();await page.waitForFunction(({domain,level})=>document.querySelector('.ds-dashboard')?.dataset.domain===domain&&document.querySelector('#stats-status')?.textContent.includes(level),{domain,level});return data;}
for(const level of ['중학교','고등학교','초등학교']){const data=await domain('reading',level);const expected=data.indicators.find(i=>i.column==='library_books_2026');assert(expected.coverage.available>0);await page.locator('[data-indicator="library_books_2026"][aria-pressed="true"]').waitFor();assert(await page.locator('.ds-indicators button:visible').count()<=9,'picker initially at most eight plus selected');assert((await page.locator('.ds-context-count').innerText()).includes('확보 '+expected.coverage.general.available+'/'));}
await page.locator('#stats-indicator-search').fill('예산');const found=await page.locator('.ds-indicators button:visible').allTextContents();assert(found.length>=2);assert(found.every(s=>s.includes('예산')));await page.locator('[data-indicator="library_purchase_budget_2026"]').click();await page.locator('[data-indicator="library_purchase_budget_2026"][aria-pressed="true"]').waitFor();assert(await page.locator('.ds-indicators button:visible').count()<=9);await page.locator('.ds-context-checks summary').click();assert((await page.locator('.ds-context-checks').innerText()).includes('2026'));assert(await page.locator('.ds-main-histogram').count());const budgetData=await (await page.request.get(base+'/api/domain-stats?domain=reading&level='+encodeURIComponent('초등학교'))).json(),budget=budgetData.indicators.find(i=>i.column==='library_purchase_budget_2026');assert((await page.locator('.ds-context-count').innerText()).includes('확보 '+budget.coverage.general.available+'/'));assert.equal((await page.locator('.ds-main-histogram .ds-hist-count').allTextContents()).reduce((n,s)=>n+Number(s),0),budget.coverage.general.available,'histogram uses same observed population');
await page.locator('.ds-context').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/library-budget.png'});
await domain('school','고등학교');await page.locator('[data-indicators-expand]').click();assert(await page.locator('.ds-indicators button:visible').count()>9);await page.locator('[data-indicator="scholarship_amount_2026"]').click();assert.equal(await page.locator('[data-indicator="scholarship_amount_2026"]').getAttribute('aria-pressed'),'true');assert(await page.locator('.ds-indicators button:visible').count()<=9);assert((await page.locator('.ds-context').innerText()).includes('장학금'));
await domain('trend','초등학교');for(const [id,phrase] of [['cohort_scenario_2029','가정에 따른 시나리오'],['age_residents_walkshed_500m_2024','공간·계산 추정']]){await page.locator('[data-indicators-expand]').click();await page.locator('[data-indicator="'+id+'"]').click();assert((await page.locator('.ds-context-checks summary').innerText()).includes(phrase));}
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'stats mobile page overflow');await page.screenshot({path:out+'/mobile.png'});
await page.setViewportSize({width:1440,height:1000});await page.locator('.workspace-nav [data-workspace="ask"]').click();
const columns=['scholarship_students_2026','scholarship_amount_2026','creative_clubs_2026','voluntary_clubs_2026','afterschool_subject_programs_2026','afterschool_specialty_programs_2026','grade1_students_2026','grade2_students_2026','library_books_2026','library_purchase_budget_2026'];const result=require('../api/_agent_tools').run('query_schools',{level:'고등학교'},{island:'exclude',limit:10,columns});assert.equal(result.visual.table.headers.length,12);
await page.evaluate(r=>window.ChatWorkspace.show({observation_version:1,visual:{sections:[r.visual]},sources:r.sources},'새로 연결한 열 개 지표를 함께 비교'),result);assert.equal(await page.locator('.table-comparison input:checked').count(),10);assert.equal(await page.locator('.tc-heatmap').count(),1);assert.equal(await page.locator('.tc-table th').count(),12);await page.locator('[data-expand]').click();assert(await page.locator('.tc-scroll').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'10 new variables fit expanded');await page.screenshot({path:out+'/new-indicators-table.png'});await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'chat mobile page overflow');assert.deepEqual(errors,[]);
fs.writeFileSync(out+'/check.json',JSON.stringify({passed:true,base,checkedColumns:columns,at:new Date()},null,2));console.log('PASS indicator expansion: defaults, searchable compact picker, budget, scholarship, evidence kinds, 10-column heatmap, desktop/mobile',base);
}finally{await browser?.close();if(server)await new Promise(resolve=>server.close(resolve));}})().catch(e=>{console.error(e);process.exitCode=1;});
