'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Mijin/Desktop/project_city/node_modules/playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
process.env.UPDATE_CENTER_STORE_PATH=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'policy-studio-browser-')),'store.json');delete process.env.DATABASE_URL;
const server=require('./serve_policy_studio.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const output=path.join(__dirname,process.env.POLICY_STUDIO_BASE_URL?'../outputs/policy-studio-live':'../outputs/policy-studio');fs.mkdirSync(output,{recursive:true});try{
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.POLICY_STUDIO_BASE_URL||'http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});await page.locator('.workspace-nav [data-workspace="ask"]').click();
 await page.locator('.topic-name').fill('검증: 장서 지원');await page.locator('.topic-new').click();await page.locator('.topic-select option').filter({hasText:'검증: 장서 지원'}).waitFor({state:'attached'});
 await page.locator('.policy-studio > summary').click();await page.locator('.ps-track').selectOption('general');await page.locator('.ps-target').fill('30000');await page.locator('.ps-budget').fill('10000000');await page.locator('.ps-cost').fill('15000');await page.locator('.ps-gap-weight').fill('70');await page.locator('.ps-scale-weight').fill('30');await page.locator('.ps-purpose').fill('동일 장서 목표까지의 수량과 학생 규모를 함께 검토');await page.locator('.ps-run').click();await page.locator('.ps-status').filter({hasText:'선택 목표 미달 관측'}).waitFor({timeout:65000});assert((await page.locator('#evidence-panel').innerText()).includes('목표까지 수량'));await page.locator('#evidence-panel .vs-table input').first().fill('인천신흥');assert((await page.locator('#evidence-panel').innerText()).includes('10,987'));await page.locator('#evidence-panel').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'support-quantity-desktop.png')});
 await page.locator('.visual-atlas summary').click();await page.locator('.atlas-dataset').selectOption('books');await page.locator('.atlas-section option').nth(1).waitFor({state:'attached'});await page.locator('.atlas-section').selectOption({index:1});await page.locator('#evidence-panel .vs-strip circle').first().waitFor();await page.locator('#evidence-panel .vs-strip circle').first().click();await page.locator('.vs-drill-table tr').nth(1).waitFor();assert((await page.locator('.vs-drill-table').innerText()).includes('학교'));await page.locator('.vs-drill-table').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'distribution-school-drilldown.png')});
 await page.locator('#evidence-panel .vs-chart details summary').click();const bin=page.locator('#evidence-panel .vs-bar:not([disabled])').first();await bin.click();await page.locator('.vs-drill-table tbody tr').first().waitFor();assert(await page.locator('.vs-drill-table tbody tr').count()>0);
 await page.reload({waitUntil:'domcontentloaded'});await page.locator('.workspace-nav [data-workspace="ask"]').click();await page.locator('.topic-select option').filter({hasText:'검증: 장서 지원'}).waitFor({state:'attached'});const id=await page.locator('.topic-select option').filter({hasText:'검증: 장서 지원'}).getAttribute('value');await page.locator('.topic-select').selectOption(id);await page.locator('.analysis-topics details summary').click();await page.getByRole('button',{name:'당시 근거 다시 보기',exact:true}).first().click();assert((await page.locator('.vs-history-warning').innerText()).includes('자동 복원하지'));assert.equal(await page.locator('.ps-target').inputValue(),'');await page.screenshot({path:path.join(output,'topic-restoration.png')});
 await page.locator('#question').fill('장서·도서관 지원에 필요한 자료');await page.locator('#send').click();await page.locator('.collection-card').first().waitFor({timeout:65000});assert((await page.locator('.collection-assistant').innerText()).includes('수집할까요'));assert((await page.locator('.collection-assistant').innerText()).includes('자동 내용 수집 미연결'));
 await page.setViewportSize({width:390,height:844});await page.locator('.policy-studio > summary').click();await page.locator('.policy-studio').scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(output,'support-mobile.png')});assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(output,'browser-validation.json'),JSON.stringify({passed:true,checks:['real quantity','search all rows','dot click schools','bin click schools','indexeddb refresh','historical result warning','no recommendation restore','collection capability prompts','mobile width'],errors},null,2));console.log('PASS browser: support quantities, dot/bin drilldown, topic persistence, collection prompts, mobile');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
