'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),base='https://education-living-area-preview-production.up.railway.app',out=path.join(root,'outputs/hitl-release-validation/live');fs.mkdirSync(out,{recursive:true});
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
async function post(data){const r=await fetch(base+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:AbortSignal.timeout(90000)});const d=await r.json();assert.equal(r.status,200,d.summary);return d;}
(async()=>{const report={base,started:new Date().toISOString(),assets:[],domains:[],checks:[]};const release=fs.readFileSync(path.join(root,'outputs/hitl-release-path.txt'),'utf8').trim();
 for(const name of ['index.html','assets/hitl-analysis.js','assets/hitl-analysis.css','assets/chat-workspace.js','assets/simple-app.js']){const r=await fetch(base+'/'+name,{signal:AbortSignal.timeout(40000)});assert.equal(r.status,200);const remote=sha(Buffer.from(await r.arrayBuffer())),local=sha(fs.readFileSync(path.join(release,'vercel_public',name)));assert.equal(remote,local,name);report.assets.push({name,sha256:remote});}
 const plan=await post({action:'hitl_plan',question:'등교길 안전인력을 추가 지원한다면 어떤 학교? 왜?',scope:'all',level:'초등학교'});assert(plan.checks.some(s=>s.includes('통학 경로가 아닙니다')));assert.equal(plan.catalog.length,42);
 for(const e of plan.catalog){const opts=await post({action:'hitl_options',dataset_id:e.id}),factor=opts.factors.find(f=>f.field)||opts.factors[0],d=await post({action:'hitl_run',version:plan.version,question:e.title+' 여러 요소 검토',level:'초등학교',scope:'all',year:2025,factors:[{id:factor.id,direction:'observe',weight:null}]});assert.equal(d.review.decision,'deferred');assert.equal(d.visual.chart,null);assert(Object.values(d.review.gates).every(s=>s==='unverified'));report.domains.push({id:e.id,factors:opts.factors.length,sections:d.visual.sections.length});console.log('PASS live '+e.id);}
 const invalid=await fetch(base+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'hitl_run',version:plan.version,question:'지원 학교 순위',factors:[{id:'books:score',direction:'higher',weight:3}]})});assert.equal(invalid.status,400);report.checks.push('unknown score rejected with HTTP 400','42 domains actual HTTP','no default weights or scores','independent verification gates','live assets match release SHA256','commute and park routes distinguished');report.finished=new Date().toISOString();report.passed=true;fs.writeFileSync(path.join(out,'api-audit.json'),JSON.stringify(report,null,2));console.log('PASS live release audit');})().catch(e=>{console.error(e);process.exitCode=1;});
