import assert from 'node:assert/strict';
import {extractIceNotice, fetchIceNotice, checkPageNotice} from '../update_center/page_notice.mjs';
import {autoApplyEvents} from '../update_center/automatic.mjs';
const url = 'https://www.ice.go.kr/ice/na/ntt/selectNttInfo.do?nttSn=3353108';
const html = (views=1, body='공개 명단', id='a'.repeat(32)) => `<div class="bbs_ViewA"><h3>학교 현황</h3><ul class="bbsV_data"><li>조회수 ${views}</li></ul><div class="bbsV_cont"><div><p>${body}</p></div></div><div class="bbsV_atchmnfl"><a class="fileName" href="javaScript:goFileDown('${id}');">명단.xlsx</a></div></div>`;
const response = body => new Response(body, {headers: {'content-type':'text/html; charset=utf-8'}});
assert.deepEqual(extractIceNotice(html(1)), extractIceNotice(html(999)), 'view counters are excluded');
assert.throws(() => extractIceNotice('<html><h3>로그인</h3></html>'));
assert.throws(() => extractIceNotice(html().replace('학교 현황','접근 거부')));
assert.throws(() => extractIceNotice(html().replace(/a{32}/,'unsupported-id')));
await assert.rejects(fetchIceNotice('https://other.example/ice/na/ntt/selectNttInfo.do?nttSn=1', () => {throw Error('must not fetch');}), /허용된/);
await assert.rejects(fetchIceNotice(url, async () => new Response('',{status:403})), /403/);
await assert.rejects(fetchIceNotice(url, async () => new Response('{}',{headers:{'content-type':'application/json'}})), /HTML/);
await assert.rejects(fetchIceNotice(url, async () => response('x'.repeat(2*1024*1024+1))), /크기/);
await assert.rejects(fetchIceNotice(url, async (_url,options) => {assert.equal(options.redirect,'error');assert.ok(options.signal);throw Error('redirect rejected');}), /redirect/);
const state = {}, events = [], audits = [];
const store = {recordEvent:async e => {events.push(e);return {...e,id:String(events.length)};},appendAudit:async e => {audits.push(e);}};
const entry = {dataset:'notice',auto_apply:true,check:{type:'page_notice',urls:{page:url}}};
let body = html(); const opts = {fetchImpl:async () => response(body)};
assert.equal((await checkPageNotice(entry,state,store,opts)).outcome,'baseline');
body = html(999);
assert.equal((await checkPageNotice(entry,state,store,opts)).outcome,'unchanged');
body = html(999,'개정 명단');
let result = await checkPageNotice(entry,state,store,opts);
assert.equal(result.outcome,'yellow');assert.equal(result.event.diff_json.observation_only,true);
assert.equal(result.event.diff_json.approval_blocked,true);
assert.deepEqual(await autoApplyEvents([result.event],[entry],store,{apply:async()=>{throw Error('must not apply');}}),[]);
body = html(999,'개정 명단','b'.repeat(32));
assert.equal((await checkPageNotice(entry,state,store,opts)).outcome,'yellow');
body = '<html>로그인 필요</html>';
assert.equal((await checkPageNotice(entry,state,store,opts)).outcome,'error');
assert.equal((await checkPageNotice(entry,state,store,opts)).outcome,'error-unchanged');
assert.equal(state.notice.lastStatus,'error');
body = html(999,'개정 명단','b'.repeat(32));
assert.equal((await checkPageNotice(entry,state,store,opts)).outcome,'unchanged');
assert.equal(state.notice.lastStatus,'ok');
assert.equal(state.notice.error,undefined,'recovery clears stale failure details');
console.log('PASS ICE notice parsing, stable counters, changed body/files, invalid responses, size and redirect guards, errors, and no auto apply');
