import type { SchoolDetailReportProps } from "./SchoolDetailReportPagePreview";

export const previewSchoolDetailReport: SchoolDetailReportProps = {
  schoolName: "인천석암초등학교",
  districtName: "인천광역시 미추홀구",
  casePolicyLabel: "즉시 개선 대상",
  caseStatusLabel: "공원 접근 불가",
  statusSummary:
    "도보권 공원이 없고, 생활권 안 녹지와 놀이시설도 확인되지 않는 학교입니다. 즉시 개선 검토가 필요한 상태입니다.",
  nearestParkDistanceM: 947.1,
  nearestParkName: "주안공원",
  nearestParkDistanceCityAvg: 1176.827,
  nearestParkDistanceDistrictAvg: 266.061,
  nearestParkDistanceCityPercentile: 10.7,
  nearestParkDistanceDistrictPercentile: 4.3,
  greenRatio: 0,
  greenRatioCityAvg: 7.845,
  greenRatioDistrictAvg: 4.106,
  greenRatioCityPercentile: 35.7,
  greenRatioDistrictPercentile: 21.7,
  greenRatioCityPercentile_lt: 0.0,
  greenRatioDistrictPercentile_lt: 0.0,
  playgroundCount: 0,
  straightLinePlaygroundCount: 0,
  playgroundCountCityAvg: 0.471,
  playgroundCountDistrictAvg: 0.13,
  playgroundCountCityPercentile: 88.6,
  playgroundCountDistrictPercentile: 91.3,
  playgroundCountCityPercentile_lt: 0.0,
  playgroundCountDistrictPercentile_lt: 0.0,
  noParkWithin500m: true,
  accessibilityRatio: 0,
  parkShortageVsAvg: -2.485294117647059,
  studentTrend: [
    { year: "2020", value: 837 },
    { year: "2021", value: 846 },
    { year: "2022", value: 922 },
    { year: "2023", value: 950 },
    { year: "2024", value: 940 },
    { year: "2025", value: 902 },
  ],
  studentTrendChangePct: 7.766,
  studentTrendCityAvg: -10.955,
  studentTrendDistrictAvg: -12.072,
  currentStudentCount2025: 902,
  currentStudentCountCityPercentile: 16.2,
  currentStudentCountDistrictPercentile: 30.4,
  potentialDemand2029: 629,
  potentialDemand2031: 602,
  hasLargeApartmentComplexNearby: false,
  similarityK: 4,
  similaritySelectionFeatures:
    "current_students_2025, student_slope, recent_student_change_pct, trend_volatility, iso_child_total, large_apt_count_500m, large_apt_households_500m, redev_완료수, redev_진행중수, redev_예정수, is_new_school",
  similarityComparisonFeatures:
    "nearest_park_dist_m, iso_green_ratio, iso_playground_count",
  similarityCommonPoints:
    "유사학교와 재개발 상태가 비슷합니다 (없음) | 유사학교와 신설학교 여부가 비슷합니다 | 유사학교와 학생 수가 줄어드는 흐름이 비슷합니다",
  similarityStrengthsText:
    "유사학교 평균보다 최근접 공원 거리가 193.9m 더 가깝습니다",
  similarityWeaknessesText:
    "유사학교 평균보다 녹지 비율이 5.0%p 더 낮습니다 | 유사학교 평균보다 도보권 놀이터 수가 1개 더 적습니다",
  similarityPeerAvgNearestParkDistanceM: 243.9,
  similarityPeerAvgGreenRatio: 5.86,
  similarityPeerAvgPlaygroundCount: 0.75,
  similarSchools: [
    {
      schoolName: "인천부마초등학교",
      districtName: "부평구",
      nearestParkDistanceM: 801.4,
      greenRatio: 0,
      playgroundCount: 0,
      rank: 1,
      similarityDistance: 0.61,
    },
    {
      schoolName: "인천부원초등학교",
      districtName: "부평구",
      nearestParkDistanceM: 752.2,
      greenRatio: 0,
      playgroundCount: 0,
      rank: 2,
      similarityDistance: 0.74,
    },
    {
      schoolName: "인천용마초등학교",
      districtName: "부평구",
      nearestParkDistanceM: 408,
      greenRatio: 1.425490563160452,
      playgroundCount: 0,
      rank: 3,
      similarityDistance: 0.89,
    },
    {
      schoolName: "인천화전초등학교",
      districtName: "계양구",
      nearestParkDistanceM: 400,
      greenRatio: 0.05990862430115607,
      playgroundCount: 0,
      rank: 4,
      similarityDistance: 0.97,
    },
  ],
  cityBestEnvironmentSchool: {
    schoolName: "인천청호초등학교",
    districtName: "서구",
    nearestParkDistanceM: 156,
    greenRatio: 23.624856214233546,
    playgroundCount: 0,
  },
  districtBestEnvironmentSchool: {
    schoolName: "인천연학초등학교",
    districtName: "미추홀구",
    nearestParkDistanceM: 121.4,
    greenRatio: 17.246475819091096,
    playgroundCount: 0,
  },
  problemTags: [
    "도보권 공원이 없어 공원 접근이 단절된 상태입니다",
    "녹지 비율과 도보권 놀이터 수가 모두 0입니다",
    "도보권 아동 수가 높아 개선 우선순위가 큽니다",
  ],
  contextTags: [
    "보행 동선에 대로 횡단 구간이 있습니다",
    "학교 주변에서 바로 대체할 수 있는 공원 선택지가 없습니다",
    "주거 밀도 대비 아동 체류 공간이 부족합니다",
  ],
  onSimulationClick: () => {
    window.alert("프리뷰 환경입니다. 실제 시뮬레이션은 아직 연결되지 않았습니다.");
  },
};
