"""Compare student-weighted green-access scenarios.

The input files are generated by the student-green correlation step. This script
summarizes the base/new-town-adjusted scenarios and exports comparison tables,
hotspot lists, JSON, and a Markdown report for the final narrative.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
from scipy import stats


BASE = Path(r"C:\2026_data_analysis_park")
REPORTS = BASE / "outputs" / "reports"

DONG_PATH = REPORTS / "incheon_student_green_by_base_dong_20260424.csv"
SCHOOL_PATH = REPORTS / "incheon_student_green_school_assigned_20260424.csv"

OUT_SUMMARY = REPORTS / "incheon_student_green_scenario_compare_20260424.csv"
OUT_TOP = REPORTS / "incheon_student_green_scenario_hotspots_20260424.csv"
OUT_JSON = REPORTS / "incheon_student_green_scenario_compare_20260424.json"
OUT_MD = REPORTS / "incheon_student_green_scenario_compare_20260424.md"

NEW_TOWN_DONGS = {"송도동", "청라동", "영종동"}


def corr_value(df: pd.DataFrame, x_col: str, y_col: str, method: str) -> tuple[float, float, int]:
    tmp = df[[x_col, y_col]].apply(pd.to_numeric, errors="coerce").dropna()
    n = len(tmp)
    if n < 3 or tmp[x_col].nunique() < 2 or tmp[y_col].nunique() < 2:
        return float("nan"), float("nan"), n
    if method == "pearson":
        stat, p = stats.pearsonr(tmp[x_col], tmp[y_col])
    elif method == "spearman":
        stat, p = stats.spearmanr(tmp[x_col], tmp[y_col])
    elif method == "kendall":
        stat, p = stats.kendalltau(tmp[x_col], tmp[y_col])
    else:
        raise ValueError(method)
    return float(stat), float(p), n


def summarize_scenario(name: str, dong: pd.DataFrame, school: pd.DataFrame) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []

    rows.append(
        {
            "scenario": name,
            "metric_group": "coverage",
            "metric": "dong_count",
            "value": float(len(dong)),
            "note": "",
        }
    )
    rows.append(
        {
            "scenario": name,
            "metric_group": "coverage",
            "metric": "school_count",
            "value": float(len(school)),
            "note": "",
        }
    )

    summary_metrics = [
        ("weighted_green_ratio_mean", dong["weighted_green_ratio"].mean(), "동별 학생가중 녹지비율 평균"),
        ("weighted_green_ratio_median", dong["weighted_green_ratio"].median(), "동별 학생가중 녹지비율 중앙값"),
        ("weighted_nearest_park_dist_mean", dong["weighted_nearest_park_dist_m"].mean(), "동별 학생가중 최근접 공원거리 평균"),
        ("park_area_per_student_mean", dong["park_area_per_student"].mean(), "동별 학생 1인당 공원면적 평균"),
        ("low_green_student_share_mean", dong["low_green_student_share"].mean(), "동별 저녹지 학교 학생 비중 평균"),
        ("no_park_student_share_mean", dong["no_park_student_share"].mean(), "동별 공원 0개 학교 학생 비중 평균"),
    ]
    for metric, value, note in summary_metrics:
        rows.append(
            {
                "scenario": name,
                "metric_group": "summary",
                "metric": metric,
                "value": float(value),
                "note": note,
            }
        )

    corr_specs = [
        ("total_students", "weighted_green_ratio"),
        ("total_students", "weighted_nearest_park_dist_m"),
        ("total_students", "park_area_per_student"),
        ("total_students", "low_green_student_share"),
        ("child_0_12", "weighted_green_ratio"),
        ("child_0_12", "no_park_student_share"),
    ]
    for x_col, y_col in corr_specs:
        for method in ["pearson", "spearman", "kendall"]:
            stat, p_value, n = corr_value(dong, x_col, y_col, method)
            rows.append(
                {
                    "scenario": name,
                    "metric_group": "correlation",
                    "metric": f"{method}:{x_col}->{y_col}",
                    "value": stat,
                    "note": f"p={p_value:.6f}, n={n}",
                }
            )
    return rows


def hotspot_table(dong: pd.DataFrame, scenario: str) -> pd.DataFrame:
    med_students = dong["total_students"].median()
    med_green = dong["weighted_green_ratio"].median()
    med_low = dong["low_green_student_share"].median()
    selected = dong[
        (dong["total_students"] >= med_students)
        & (
            (dong["weighted_green_ratio"] <= med_green)
            | (dong["low_green_student_share"] >= med_low)
        )
    ].copy()
    selected["scenario"] = scenario
    selected = selected.sort_values(
        ["low_green_student_share", "weighted_green_ratio", "total_students"],
        ascending=[False, True, False],
    )
    return selected[
        [
            "scenario",
            "gu",
            "base_dong",
            "school_count",
            "total_students",
            "child_0_12",
            "weighted_green_ratio",
            "park_area_per_student",
            "low_green_student_share",
            "no_park_student_share",
            "weighted_nearest_park_dist_m",
        ]
    ].head(15)


def main() -> None:
    dong = pd.read_csv(DONG_PATH)
    school = pd.read_csv(SCHOOL_PATH)

    school = school[school["is_island_tag"].fillna(0).eq(0)].copy()
    dong_base = dong.copy()
    school_base = school.copy()

    dong_ex = dong[~dong["base_dong"].isin(NEW_TOWN_DONGS)].copy()
    school_ex = school[~school["base_dong"].isin(NEW_TOWN_DONGS)].copy()

    rows = []
    rows.extend(summarize_scenario("baseline_non_island", dong_base, school_base))
    rows.extend(summarize_scenario("exclude_songdo_cheongna_yeongjong", dong_ex, school_ex))
    summary = pd.DataFrame(rows)
    summary.to_csv(OUT_SUMMARY, index=False, encoding="utf-8-sig")

    hotspots = pd.concat(
        [
            hotspot_table(dong_base, "baseline_non_island"),
            hotspot_table(dong_ex, "exclude_songdo_cheongna_yeongjong"),
        ],
        ignore_index=True,
    )
    hotspots.to_csv(OUT_TOP, index=False, encoding="utf-8-sig")

    payload = {
        "note": "Baseline already excludes schools tagged as island.",
        "excluded_base_dongs": sorted(NEW_TOWN_DONGS),
        "summary_rows": summary.to_dict(orient="records"),
        "hotspots": hotspots.to_dict(orient="records"),
        "outputs": {
            "summary_csv": str(OUT_SUMMARY.relative_to(BASE)),
            "hotspots_csv": str(OUT_TOP.relative_to(BASE)),
            "json": str(OUT_JSON.relative_to(BASE)),
            "markdown": str(OUT_MD.relative_to(BASE)),
        },
    }
    OUT_JSON.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    pivot = summary.pivot(index="metric", columns="scenario", values="value")

    def v(metric: str, scenario: str) -> float:
        return float(pivot.loc[metric, scenario])

    md = f"""# 학생-녹지 시나리오 비교 (2026-04-24)

## 기준
- `baseline_non_island`: 기존 분석 그대로, 이미 `섬지역` 제외
- `exclude_songdo_cheongna_yeongjong`: 기존 분석에서 `송도동`, `청라동`, `영종동` 추가 제외

## 핵심 비교
| 지표 | 기본(비도서) | 신도시 제외 |
|---|---:|---:|
| 동 수 | {v('dong_count', 'baseline_non_island'):.0f} | {v('dong_count', 'exclude_songdo_cheongna_yeongjong'):.0f} |
| 학교 수 | {v('school_count', 'baseline_non_island'):.0f} | {v('school_count', 'exclude_songdo_cheongna_yeongjong'):.0f} |
| 동별 학생가중 녹지비율 평균 | {v('weighted_green_ratio_mean', 'baseline_non_island'):.3f} | {v('weighted_green_ratio_mean', 'exclude_songdo_cheongna_yeongjong'):.3f} |
| 동별 학생가중 녹지비율 중앙값 | {v('weighted_green_ratio_median', 'baseline_non_island'):.3f} | {v('weighted_green_ratio_median', 'exclude_songdo_cheongna_yeongjong'):.3f} |
| 동별 학생가중 최근접 공원거리 평균(m) | {v('weighted_nearest_park_dist_mean', 'baseline_non_island'):.3f} | {v('weighted_nearest_park_dist_mean', 'exclude_songdo_cheongna_yeongjong'):.3f} |
| 학생 1인당 공원면적 평균 | {v('park_area_per_student_mean', 'baseline_non_island'):.3f} | {v('park_area_per_student_mean', 'exclude_songdo_cheongna_yeongjong'):.3f} |
| 저녹지 학교 학생 비중 평균 | {v('low_green_student_share_mean', 'baseline_non_island'):.3f} | {v('low_green_student_share_mean', 'exclude_songdo_cheongna_yeongjong'):.3f} |
| 공원 0개 학교 학생 비중 평균 | {v('no_park_student_share_mean', 'baseline_non_island'):.3f} | {v('no_park_student_share_mean', 'exclude_songdo_cheongna_yeongjong'):.3f} |

## 상관 비교
| 관계 | 기본 Spearman | 신도시 제외 Spearman |
|---|---:|---:|
| 총학생수 -> 학생가중 녹지비율 | {v('spearman:total_students->weighted_green_ratio', 'baseline_non_island'):.3f} | {v('spearman:total_students->weighted_green_ratio', 'exclude_songdo_cheongna_yeongjong'):.3f} |
| 총학생수 -> 학생가중 최근접 공원거리 | {v('spearman:total_students->weighted_nearest_park_dist_m', 'baseline_non_island'):.3f} | {v('spearman:total_students->weighted_nearest_park_dist_m', 'exclude_songdo_cheongna_yeongjong'):.3f} |
| 총학생수 -> 학생 1인당 공원면적 | {v('spearman:total_students->park_area_per_student', 'baseline_non_island'):.3f} | {v('spearman:total_students->park_area_per_student', 'exclude_songdo_cheongna_yeongjong'):.3f} |
| 총학생수 -> 저녹지 학생 비중 | {v('spearman:total_students->low_green_student_share', 'baseline_non_island'):.3f} | {v('spearman:total_students->low_green_student_share', 'exclude_songdo_cheongna_yeongjong'):.3f} |
| 0~12세 아동수 -> 학생가중 녹지비율 | {v('spearman:child_0_12->weighted_green_ratio', 'baseline_non_island'):.3f} | {v('spearman:child_0_12->weighted_green_ratio', 'exclude_songdo_cheongna_yeongjong'):.3f} |
| 0~12세 아동수 -> 공원0개 학교 학생 비중 | {v('spearman:child_0_12->no_park_student_share', 'baseline_non_island'):.3f} | {v('spearman:child_0_12->no_park_student_share', 'exclude_songdo_cheongna_yeongjong'):.3f} |

## 산출물
- `{OUT_SUMMARY.relative_to(BASE)}`
- `{OUT_TOP.relative_to(BASE)}`
- `{OUT_JSON.relative_to(BASE)}`
"""
    OUT_MD.write_text(md, encoding="utf-8")
    print(md)


if __name__ == "__main__":
    main()
