'use strict';
const fs=require('node:fs'),path=require('node:path'),yaml=require('js-yaml'),root=path.resolve(__dirname,'..');
// Requirements describe missing decision evidence, never infer a shortage from coverage.
const needs=[
 {id:'reading',match:/도서|독서|장서|사서|책|문해/,title:'독서 자원과 실제 이용',datasets:['libraries','school_library','school_public_disclosures'],have:'도서관 위치·장서·좌석·사서 공시',need:'학교별 이용 학생·대기자, 개방 시간, 사서 실제 근무시간',why:'시설·장서 수만으로 학생이 실제 이용하는지와 필요한 지원량을 정할 수 없습니다.',fields:['학교명','연도','이용학생수_명','대기학생수_명','주당개방시간_시간','사서근무시간_시간'],effect:'장서 확충·인력·개방시간 조정 중 검토할 대안을 구체화합니다.'},
 {id:'outdoor',match:/공원|녹지|놀이터|야외|실외|운동장|산책|체육|운동|놀\s*곳|뛰어놀|뛰놀|갈\s*곳|쉴\s*곳/,title:'야외활동 공간과 이용 조건',datasets:['parks','student_services'],have:'공원·놀이터·일부 운동시설 위치와 보행 도달권',need:'학생 이용 가능 시간, 연령·예약 조건, 실제 출입구와 시설 상태',why:'지도상 위치와 대표점 도달권만으로 이용 가능·접근 안전을 확인할 수 없습니다.',fields:['학교명','연도','시설명','개방시간','이용자격','출입구위도','출입구경도','시설상태'],effect:'시설 확충과 기존 시설 개방·연계 대안을 구분합니다.'},
 {id:'route',match:/도보|보행|통학|등교|하교|횡단|교통|안전|사고|위험|접근|거리|건너|보도|차량|차가\s*많/,title:'실제 통학·이용 경로와 안전',datasets:['school_zones'],have:'학구도·보행 500m 도달권·일부 경로, 2024 인천 사고다발 중심점 11곳',need:'출입구 간 보행경로, 횡단시설, 보도 단절, 시간대별 통행량과 안전 점검',why:'학구 경계와 사고 중심점은 학생의 실제 이동 경로나 경로 안전 검증을 대신하지 않습니다.',fields:['학교명','연도','출발출입구','도착출입구','실측도보거리_m','횡단횟수_회','보도단절','안전확인','확인일'],effect:'경로 개선·운영 변경·시설 연계의 안전 조건을 확인합니다.',gate:true},
 {id:'demand',match:/인구|학생|수요|예측|미래|입주|대단지|아파트|재건축|재개발|개발|공사|폐교|과밀/,title:'향후 학생 수요와 개발 일정',datasets:['school_public_disclosures','redevelopment','construction_yeonsu','construction_michuhol','construction_gyeyang'],have:'연도별 학생 공시·수요 모형, 대단지·정비사업·일부 구 착공 기록',need:'확정 입주 시기·세대수, 연령별 전입, 취학 예정자와 학구 변경 계획',why:'사업·착공 기록과 모형 예측은 현재 공사 여부나 실제 입주·취학 수요의 확정값이 아닙니다.',fields:['학교명','연도','사업명','입주예정일','확정세대수_세대','취학예정자_명','계획확정여부'],effect:'현재 지원과 장래 수요 대응 시기를 나눠 검토합니다.'},
 {id:'care',match:/돌봄|방과후|청소년|복지|취약|맞벌이|혼자|퇴근|방치|하교\s*후/,title:'돌봄·청소년 지원의 수용 여건',datasets:['student_services','school_public_disclosures'],have:'돌봄 시설과 청소년 방과후아카데미 일부 목록',need:'기관별 정원·현원·대기자, 이용 연령·비용·시간과 학교 연계 가능 여부',why:'일부 시설 목록의 개수가 지역 전체 청소년 복지의 공급·부족을 뜻하지 않습니다.',fields:['학교명','연도','기관명','정원_명','현원_명','대기자_명','이용연령','이용시간','비용_원'],effect:'신규 확충·정원 조정·기관 연계 중 가능한 대안을 검토합니다.'},
 {id:'academy',match:/학원|사교육|학원가/,title:'학원 분포와 실제 교육비·이용',datasets:[],have:'등록 학원 위치와 탐색용 밀집 구역',need:'수강료·과목·운영 상태, 학생의 실제 이용과 교육비 조사',why:'등록 위치의 밀집도를 실제 사교육 참여율이나 교육 격차로 단정할 수 없습니다.',fields:['학교명','연도','조사대상수_명','참여학생수_명','월교육비_원','조사방법'],effect:'공간 분포 관측과 실제 이용·비용 격차를 구분합니다.'},
 {id:'environment',match:/미세먼지|폭염|그늘|소음|기후|대기질|더위/,title:'활동 시간대의 환경 조건',datasets:[],have:'학교·공원 위치 자료',need:'동일 시기·시간대 기온·미세먼지·소음, 그늘과 휴식시설 조사',why:'현재 위치 자료에 활동 시간대별 노출과 현장 상태가 연결되어 있지 않습니다.',fields:['학교명','연도','측정일시','측정위치','기온_C','미세먼지_ug_m3','그늘확인','측정방법'],effect:'활동 시간 조정·그늘 확충·공간 대안을 검토합니다.'},
 {id:'outcome',match:/학업|성취|성적|수능|의대|효과|인과|향상/,title:'성과와 효과 검증',datasets:[],have:'환경·자원 관측 자료; 질문한 성과와의 연결 근거는 별도 확인 필요',need:'동일 집단·시점의 성과 정의, 비교 집단, 사전·사후 측정과 교란 요인',why:'자원 수나 단순 상관관계로 교육 성과·정책 효과를 대신 추정할 수 없습니다.',fields:['학교명','연도','지표명','측정값','단위','측정시점','비교집단','측정방법'],effect:'효과 분석이 가능한 설계인지 확인하며 학교 성과 순위는 생성하지 않습니다.'},
 {id:'execution',match:/지원|예산|배분|확충|투자|우선|정책|개선|추천|해결/,title:'지원량·실행 가능성 확인',datasets:[],have:'질문에 관련된 현재 자원 관측과 선택한 검토 가중치',need:'지원 대상·자격, 운영 주체 동의, 수용 여력, 견적·단가·예산과 목표 수량',why:'어느 학교에 얼마나 지원할지는 목표·단가와 이용·안전·실행·경로 근거가 있어야 비교할 수 있습니다.',fields:['학교명','연도','지원자원','이용자격','운영주체동의','수용여력','목표수량','단위','단가_원','예산_원','안전근거','경로근거'],effect:'필수 조건을 확인한 대안에 한해 선택한 정책 선호로 조건부 순서·지원량을 검토합니다.',gate:true}
];
let cached;
function sources(){const file=path.join(root,'data_sources.yaml'),mtime=fs.statSync(file).mtimeMs;if(cached?.mtime===mtime)return cached.rows;const rows=(yaml.load(fs.readFileSync(file,'utf8')).sources||[]).map(s=>({dataset:s.dataset,provider:s.provider,source_url:/^https?:\/\//.test(s.source_url||'')?s.source_url:null,coverage:s.coverage||s.notes||'',check:{type:s.check?.type},auto_apply:s.auto_apply===true,available:!!s.local_file&&fs.existsSync(path.join(root,s.local_file)),path:s.local_file||null}));cached={mtime,rows};return rows;}
function plan(p,d={}){
 const q=String(p.question||'').slice(0,500);if(!q)return null;
 const factorWords={books:'장서',schools:'학생',routes:'도보',route_review:'도보',residential:'입주',academies:'학원',clusters:'학원가',services:'돌봄',shared_parks:'공원'};
 const context=q+' '+(p.factors||[]).map(f=>factorWords[String(f.id).split(':')[0]]||'').join(' '),all=sources(),chosen=needs.filter(n=>n.match.test(context));
 const supplied=[p.upload,...(p.uploads||[])].filter(Boolean).flatMap(u=>u.headers||[]);
 const items=chosen.map(n=>{const refs=all.filter(s=>n.datasets.includes(s.dataset));return {id:n.id,title:n.title,supplied_fields:n.fields.filter(f=>supplied.includes(f)),available:n.have,coverage:'보유 자료집 수준의 확인입니다. 요청한 학교·연도·항목의 값이 모두 있다는 뜻은 아닙니다.',needed:n.need,reason:n.why,decision_effect:n.effect,fields:[...n.fields,'출처','기준일'],priority:n.gate?'판단 전 필수 확인':'관련 근거 보완',status:'추가 근거 확인 필요',sources:refs,method:refs.some(s=>['refresh_pipeline','school_zones','json_api'].includes(s.check.type))?'공개자료 갱신 + 기관·현장 자료':'기관 자료 확보·파일 첨부 또는 현장 조사'};});
 const gaps=(d.visual?.sections||[]).filter(s=>s.statistics&&(s.statistics.excluded>0||s.statistics.n===0)).slice(0,6).map(s=>`${s.title}: 유효 ${s.statistics.n}건 · 제외 ${s.statistics.excluded}건. 제외 사유와 해당 학교·연도 자료를 확인하세요.`);
 if(d.join?.excluded>0)gaps.unshift(`첨부 ${d.join.total}행 중 ${d.join.excluded}행 미연결·제외. 연결 상태 표에서 학교명·연도·중복·결측을 확인하세요.`);
 return {version:1,question:q,scope:{school_id:p.school_id||null,level:p.level||null,year:p.year||null},items,observed_gaps:gaps,unresolved:!items.length?'검토할 문제·대상·기간을 구체화하면 필요한 자료를 좁힐 수 있습니다.':null,attachment:p.upload||p.uploads?.length?'첨부 자료도 연결 상태·출처·기준일과 필수 확인 조건을 검사해야 합니다. 첨부만으로 검증 완료가 되지 않습니다.':null,rule:(d.answerable&& !/지원|정책|개선|추천|문제|부족|격차|해결|확충|안전|검토/.test(q)?'현재 질문의 답변과 별도로, 더 깊은 정책 검토를 할 때 참고할 제안입니다. ':'')+'추가 수집 제안이며 미확보를 부족으로 판단하지 않습니다. 원문과 실제 수집 결과를 확인한 자료만 반영합니다.',engine:'등록 자료·질문별 근거 요건 대조 · 추가 모델 호출 없음'};
}
function enrich(d,p){if(p.action&&!['hitl_plan','hitl_run','hitl_ordered','hitl_overlap','studio_scenario'].includes(p.action))return d;const result=plan(p,d);if(result)d.collection_plan=result;return d;}
module.exports={plan,enrich,needs};
