// Canonical analytical sources. Historic scores/actions are deliberately not fields.
const entries=[
 ['designations','교육청 지정사업 원장','context/school_designations.json','지정사업,디지털 튜터,AI중점,자율학교,교육실습,미래교실','records','school_name,school_level,school_year,designation_type,program_name,period_status,verification_status'],
 ['schools','학교 공원 녹지 관측','education/analysis_dataset.json','학교,학생,원아,학급,교원,공원,녹지','schools','name,level,gu,year,students,classes,teachers,parks,green'],
 ['parks','공원 시설 원장','parks.csv','공원 목록,공원 시설,공원 면적','','공원명,공원구분,gu,공원면적,위도,경도'],
 ['playgrounds','어린이 놀이시설','geocoded_playground.csv','놀이터,놀이시설','',''],
 ['services','도서관 운동 돌봄 시설','student_services/priorities.json','돌봄,복지,운동 시설,체육 시설,도서관 목록','facilities','name,kind,address,eligibility_note,opening_hours,capacity,coordinate_status,source_url'],
 ['books','학교 장서 사서','student_services/priorities.json','장서,사서,독서','schools','name,student_year,students,books.year,books.per_student,books.staff'],
 ['library_access','도서관 거리별 접근','education/library_access_preview.json','도서관 접근,도서관 거리,도서관 분포','schools','name,level,nearest_m.public_children,nearest_m.including_small'],
 ['library_scenarios','도서관 거리권 인구 시나리오','education/library_access_preview.json','도서관 시나리오,도서관 거리권 인구','scenarios','level,radius_m,group,value,missing_cells'],
 ['academies','학원 교습소','education/academies.json','학원,교습소','','name,address,facility_type,target_category,reference_date,coordinate_status,source_url'],
 ['construction','착공 신고 공사장','context/facilities_construction.geojson','공사,착공','',''],
 ['nightlife','유흥 단란주점','context/facilities_nightlife.geojson','유흥,단란,주점','',''],
 ['redevelopment','재개발 사업','redevelopment_geocoded.csv','재개발,재건축,정비사업','','구역명,구명,위치,면적,사업유형,진행단계,출처'],
 ['apartments','대단지 아파트','large_apt_complexes_2025.csv','대단지,아파트,세대수','','단지명,시군구,세대수,도로명주소'],
 ['shared_parks','공원 공동 이용 부담','education/shared_parks.json','공동 이용,공유 공원,공원 공유,공원 부담','schools','name,level,gu,students_2026,park_count,sharing_school_count,shared_area_per_student,same_level_shared_area_per_student,largest_park_loss_share'],
 ['park_review','공원별 현장 확인 범위','education/field_verification.json','공원 현장,공원 확인 범위','parks','park_name,status,linked_schools,analyzed_schools'],
 ['resilience','도로 구간 중단 시나리오','education/road_resilience.json','도로 중단,도로 폐쇄,도로 대체','schools','name,level,status,segments_losing_500m_access'],
 ['clusters','학원 밀집 분석','education/academy_clusters.json','학원 밀집,학원가','schools','name,count_500m,facilities_per_km2_500m'],
 ['diffusion','지정학교 확산 시나리오','education/designation_diffusion.json','확산','scenarios','radius_m,probability_per_edge'],
 ['routes','공원 보행 경로','education/school_routes.json','보행,도보,경로,우회율','','name,status,park_name,route_distance_m,straight_distance_m,detour_ratio,method'],
 ['candidate_routes','격자 연결 경로 관측','candidate_barrier_routes_by_school.json','후보지 경로,격자 경로','','name,grid_id,route_length_m,note'],
 ['route_review','보행 경로 재검토','education/route_review.json','경로 검토,경로 재검토','schools','school_name,park_name,reviewed_distance_m,reviewed_source,reviewed_date,review_status,adopted_basis'],
 ['hybrid','출입구 경로 교차 검토','education/hybrid_walk_review.json','출입구,하이브리드','schools','school_name,park_name,entrances_verified,review_status,adopted_basis,legacy_distance_m'],
 ['residential','주거 구역 내부 통행 시나리오','education/residential_scenario.json','내부 통행,주거 구역,아파트 통행','schools','name,baseline.area_m2,scenario.area_m2,added_area_m2,status'],
 ['school_demand','생활권 연령 인구 추정','education/school_age_demand.json','생활권 인구,연령 수요,생활권 수요','schools',''],
 ['grid_demand','250m 격자 수요 시나리오','education/candidate_demand_v2.json','격자,250m,후보지 자료,후보지 시뮬레이션','candidates',''],
 ['forecast','학교 학생 수 예측','education/enrollment_forecasts.json','학생 예측,학생 수 예측,학생 전망,미래 학생,원아 전망,학생 수 전망','',''],
 ['cohort','학년 진급 시나리오','education/grade_cohort_scenarios.json','진급,학년,입학생','schools',''],
 ['demography','지역 연령 인구 관측','education/regional_demography.json','주민등록,지역 인구,거주 인구,인구 변화','',''],
 ['regional_forecast','지역 연령 인구 예측','education/regional_age_forecasts.json','인구 예측,인구 전망,지역 수요','',''],
 ['validation','지역 인구 모형 검증','education/regional_age_forecast_validation.json','모형 검증,예측 오차,예측 성능,prophet,xgboost','summary','school_level,horizon,n,selected_mae,persistence_mae'],
 ['school_validation','학교 예측 성능 검증','education/forecast_validation.json','학생 예측 성능,학교 예측 검증','',''],
 ['progression','졸업 후 진학 취업','education/school_progression.json','진학,취업,졸업','schools','name,year,status,metrics.graduates,metrics.advanced,metrics.published_progression_pct,metrics.employed,source_url'],
 ['athletics','학교 운동부 공시','education/school_athletics.json','운동부,선수,운동부 예산','schools','school_name,sport,athletes,posted_date,budget_raw,source_url'],
 ['sports_awards','체육 대회 결과 관측','education/sports_awards.json','체육 대회,메달,체육 실적','schools','school_name,year,event,category,discipline,result,result_basis,source_url'],
 ['science_awards','과학전람회 결과 관측','education/science_awards.json','과학전람회,과학 수상','schools','school_name,year,event,category,result,work_title,result_basis,source_url'],
 ['invention_awards','발명품 대회 결과 관측','education/invention_awards.json','발명,발명품','schools','school_name,year,event,category,result,work_title,result_basis,source_url'],
 ['curriculum','공동교육과정 개설 과목','education/curriculum_network.json','공동교육,개설 과목,공동 과정','courses','source_school_name,source_gu,kind,subject,target_grade,advertised_seats,credits'],
 ['curriculum_links','공동교육과정 연결망','education/curriculum_network.json','공동교육 연결망,과정 연결망','edges','provider_id,eligible_school_id,straight_distance_m'],
 ['indicators','학교 공시 지표','education/school_public_indicators.json','장학금,학비,동아리,방과후,체력,paps,공시 지표','schools',''],
 ['similar','유사학교 비교','education/school_analysis.json','유사학교,유사 학교,knn','',''],
 ['zones','학교 통학구역','education/school_zones.geojson','통학구역,학구,학교 구역','',''],
 ['walkshed','500m 보행 도달권','education/walkshed_500m.geojson','도달권,생활권 지도,보행권','',''],
];
module.exports=entries.map(([id,title,file,terms,rows,fields])=>({id,title,file:'data_processed/'+file,terms:terms.split(','),rows,fields:fields?fields.split(','):[]}));
