const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const catalog=require('./_data_catalog'),model=require('./_school_summary');
const intent=require('./_question_intent');
const ROOT=path.join(__dirname,'..'),cache=new Map();
const labels={name:'학교·시설',school_name:'학교',level:'학교급',school_level:'학교급',gu:'지역',year:'연도',kind:'자원 종류',status:'자료 상태',value:'관측값',label:'지표',unit:'단위',group:'구분',source_url:'원문 출처',source_school_name:'개설 학교',source_gu:'지역',subject:'과목',advertised_seats:'공고 정원',students:'학생 수',residents:'연령 인구',athletes:'선수 인원',sport:'종목',category:'유형',address:'주소',route_distance_m:'보행망 거리 m',straight_distance_m:'직선 거리 m',detour_ratio:'우회율',shared_area_per_student:'공유 공원면적 ㎡/명',same_level_shared_area_per_student:'동일 학교급 공유면적 ㎡/명',sharing_school_count:'공유 학교 수',park_count:'공원 관측 수',students_2026:'2026 재학생',largest_park_loss_share:'최대 공원 기여 비율',selected_mae:'선택모형 평균절대오차',persistence_mae:'유지모형 평균절대오차',horizon:'예측 선행연수',n:'관측 수',result:'확인 결과',work_title:'작품',posted_date:'게시일',reference_date:'기준일',eligibility_note:'이용 조건',opening_hours:'개방시간',capacity:'수용 인원',coordinate_status:'위치 확인',facility_type:'시설 유형',target_category:'교육 대상 구분',event:'대회',result_basis:'해석 기준',period:'구분',method:'산출 방법',park_name:'공원명',source:'출처'};
Object.assign(labels,{'공원면적':'공원면적 ㎡',grid_id:'격자 ID',route_length_m:'경로 길이 m',missing_cells:'인구 결측 격자 수',classes:'학급 수',teachers:'교원 수',parks:'도보권 공원 수',green:'추정 녹지비율 %',student_year:'학생 기준연도',reviewed_distance_m:'재검토 거리 m',reviewed_source:'재검토 자료',reviewed_date:'재검토일',review_status:'검토 상태',adopted_basis:'채택 기준',entrances_verified:'출입구 확인',legacy_distance_m:'이전 관측 거리 m',budget_raw:'예산 공개 방식',discipline:'세부 종목',target_grade:'대상 학년',credits:'학점',area_m2:'면적 ㎡',source_as_of:'자료 기준일',construction_status:'공사 진행 확인',business_status:'행정 영업 상태',mae:'평균절대오차 명',baseline_mae:'기준모형 오차 명',wape:'가중 절대비율오차',direction_accuracy:'증감 방향 일치율',provider_name:'개설 학교',eligible_name:'참여 가능 학교',basis:'비교 기준',linked_schools:'연결 학교 수',analyzed_schools:'분석 학교 수',segments_losing_500m_access:'중단 시 대안 미확보 구간 수',count_500m:'직선 500m 학원 수',facilities_per_km2_500m:'면적당 학원 수 개/㎢',radius_m:'연결 반경 m',probability_per_edge:'연결별 가정 확률','nearest_m.public_children':'공공 어린이도서관 직선거리 m','nearest_m.including_small':'작은도서관 포함 직선거리 m',school_year:'학년도',designation_type:'지정 유형',program_name:'사업',period_status:'지정 기간 상태',verification_status:'원문 확인 상태'});
const display=v=>({available:'자료 확보',observed:'관측',estimated:'배분 추정',missing:'미확보',unknown:'미확인',current:'해당 학년도',expired:'이전 학년도',official_roster:'공식 명단',park:'공원',library:'도서관',sports:'운동',welfare:'돌봄',straight_500m:'직선 500m',walkshed_500m:'분석 보행권 500m',footprint:'격자 내부',progression_pending_publication:'진학 상세 공시 대기',administrative_record_only_not_confirmed_active:'행정 신고 기록 · 현재 공사 미확인',address_geocoded:'주소로 위치 추정',integrated:'통합 교과',elementary:'초등 대상',middle:'중등 대상',high:'고등 대상',not_detected:'공간 군집 미확인'})[v]??(typeof v==='boolean'?(v?'확인':'미확인'):v);
const fieldLabel=k=>labels[k]||({'observations.2026.students':'2026 재학생','observations.2026.classes':'2026 학급 수','environment.parks':'도보권 공원 수','environment.green':'추정 녹지비율 %','books.per_student':'학생당 장서 권','books.staff':'사서 인원','books.year':'장서 기준연도','metrics.graduates':'졸업자','metrics.advanced':'진학자','metrics.published_progression_pct':'공시 진학률 %','metrics.employed':'취업자','baseline.area_m2':'기초 도달권 ㎡','scenario.area_m2':'가정 도달권 ㎡','added_area_m2':'가정 추가면적 ㎡'})[k]||k;
const get=(r,k)=>k.split('.').reduce((v,p)=>v?.[p],r);
const numeric=v=>typeof v==='number'&&Number.isFinite(v);
function csv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if((c===','||c==='\n')&&!quoted){row.push(cell.replace(/\r$/,''));cell='';if(c==='\n'){rows.push(row);row=[];}}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}const header=(rows.shift()||[]).map(s=>s.replace(/^\uFEFF/,''));return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(header.map((k,i)=>[k,r[i]!==''&&r[i]!=null&&/^-?\d+(\.\d+)?$/.test(r[i])?Number(r[i]):r[i]||null])));}
function read(entry){if(entry.id==='walkshed'){const general=read({...entry,id:'walkshed-general'}),file='data_processed/school_walkshed_500m_v3.geojson',elementary=read({id:'walkshed-elementary',file});return {...general,extraSource:{path:file,sha256:elementary.hash},data:{...general.data,features:[...elementary.data.features,...general.data.features]}};}const stat=fs.statSync(path.join(ROOT,entry.file));let c=cache.get(entry.id);if(c?.stamp===stat.mtimeMs)return c;const bytes=fs.readFileSync(path.join(ROOT,entry.file));const data=entry.file.endsWith('.csv')?csv(bytes.toString('utf8')):JSON.parse(bytes);c={stamp:stat.mtimeMs,data,hash:crypto.createHash('sha256').update(bytes).digest('hex')};cache.set(entry.id,c);return c;}
function rowsFor(e,data){
 let v=e.rows?get(data,e.rows):data,rows=[];
 if(e.id==='library_scenarios'){rows=v.flatMap(r=>data.levels.map((level,i)=>({level,radius_m:r.radius_m,group:r.supply,value:r.city_uncovered_age_population[i],missing_cells:r.city_missing_age_cells?.[i]})));}
 else if(e.id==='candidate_routes'){rows=Object.entries(v).flatMap(([id,grids])=>Object.entries(grids).map(([grid_id,r])=>({id,grid_id,route_length_m:r.route_length_m,note:r.note,route_coordinates:r.route_coords?.map(p=>[p[1],p[0]])})));}
 else if(e.id==='curriculum_links'){rows=v.map(r=>{const a=model.registry().find(s=>s.id===r.provider_id),b=model.registry().find(s=>s.id===r.eligible_school_id);return {...r,id:r.provider_id,name:a?.name,provider_name:a?.name,eligible_name:b?.name,route_coordinates:a&&b?[[a.lng,a.lat],[b.lng,b.lat]]:null};});}
 else if(e.id==='schools'){rows=v.flatMap(r=>Object.entries(r.observations||{}).map(([year,o])=>({...r,...o,...r.environment,year:Number(year)})));}
 else if(e.id==='school_validation'){for(const [level,r] of Object.entries(data))for(const ob of r.summary||[])rows.push({level,...ob});}
 else if(e.id==='indicators'){for(const [id,items] of Object.entries(v))for(const item of items)for(const ob of item.observations||[])for(const m of ob.metrics||[])rows.push({id,year:ob.publication_year,group:item.title,label:m.label,value:m.value,unit:m.unit,status:ob.status,source_url:ob.source_url});}
 else if(['forecast','cohort','demography','regional_forecast'].includes(e.id)){for(const [id,r] of Object.entries(v))for(const [key,group] of [['history','관측'],['forecast','예측'],['cohort_scenario','무이동 시나리오']])for(const p of r[key]||[])rows.push({id,name:r.region_name,level:r.school_level||id.split('|')[1],gu:r.region_name,year:p.year,value:p.students??p.residents,unit:'명',group,source_url:r.source_url,limitations:r.limitations||r.scope});}
 else if(['school_demand','grid_demand'].includes(e.id)){for(const [id,r] of Object.entries(v))for(const [area,a] of Object.entries(r))for(const [level,p] of Object.entries(a?.levels||{}))rows.push({id,level,group:area,value:p.estimated_residents,unit:'명',status:p.status,missing_parent_grids:p.missing_parent_grids,year:data.base_year});}
 else if(data.type==='FeatureCollection')rows=data.features.map(f=>({...f.properties,geometry:f.geometry,...(f.geometry?.type==='Point'?{lng:f.geometry.coordinates[0],lat:f.geometry.coordinates[1]}:{})}));
 else if(Array.isArray(v))rows=v;
 else rows=Object.entries(v).flatMap(([id,r])=>Array.isArray(r)?r.map(x=>({id,...x})):[{id,...r}]);
 const registry=model.registry(),byId=new Map(registry.map(s=>[s.id,s]));
 return rows.map((r,i)=>{const id=r.school_id||r.학교ID||r.id,s=byId.get(id);const name=r.name||r.school_name||r.학교명||r.공원명||r.단지명||r.구역명||s?.name||String(id||i+1);return {...r,id,name,level:r.level||r.school_level||r.학교급구분||s?.level,gu:r.gu||r.구명||r.시군구||s?.gu,lat:r.lat??r.latitude??r.위도??s?.lat,lng:r.lng??r.longitude??r.경도??s?.lng};});
}
function match(q){if(/도서관/.test(q)&&!/장서|사서|독서|거리|접근|분포|시나리오/.test(q))return catalog.find(e=>e.id==='services');if(/학생|원아/.test(q)&&/검증|성능|오차/.test(q))return catalog.find(e=>e.id==='school_validation');if(/학생|원아/.test(q)&&/미래|예측|전망/.test(q))return catalog.find(e=>e.id==='forecast');const token=q.toLowerCase().replace(/\s+/g,''),related=intent.resolve(q).matches;return catalog.filter(e=>related.has(e.id)).map(e=>({e,score:e.terms.filter(t=>t!=='학교').reduce((n,t)=>n+(token.includes(t.toLowerCase().replace(/\s+/g,''))?t.length:0),0)+(token.includes(e.title.replace(/\s+/g,''))?30:0)})).sort((a,b)=>b.score-a.score)[0]?.e;}
function catalogAnswer(){return {answerable:true,mode:'catalog',summary:'보유 자료와 기존 분석을 질문으로 열 수 있습니다. 아래에서 자료를 선택하거나 학교·지역·연도와 궁금한 내용을 함께 적어 주세요. 결과는 Word·PNG와 표 데이터로 저장할 수 있습니다.',sources:[],suggestions:catalog.map(e=>({label:e.title,question:e.title+' 자료 보여줘',dataset_id:e.id})),visual:{title:'질문으로 꺼내 보는 자료',table:{headers:['자료','질문 키워드'],rows:catalog.map(e=>[e.title,e.terms.join(' · ')])},notes:['원자료·시나리오·확인 기록은 서로 다른 의미입니다. 결과마다 기준과 한계를 표시합니다.']}};}
function distance(a,b){const rad=Math.PI/180,x=(a.lng-b.lng)*rad*Math.cos((a.lat+b.lat)*rad/2),y=(a.lat-b.lat)*rad;return 6371000*Math.hypot(x,y);}
function run(q,payload={}){
 if(!payload.dataset_id&&/수상/.test(q)&&!/과학|발명|체육|메달/.test(q)){const d=catalogAnswer();d.summary='수상 기록은 대회별 수집 범위가 달라 나누어 확인합니다. 어떤 자료를 볼지 선택해 주세요.';d.suggestions=d.suggestions.filter(s=>/awards/.test(s.dataset_id));return d;}
 if(/어떤.*(자료|데이터|분석)|보유.*(자료|데이터)|전체.*(데이터|분석).*목록|분석.*목록|데이터.*목록/.test(q))return catalogAnswer();
 const e=payload.dataset_id?catalog.find(e=>e.id===payload.dataset_id):match(q);if(!e)return null;
 const bundle=read(e),all=rowsFor(e,bundle.data);let rows=all;
 const named=model.registry().filter(s=>q.includes(s.name)),selected=named[0]||(!intent.allScope(q)&&payload.school_id?model.registry().find(s=>s.id===payload.school_id):null);
 const level=['초등학교','중학교','고등학교','유치원'].find(l=>q.includes(l))||selected?.level||(payload.level!=='전체'?payload.level:null);const gu=[...new Set(model.registry().map(s=>s.gu).filter(Boolean))].sort((a,b)=>b.length-a.length).find(g=>g&&q.includes(g));const year=Number(payload.year||q.match(/20\d{2}/)?.[0]);
 let notes=[];
 if(selected){if(all.some(r=>r.id===selected.id||r.name===selected.name||r.schools?.some(s=>s.id===selected.id)))rows=rows.filter(r=>r.id===selected.id||r.name===selected.name||r.schools?.some(s=>s.id===selected.id));else if(['parks','playgrounds','services','academies','construction','nightlife','redevelopment','apartments'].includes(e.id)){rows=rows.filter(r=>numeric(r.lat)&&numeric(r.lng)&&distance(r,selected)<=500);notes.push('선택 학교 대표점에서 직선 500m 이내 좌표 확보 시설입니다. 도보 접근·전수 시설·안전 검증이 아닙니다.');}else rows=[];}
 if(level)rows=rows.filter(r=>r.level===level||(!r.level&&['parks','services','academies','construction','nightlife','redevelopment','apartments'].includes(e.id)));
 if(gu)rows=rows.filter(r=>r.gu===gu||String(r.address||r.도로명주소||'').includes(gu));
 if(e.id==='schools'&&!year&&!/추세|연도별|변화/.test(q)){const latest=Math.max(...rows.map(r=>r.year));rows=rows.filter(r=>r.year===latest);notes.push(latest+'년 공시 관측. 공원·녹지는 현재 환경 스냅샷으로 같은 시점이라고 단정할 수 없습니다.');}
 if(year&&all.some(r=>r.year!=null))rows=rows.filter(r=>Number(r.year)===year);
 if(e.id==='services'){const kind=/돌봄|복지/.test(q)?'welfare':/운동|체육/.test(q)?'sports':/도서관/.test(q)?'library':null;if(kind&&!payload.dataset_id)rows=rows.filter(r=>r.kind===kind);}
 if(e.id==='indicators'){const topic=['장학금','학비','동아리','방과후','체력'].find(t=>q.includes(t))||(/paps/i.test(q)?'체력':null);if(topic)rows=rows.filter(r=>r.group.includes(topic));}
 if(e.id==='indicators'&&rows.length&&/상관|관계/.test(q)&&/학생/.test(q)){
  const candidates=[...new Set(rows.map(r=>r.label))],label=candidates.find(l=>q.includes(l))||candidates.find(l=>/금액/.test(q)&&/금액/.test(l))||candidates.find(l=>/수혜/.test(q)&&/수혜/.test(l));
  if(!label)return {...catalogAnswer(),summary:'비교할 공시 지표를 하나 지정해 주세요. 예: 2026 초등학교 장학금 금액과 학생 수 상관관계',suggestions:candidates.slice(0,12).map(l=>({label:l,question:`${year||2026} ${level||'초등학교'} ${l}과 학생 수 상관관계`,dataset_id:e.id}))};
  const engine=require('./_analysis_engine'),base=require('./analysis').dataset(),values=new Map();for(const r of rows.filter(r=>r.label===label&&r.year===(year||2026)&&numeric(r.value))){if(values.has(r.id))values.set(r.id,null);else values.set(r.id,r.value);}
  const dataset={...base,extra_fields:{public_metric:[label,rows.find(r=>r.label===label)?.unit||'']},schools:base.schools.map(s=>({...s,observations:{...s.observations,[year||2026]:{...s.observations[year||2026],public_metric:values.get(s.id)??null}}}))};
  const plan={method:'relationship',level:level||selected?.level||payload.level||'초등학교',gu:gu||'전체',year:year||2026,x:'public_metric',y:'students',controls:[]};const calculation=engine.analyze(dataset,plan);calculation.limitations.push('학교 ID와 공시연도로 일대일 연결한 지표입니다. 중복 지표·결측값은 제외하며 인과효과를 뜻하지 않습니다.');return {answerable:true,mode:'calculation',summary:calculation.summary,calculation,sources:[{id:'dataset#indicators',title:label,source:e.file,body:'공시 지표와 재학생 수의 탐색적 관계',provenance:[{path:e.file,sha256:bundle.hash}]}]};
 }
 let fields=e.fields.length?e.fields:['name','level','gu','year','group','label','value','unit','status','source_url'].filter(k=>rows.some(r=>r[k]!=null));
 if(e.id==='similar'){if(!selected){notes.push('유사학교는 학교를 선택한 후 비교합니다. 학생·주거 조건의 유사성이며 정책 우선순위가 아닙니다.');rows=[];}else{rows=rows.flatMap(r=>(r.similar_schools||[]).map(p=>({name:p.school_name,green:p.green_ratio,park_count:p.park_count,basis:r.knn_basis})));fields=['name','green','park_count','basis'];}}
 if(['construction','nightlife','playgrounds','zones','walkshed'].includes(e.id))fields=['name','gu','level','address','category','reference_date','source_as_of','construction_status','business_status','area_m2','method','source_url'].filter(k=>rows.some(r=>r[k]!=null));
 if(e.id==='indicators')fields=['name','level','year','group','label','value','unit','status','source_url'];
 if(e.id==='library_scenarios')notes.push('권역이 겹치는 시나리오는 서로 합산하지 않습니다. 결측 인구는 0으로 대체하지 않으며 후보 순위를 제시하지 않습니다.');
 if(e.id==='candidate_routes')notes.push('격자까지의 기존 경로 관측이며 토지 적합성·통행 허용·안전 검증을 완료했다는 뜻이 아닙니다.');
 if(e.id==='curriculum_links'){fields=['provider_name','eligible_name','straight_distance_m'];notes.push('공고의 제공·참여 가능 학교 연결입니다. 지도 선은 직선 관계도이며 실제 이동 경로·참여 실적이 아닙니다.');}
 if(e.id==='school_validation')fields=['level','horizon','n','mae','baseline_mae','wape','direction_accuracy'];
 const numericFields=fields.filter(k=>!['year','id','lat','lng'].includes(k)&&!/year|horizon|위도|경도/.test(k)&&rows.some(r=>numeric(get(r,k))));
 const nf=numericFields.find(k=>q.includes(fieldLabel(k)))||numericFields.find(k=>({students:/학생|원아/,classes:/학급/,teachers:/교원|교사/,parks:/공원/,green:/녹지/})[k]?.test(q))||({books:'books.per_student',shared_parks:'shared_area_per_student',validation:'selected_mae',school_validation:'mae',progression:'metrics.published_progression_pct'})[e.id]||numericFields[0];
 const valueRows=nf?rows.filter(r=>numeric(get(r,nf))):[];
 const sameMeasure=(e.id!=='indicators'||new Set(valueRows.map(r=>r.label+'|'+r.unit)).size===1)&&new Set(valueRows.map(r=>r.level).filter(Boolean)).size<=1&&new Set(valueRows.map(r=>r.year).filter(Boolean)).size<=1&&new Set(valueRows.map(r=>r.group).filter(Boolean)).size<=1;
 let chart=null,interpretation='';
 if(nf&&sameMeasure&&valueRows.length){const values=valueRows.map(r=>get(r,nf)).sort((a,b)=>a-b),median=(values[Math.floor((values.length-1)/2)]+values[Math.floor(values.length/2)])/2,mean=values.reduce((a,b)=>a+b,0)/values.length;interpretation=`${fieldLabel(nf)} 값이 있는 ${values.length}건의 중앙값은 ${Number(median.toFixed(2))}, 평균은 ${Number(mean.toFixed(2))}입니다. 범위는 ${Number(values[0].toFixed(2))}~${Number(values.at(-1).toFixed(2))}입니다. `;
  if(rows.every(r=>r.year!=null)&&new Set(rows.map(r=>r.name)).size===1&&new Set(rows.map(r=>r.label)).size<=1){chart={kind:'line',x:['연도','년'],y:[fieldLabel(nf),rows[0].unit||''],points:valueRows.map(r=>({x:r.year,y:get(r,nf),name:r.group||'관측'})).sort((a,b)=>a.x-b.x)};}
  else if(/분포|히스토그램|분석|해석/.test(q)){const min=values[0],max=values.at(-1),step=(max-min)/8||1,points=Array.from({length:8},(_,i)=>({name:`${Number((min+i*step).toFixed(1))}~${Number((min+(i+1)*step).toFixed(1))}`,value:0}));for(const v of values)points[Math.min(7,Math.floor((v-min)/step))].value++;chart={kind:'bar',unit:'건',points};}
 }
 if(nf&&valueRows.length&&rows.every(r=>r.year!=null)&&new Set(rows.map(r=>r.name)).size===1&&new Set(rows.map(r=>r.label)).size<=1&&new Set(rows.map(r=>r.unit)).size<=1)chart={kind:'line',x:['연도','년'],y:[fieldLabel(nf),rows[0].unit||''],points:valueRows.map(r=>({x:r.year,y:get(r,nf),name:r.group||'관측'})).sort((a,b)=>a.x-b.x)};
 if(!chart){const key=rows.some(r=>r.gu)?'gu':rows.some(r=>r.group)?'group':rows.some(r=>r.status)?'status':rows.some(r=>r.kind)?'kind':rows.some(r=>r.target_category)?'target_category':rows.some(r=>r.level)?'level':'name';if(key){const counts=new Map();for(const r of rows){const k=r[key]||'미확인';counts.set(k,(counts.get(k)||0)+1);}chart={kind:'bar',unit:'건',points:[...counts].sort(([a],[b])=>String(a).localeCompare(String(b),'ko')).map(([name,value])=>({name,value}))};}}
 const scalarNotes=[bundle.data.coverage,bundle.data.scope,bundle.data.scope_note,bundle.data.method,bundle.data.limitations].flat().filter(v=>typeof v==='string');notes.push(...scalarNotes,...new Set(rows.map(r=>r.limitations).filter(v=>typeof v==='string')));
 notes.push('수집 자료의 관측·기록 단위 집계입니다. 누락은 0이나 부족 확정이 아니며 평균·분포는 정책 효과나 학교 품질 순위가 아닙니다.','학교급·기준연도·행정구역이 다르면 직접 비교하지 않습니다. 도서지역은 별도 검토하며 이용·안전·실행·출입구 조건은 독립적으로 확인합니다.');
 if(nf&&!sameMeasure)notes.push('여러 학교급·연도·단위·관측과 예측이 섞여 있어 전체 수치 평균은 계산하지 않았습니다. 학교급과 연도 또는 학교를 지정하면 범위를 좁혀 분석합니다.');
 if(chart?.kind==='line'&&rows.some(r=>r.group==='예측')){notes.push('초록 실선은 실제 관측, 황색 점과 점선은 모형 예측입니다. 예측은 확정 수요가 아닙니다.');const obs=rows.filter(r=>r.group==='관측'&&numeric(r.value)).sort((a,b)=>a.year-b.year),pred=rows.filter(r=>r.group==='예측'&&numeric(r.value)).sort((a,b)=>a.year-b.year);if(obs.length&&pred.length)interpretation=`최근 ${obs.at(-1).year}년 관측 ${obs.at(-1).value}명에서 ${pred.at(-1).year}년 모형값 ${pred.at(-1).value}명으로 ${pred.at(-1).value>=obs.at(-1).value?'증가':'감소'}하는 시나리오입니다. `;}
 const maps=[...new Map(rows.filter(r=>numeric(r.lat)&&numeric(r.lng)).map(r=>[r.name+'|'+r.lat+'|'+r.lng,{name:r.name,lat:r.lat,lng:r.lng,detail:r.status||''}])).values()].slice(0,1500);
 const sources=[{id:'dataset#'+e.id,title:e.title,source:e.file,body:scalarNotes.join('\n')||'수집된 정규화 원장. 표의 원문 링크와 기준일을 함께 확인하세요.',provenance:[{path:e.file,sha256:bundle.hash},...(bundle.extraSource?[bundle.extraSource]:[])]}];
 const urls=[...new Set(rows.map(r=>r.source_url).filter(u=>/^https?:\/\//.test(u||'')))];sources.push(...urls.slice(0,20).map((url,i)=>({id:e.id+'#source'+i,title:'공개 원문 '+(i+1),source:url,body:'표의 해당 기록과 연결된 원문입니다.'})));
 if(rows.length>1500)notes.push(`화면·보고서 표와 지도는 앞 1,500건을 표시합니다. 집계는 필터에 맞는 ${rows.length.toLocaleString()}건 전체이며 전체 표는 CSV로 저장할 수 있습니다.`);
 if(chart?.kind==='bar')chart.points=chart.points.map(p=>({...p,name:display(p.name)}));
 const formatted=rows.map(r=>fields.map(k=>k==='source_url'?{url:r[k],label:'원문'}:display(get(r,k))??'미확보'));
 return {answerable:true,mode:'dataset',summary:`${e.title}: ${selected?.name||gu||'인천 전체'}${level?' · '+level:''}${year?' · '+year+'년':''} 조건에서 ${rows.length.toLocaleString()}건을 확인했습니다. ${interpretation}${rows.length?'기준과 한계를 함께 검토해 주세요.':'해당 범위의 수집 자료를 확보하지 못했습니다.'}`,school_id:selected?.id||null,sources,query:{dataset_id:e.id,year:year||null,level:level||null,gu:gu||null,school_id:selected?.id||null,total:rows.length},visual:{title:e.title,chart,map:maps,geometries:rows.filter(r=>r.geometry&&r.geometry.type!=='Point').slice(0,200).map(r=>({type:'Feature',properties:{name:r.name},geometry:r.geometry})),routes:rows.filter(r=>r.route_coordinates).slice(0,20).map(r=>({name:r.name,coordinates:r.route_coordinates})),table:{headers:fields.map(fieldLabel),rows:formatted.slice(0,1500)},notes},export_table:{headers:fields.map(fieldLabel),rows:formatted}};
}
module.exports={run,catalog,read,rowsFor,match,csv,fieldLabel,get};
